// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Capabilities {
    "canOpenProduct": boolean;
    "canStartRuntime": boolean;
    "canStopRuntime": boolean;
    "canRetryCleanupRuntime": boolean;
    "canRestartRuntime": boolean;
    "canStartLumen": boolean;
    "canStopLumen": boolean;
    "canRetryCleanupLumen": boolean;
    "canRestartLumen": boolean;
    "canResumeAfterFailedShutdown": boolean;
    "canRequestQuit": boolean;
    "canApplyUpdate": boolean;
}

export interface ConfigIssue {
    "path": string;
    "message": string;
}

export interface ConfigValidation {
    "valid": boolean;
    "fingerprint"?: string;
    "issues"?: ConfigIssue[] | null;
}

export enum DesiredState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesiredStopped = "stopped",
    DesiredRunning = "running",
    DesiredDisabled = "disabled",
};

/**
 * DesktopPreferences contains host-owned settings. These values are persisted
 * in settings.v1.json and are deliberately separate from the Server manifest.
 */
export interface DesktopPreferences {
    "version": number;
    "locale": string;
    "region": string;
    "updateChannel": string;
    "theme": string;
    "openProductOnLaunch": boolean;
}

export interface DesktopSnapshot {
    "instanceID": string;
    "revision": number;
    "host": HostSnapshot;
    "runtime": RuntimeSnapshot;
    "storage": StorageSummary;
    "lumen": LumenSnapshot;
    "update": UpdateSnapshot;
    "operations": OperationSnapshot[] | null;
}

export enum DotColor {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DotGray = "gray",
    DotYellow = "yellow",
    DotGreen = "green",
    DotRed = "red",
};

/**
 * Error is the only error shape exposed through Wails bindings and events.
 * Internal errors must be redacted before they reach this type.
 */
export interface Error {
    "code": ErrorCode;
    "message": string;
    "operationID"?: string;
}

/**
 * ErrorCode is a stable control-plane error identifier. The Settings client
 * must map these values exhaustively; display text is deliberately separate.
 */
export enum ErrorCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ErrorInvalidArgument = "invalid_argument",
    ErrorStaleVersion = "stale_version",
    ErrorStaleConfig = "stale_config",
    ErrorControllerBusy = "controller_busy",
    ErrorOperationConflict = "operation_conflict",
    ErrorOperationNotCancellable = "operation_not_cancellable",
    ErrorRuntimeNotConfigured = "runtime_not_configured",
    ErrorRuntimeNotReady = "runtime_not_ready",
    ErrorRepositoryControlUnavailable = "repository_control_unavailable",
    ErrorStorageLocationOffline = "storage_location_offline",
    ErrorStopTimeout = "stop_timeout",
    ErrorReadinessTimeout = "readiness_timeout",
    ErrorSignatureInvalid = "signature_invalid",
    ErrorShutdownInProgress = "shutdown_in_progress",
    ErrorLumenNotInstalled = "lumen_not_installed",
    ErrorLumenOwnerBusy = "lumen_owner_busy",
    ErrorRecoveryRequired = "recovery_required",
};

export interface HostActionTicket {
    "id": string;
    "requestID": string;
    "kind": string;
    "actor": string;
    "purpose"?: string;
    "name"?: string;
    "expectedVersion": number;
    "nonce": string;
    "status": string;
    "riskWarnings"?: string[] | null;
    "expiresAt": string;
}

export interface HostSnapshot {
    "bootPhase": string;
    "settingsVisible": boolean;
    "settingsNavigation": NavigationIntent;
    "preferences": DesktopPreferences;
    "shutdown": ShutdownSnapshot;
    "recovery"?: Error;
}

export enum LumenControlPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LumenControlUnspecified = "unspecified",
    LumenControlStarting = "starting",
    LumenControlDownloading = "downloading",
    LumenControlLoading = "loading",
    LumenControlWarmup = "warmup",
    LumenControlReady = "ready",
    LumenControlFailed = "failed",
    LumenControlStopping = "stopping",
};

export interface LumenControlStatus {
    "connected": boolean;
    "inferenceReady": boolean;
    "phase": LumenControlPhase;
    "version"?: string;
    "backend"?: string;
    "startedAtUnixMS"?: number;
    "download"?: LumenDownloadProgress | null;
    "services": LumenServiceStatus[] | null;
    "error"?: Error | null;
    "sequence": number;
}

export interface LumenDownloadProgress {
    "model": string;
    "file": string;
    "bytesDone": number;
    "bytesTotal": number;
    "filesDone": number;
    "filesTotal": number;
}

export enum LumenInstallPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LumenAbsent = "absent",
    LumenInstalling = "installing",
    LumenInstalled = "installed",
    LumenInstallFailed = "failed",
};

export interface LumenLogEntry {
    "timeUnixMS": number;
    "level": string;
    "target": string;
    "message": string;
    "fields": { [_ in string]?: string } | null;
}

export enum LumenProcessPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LumenStopped = "stopped",
    LumenStarting = "starting",
    LumenRunning = "running",
    LumenStopping = "stopping",
    LumenBackoff = "backoff",
    LumenFailed = "failed",
};

export interface LumenServiceStatus {
    "service": string;
    "phase": LumenControlPhase;
    "error"?: Error | null;
}

export interface LumenSnapshot {
    "version": number;
    "installPhase": LumenInstallPhase;
    "desiredState": DesiredState;
    "processPhase": LumenProcessPhase;
    "ownership": Ownership;
    "recoveryCause"?: ErrorCode;
    "profile"?: string;
    "preset": string;
    "cacheDir": string;
    "availableProfiles": string[] | null;
    "availablePresets": string[] | null;
    "control": LumenControlStatus;
    "installerAvailable": boolean;
    "processAvailable": boolean;
    "presentation": ProcessPresentation;
    "capabilities": Capabilities;
}

export interface NavigationIntent {
    "sequence": number;
    "route": string;
}

export interface OperationReceipt {
    "operationID": string;
    "requestID": string;
    "aggregate": string;
    "acceptedVersion": number;
}

export interface OperationSnapshot {
    "operationID": string;
    "requestID": string;
    "aggregate": string;
    "state": string;
    "cancellable": boolean;
    "error"?: Error;
}

export enum Ownership {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OwnershipNone = "none",
    OwnershipHeld = "held",
};

export interface ProcessPresentation {
    "color": DotColor;
    "label": string;
}

export interface RuntimeConfigDraft {
    "toml": string;
    "baseFingerprint": string;
    "candidateFingerprint": string;
    "source": string;
    "settings": RuntimeConfigSettings;
    "validation": ConfigValidation;
}

/**
 * RuntimeConfigSettings is the small, user-facing projection of the complete
 * Server manifest. The Desktop frontend edits this structure; Go patches the
 * authoritative TOML candidate and runs the real strict loader.
 */
export interface RuntimeConfigSettings {
    "networkMode": string;
    "listen": string;
    "storagePath": string;
    "loggingLevel": string;
    "hardwareAcceleration": string;
}

export enum RuntimePhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeStopped = "stopped",
    RuntimeStarting = "starting",
    RuntimeRunning = "running",
    RuntimeStopping = "stopping",
    RuntimeRestarting = "restarting",
    RuntimeSavingConfig = "saving-config",
    RuntimeApplyingConfig = "applying-config",
    RuntimeFailed = "failed",
};

export interface RuntimeSnapshot {
    "version": number;
    "desiredState": DesiredState;
    "phase": RuntimePhase;
    "ownership": Ownership;
    "recoveryCause"?: ErrorCode;
    "pendingConfigValidation": boolean;
    "configured": boolean;
    "manifestSHA256"?: string;
    "productURL"?: string;
    "presentation": ProcessPresentation;
    "capabilities": Capabilities;
}

export enum ShutdownPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShutdownIdle = "idle",
    ShutdownQuiescing = "quiescing",
    ShutdownFailed = "failed",
    ShutdownArmed = "armed",
};

export interface ShutdownSnapshot {
    "phase": ShutdownPhase;
    "operationID"?: string;
    "error"?: Error;
}

export interface StorageShortcut {
    "id": string;
    "name": string;
    "path"?: string;
    "kind"?: string;
    "status": string;
    "canOpen": boolean;
    "repositoryCount": number;
    "activeOperationCount": number;
    "canRemove": boolean;
    "removalBlockedBy"?: string;
    "filesPreserved": boolean;
    "writable": boolean;
    "capacityKnown": boolean;
    "totalBytes"?: number;
    "availableBytes"?: number;
    "filesystem"?: string;
}

export interface StorageSummary {
    "version": number;
    "count": number;
}

export interface UpdateSnapshot {
    "version": number;
    "phase": string;
    "channel": string;
    "currentVersion": string;
    "availableVersion"?: string;
    "providerAvailable": boolean;
    "error"?: Error;
    "canApply": boolean;
}
