// Command openapinormalize applies the RFC 9457 constraints that swag cannot
// express per response media type or as a literal discriminated union.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"server/internal/api/problem"

	"gopkg.in/yaml.v3"
)

const specPath = "docs/swagger.yaml"

func main() {
	data, err := os.ReadFile(specPath)
	if err != nil {
		panic(err)
	}
	var document yaml.Node
	if err := yaml.Unmarshal(data, &document); err != nil {
		panic(err)
	}
	root := document.Content[0]
	components := mappingValue(root, "components")
	schemas := mappingValue(components, "schemas")
	installProblemSchemas(schemas)
	rewriteProblemReferenceSchemas(root, schemas)
	normalized := normalizeResponses(mappingValue(root, "paths"))

	output, err := yaml.Marshal(&document)
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(specPath, output, 0o644); err != nil {
		panic(err)
	}
	writeJSONArtifacts(output)
	fmt.Printf("Normalized %d API error responses as RFC 9457 Problem Details.\n", normalized)
}

func rewriteProblemReferenceSchemas(root, schemas *yaml.Node) {
	walkNodes(root, func(current *yaml.Node) {
		if current.Kind == yaml.ScalarNode && current.Value == "#/components/schemas/problem.Reference" {
			current.Value = "#/components/schemas/api.ProblemReference"
		}
	})
	deleteMappingValue(schemas, "problem.Reference")
}

func walkNodes(current *yaml.Node, visit func(*yaml.Node)) {
	visit(current)
	for _, child := range current.Content {
		walkNodes(child, visit)
	}
}

func writeJSONArtifacts(yamlDocument []byte) {
	var document map[string]any
	if err := yaml.Unmarshal(yamlDocument, &document); err != nil {
		panic(err)
	}
	jsonDocument, err := json.MarshalIndent(document, "", "    ")
	if err != nil {
		panic(err)
	}
	jsonDocument = append(jsonDocument, '\n')
	if err := os.WriteFile("docs/swagger.json", jsonDocument, 0o644); err != nil {
		panic(err)
	}

	info, ok := document["info"].(map[string]any)
	if !ok {
		panic("OpenAPI info object is missing")
	}
	document["schemes"] = "__SWAG_SCHEMES__"
	info["description"] = "__SWAG_DESCRIPTION__"
	info["title"] = "__SWAG_TITLE__"
	info["version"] = "__SWAG_VERSION__"
	templateJSON, err := json.MarshalIndent(document, "", "    ")
	if err != nil {
		panic(err)
	}
	template := string(templateJSON)
	template = strings.Replace(template, `"__SWAG_SCHEMES__"`, `{{ marshal .Schemes }}`, 1)
	template = strings.Replace(template, `"__SWAG_DESCRIPTION__"`, `"{{escape .Description}}"`, 1)
	template = strings.Replace(template, `"__SWAG_TITLE__"`, `"{{.Title}}"`, 1)
	template = strings.Replace(template, `"__SWAG_VERSION__"`, `"{{.Version}}"`, 1)

	source := fmt.Sprintf(`// Code generated by swaggo/swag and normalized by tools/openapinormalize. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `+"`"+`%s`+"`"+`

var SwaggerInfo = &swag.Spec{
	Version: "1.0",
	Title: "Lumilio-Photos API",
	Description: "Media management system API with asset features",
	InfoInstanceName: "swagger",
	SwaggerTemplate: docTemplate,
	LeftDelim: "{{",
	RightDelim: "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
`, template)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("docs/docs.go", formatted, 0o644); err != nil {
		panic(err)
	}
}

func normalizeResponses(paths *yaml.Node) int {
	count := 0
	for index := 0; index+1 < len(paths.Content); index += 2 {
		path := paths.Content[index].Value
		if !strings.HasPrefix(path, "/api/v1") {
			continue
		}
		pathItem := paths.Content[index+1]
		for operationIndex := 0; operationIndex+1 < len(pathItem.Content); operationIndex += 2 {
			method := pathItem.Content[operationIndex].Value
			if !isHTTPMethod(method) {
				continue
			}
			responses := mappingValueOrNil(pathItem.Content[operationIndex+1], "responses")
			if responses == nil {
				continue
			}
			for responseIndex := 0; responseIndex+1 < len(responses.Content); responseIndex += 2 {
				status, err := strconv.Atoi(responses.Content[responseIndex].Value)
				if err != nil || status < 400 || status > 599 {
					continue
				}
				response := responses.Content[responseIndex+1]
				setMappingValue(response, "content", node(map[string]any{
					problem.MediaType: map[string]any{"schema": map[string]any{"$ref": problemSchemaRef(path, status)}},
				}))
				count++
			}
		}
	}
	return count
}

func problemSchemaRef(path string, status int) string {
	if status == 429 {
		return "#/components/schemas/api.RateLimitedProblemResponse"
	}
	if status == 409 && (path == "/api/v1/repositories" || path == "/api/v1/repository-candidates/open") {
		return "#/components/schemas/api.RepositoryConflictProblemResponse"
	}
	return "#/components/schemas/api.ProblemResponse"
}

func installProblemSchemas(schemas *yaml.Node) {
	registered := problem.Registered()
	union := make([]any, 0, len(registered)+1)
	referenceUnion := make([]any, 0, len(registered))
	discriminator := map[string]any{"about:blank": "#/components/schemas/api.AboutBlankProblem"}
	referenceDiscriminator := make(map[string]any, len(registered))

	setMappingValue(schemas, "api.AboutBlankProblem", node(problemSchema("about:blank", 0, nil)))
	union = append(union, map[string]any{"$ref": "#/components/schemas/api.AboutBlankProblem"})

	for _, descriptor := range registered {
		name := "api." + schemaName(descriptor.Type) + "Problem"
		refName := "api." + schemaName(descriptor.Type) + "ProblemReference"
		ref := "#/components/schemas/" + name
		referenceRef := "#/components/schemas/" + refName
		setMappingValue(schemas, name, node(problemSchema(descriptor.Type, descriptor.Status, descriptor.Extensions)))
		setMappingValue(schemas, refName, node(referenceSchema(descriptor.Type, descriptor.Extensions)))
		union = append(union, map[string]any{"$ref": ref})
		referenceUnion = append(referenceUnion, map[string]any{"$ref": referenceRef})
		discriminator[descriptor.Type] = ref
		referenceDiscriminator[descriptor.Type] = referenceRef
	}

	setMappingValue(schemas, "api.ProblemResponse", node(map[string]any{
		"oneOf": union,
		"discriminator": map[string]any{
			"propertyName": "type",
			"mapping":      discriminator,
		},
	}))
	setMappingValue(schemas, "api.ProblemReference", node(map[string]any{
		"oneOf": referenceUnion,
		"discriminator": map[string]any{
			"propertyName": "type",
			"mapping":      referenceDiscriminator,
		},
	}))
	setMappingValue(schemas, "api.RateLimitedProblemResponse", node(problemSchema(
		problem.RateLimited.Type, problem.RateLimited.Status, problem.RateLimited.Extensions,
	)))
	setMappingValue(schemas, "api.RepositoryConflictProblemResponse", node(problemSchema(
		problem.RepositoryConflict.Type, problem.RepositoryConflict.Status, problem.RepositoryConflict.Extensions,
	)))
}

func problemSchema(problemType string, status int, extensions []problem.Extension) map[string]any {
	properties := map[string]any{
		"type":     map[string]any{"type": "string", "format": "uri", "const": problemType},
		"instance": map[string]any{"type": "string", "format": "uri", "pattern": `^urn:lumilio:problem:[0-9a-f]{32}$`},
	}
	if status == 0 {
		properties["status"] = map[string]any{"type": "integer", "minimum": 400, "maximum": 599}
	} else {
		properties["status"] = map[string]any{"type": "integer", "const": status}
	}
	required := []string{"type", "status", "instance"}
	addExtensions(properties, &required, extensions)
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"required":             required,
		"properties":           properties,
	}
}

func referenceSchema(problemType string, extensions []problem.Extension) map[string]any {
	properties := map[string]any{
		"type":      map[string]any{"type": "string", "format": "uri", "const": problemType},
		"instance":  map[string]any{"type": "string", "format": "uri", "pattern": `^urn:lumilio:problem:[0-9a-f]{32}$`},
		"retryable": map[string]any{"type": "boolean"},
	}
	required := []string{"type", "instance"}
	addExtensions(properties, &required, extensions)
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"required":             required,
		"properties":           properties,
	}
}

func addExtensions(properties map[string]any, required *[]string, extensions []problem.Extension) {
	for _, extension := range extensions {
		switch extension.Schema {
		case "integer":
			properties[extension.Name] = map[string]any{"type": "integer", "minimum": 1}
			*required = append(*required, extension.Name)
		case "array[string]":
			properties[extension.Name] = map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
		default:
			properties[extension.Name] = map[string]any{"type": "string"}
			if extension.Name == "conflict_type" {
				*required = append(*required, extension.Name)
			}
		}
	}
	sort.Strings(*required)
}

func schemaName(problemType string) string {
	path := strings.TrimPrefix(problemType, problem.Namespace)
	var result strings.Builder
	upper := true
	for _, char := range path {
		if char == '/' || char == '-' {
			upper = true
			continue
		}
		if upper {
			char = unicode.ToUpper(char)
			upper = false
		}
		result.WriteRune(char)
	}
	return result.String()
}

func node(value any) *yaml.Node {
	var encoded yaml.Node
	if err := encoded.Encode(value); err != nil {
		panic(err)
	}
	return &encoded
}

func mappingValue(mapping *yaml.Node, key string) *yaml.Node {
	value := mappingValueOrNil(mapping, key)
	if value == nil {
		panic("missing OpenAPI mapping key: " + key)
	}
	return value
}

func mappingValueOrNil(mapping *yaml.Node, key string) *yaml.Node {
	for index := 0; index+1 < len(mapping.Content); index += 2 {
		if mapping.Content[index].Value == key {
			return mapping.Content[index+1]
		}
	}
	return nil
}

func setMappingValue(mapping *yaml.Node, key string, value *yaml.Node) {
	for index := 0; index+1 < len(mapping.Content); index += 2 {
		if mapping.Content[index].Value == key {
			mapping.Content[index+1] = value
			return
		}
	}
	mapping.Content = append(mapping.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key}, value)
}

func deleteMappingValue(mapping *yaml.Node, key string) {
	for index := 0; index+1 < len(mapping.Content); index += 2 {
		if mapping.Content[index].Value == key {
			mapping.Content = append(mapping.Content[:index], mapping.Content[index+2:]...)
			return
		}
	}
}

func isHTTPMethod(value string) bool {
	switch value {
	case "get", "put", "post", "delete", "options", "head", "patch", "trace":
		return true
	default:
		return false
	}
}
