version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    volumes:
      - photo-storage:/app/data/photos
    environment:
      - STORAGE_PATH=/app/data/photos
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=dev
      - DB_PASSWORD=Kr.lm<7knzb.;3^o
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - app

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=Kr.lm<7knzb.;3^o
      - POSTGRES_DB=lumina-photos
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  photo-storage:
    driver: local
  postgres-data:
    driver: local