version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - photo-storage:/app/data/photos
    environment:
      - STORAGE_PATH=/app/data/photos

volumes:
  photo-storage:
    driver: local