name: lumilio-photos-dev-http

services:
    lumilio:
        build:
            context: .
            dockerfile: server/Dockerfile
            secrets:
                - npmrc
        volumes:
            - ${LUMILIO_STORAGE:-./.cache/docker/storage}:/data/storage
            - ${LUMILIO_STATE:-./.cache/docker/state}:/data/app-state
        command: ["server", "--config", "/app/config/server.dev.toml"]
        ports:
            - "${WEB_HTTP_PORT:-6657}:6680"
        healthcheck:
            test: ["CMD", "server", "config", "healthcheck", "--config", "/app/config/server.dev.toml"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s

secrets:
    npmrc:
        file: ${LUMILIO_NPMRC:-${HOME}/.npmrc}
