services:
    db:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=lumiliophotos
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
# docker run -d --name db -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=lumiliophotos -p 5432:5432 -v postgres_data:/var/lib/postgresql/data postgres:15-alpine
# container run -d --name db -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=lumiliophotos -p 5432:5432 -v postgres_data:/var/lib/postgresql/data postgres:15-alpine
