package config

import (
	"fmt"
	"os"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

// DesktopParams contains the host-specific inputs needed to run the shared
// server runtime from the desktop supervisor.
type DesktopParams struct {
	Port        string
	WebRoot     string // empty = API only
	LogDir      string
	StoragePath string
	// DBHost is what the server dials to reach the private PostgreSQL: a Unix
	// socket directory on unix hosts, or 127.0.0.1 on Windows (whose
	// PostgreSQL builds have no Unix sockets).
	DBHost        string
	PGPort        string
	DBUser        string
	DBName        string
	PasswordFile  string
	SecretKeyPath string
	ExifToolPath  string // empty = resolve via PATH
	FFmpegPath    string
	FFprobePath   string
	// LumenStaticNodes pins Lumen node gRPC endpoints ("host:port") in addition
	// to mDNS discovery. The desktop host always pins the supervised local hub
	// endpoint: the SDK treats static entries as address facts, not liveness
	// claims, so the entry is harmless while the hub is not installed/running
	// and connects as soon as it comes up (no server restart needed).
	LumenStaticNodes []string
}

// NewDesktopConfig builds the server runtime config for the desktop host. It
// intentionally does not apply generic SERVER_*/DB_* environment overrides:
// desktop-specific environment handling belongs in the supervisor before this
// typed config is constructed.
func NewDesktopConfig(p DesktopParams) (AppConfig, error) {
	if err := validateDesktopParams(p); err != nil {
		return AppConfig{}, err
	}

	cfg := defaultAppConfigForEnvironment("production")
	cfg.Environment = "production"
	cfg.ServerConfig = ServerConfig{
		Port:     strings.TrimSpace(p.Port),
		LogLevel: "info",
		CORSAllowedOrigins: []string{
			"http://localhost:6657",
		},
		WebRoot: strings.TrimSpace(p.WebRoot),
	}
	cfg.LoggingConfig.Level = "info"
	cfg.LoggingConfig.LogDir = strings.TrimSpace(p.LogDir)
	cfg.LoggingConfig.ConsoleFormat = "console"
	cfg.LoggingConfig.FileFormat = "json"
	cfg.DatabaseConfig = DatabaseConfig{
		Host:         strings.TrimSpace(p.DBHost),
		Port:         strings.TrimSpace(p.PGPort),
		User:         strings.TrimSpace(p.DBUser),
		PasswordFile: strings.TrimSpace(p.PasswordFile),
		DBName:       strings.TrimSpace(p.DBName),
		SSL:          "disable",
	}
	cfg.StorageConfig.Path = strings.TrimSpace(p.StoragePath)
	cfg.Auth.SecretKeyPath = strings.TrimSpace(p.SecretKeyPath)
	cfg.Auth.WebAuthnRPID = "localhost"
	cfg.Auth.WebAuthnRPOrigins = []string{"http://localhost:" + cfg.ServerConfig.Port}
	cfg.Lumen.DiscoveryEnabled = true
	cfg.Lumen.DiscoveryMDNSEnabled = true
	cfg.Lumen.DiscoveryHubURL = ""
	cfg.Lumen.DiscoveryStaticNodes = p.LumenStaticNodes
	cfg.Tools = ToolsConfig{
		ExifToolPath: strings.TrimSpace(p.ExifToolPath),
		FFmpegPath:   strings.TrimSpace(p.FFmpegPath),
		FFprobePath:  strings.TrimSpace(p.FFprobePath),
	}

	applyDBPasswordFile(&cfg)
	return cfg, nil
}

func validateDesktopParams(p DesktopParams) error {
	required := map[string]string{
		"port":            p.Port,
		"log_dir":         p.LogDir,
		"storage_path":    p.StoragePath,
		"db_host":         p.DBHost,
		"pg_port":         p.PGPort,
		"db_user":         p.DBUser,
		"db_name":         p.DBName,
		"password_file":   p.PasswordFile,
		"secret_key_path": p.SecretKeyPath,
	}
	for name, value := range required {
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("desktop config requires %s", name)
		}
	}
	return nil
}

// WriteGeneratedTOML writes a debug copy of an AppConfig. It is useful for
// inspecting desktop startup state, but hosts should pass AppConfig directly to
// app.Run rather than reloading this file. Raw database passwords are omitted.
func WriteGeneratedTOML(path string, cfg AppConfig) error {
	fileCfg := tomlConfigFromAppConfig(cfg)
	fileCfg.DatabaseConfig.Password = ""

	data, err := toml.Marshal(fileCfg)
	if err != nil {
		return fmt.Errorf("marshal generated config: %w", err)
	}
	header := []byte("# Generated by Lumilio Photos. Debug copy only; runtime uses typed config.\n")
	if err := os.WriteFile(path, append(header, data...), 0o600); err != nil {
		return fmt.Errorf("write generated config: %w", err)
	}
	return nil
}

func tomlConfigFromAppConfig(cfg AppConfig) tomlConfig {
	return tomlConfig{
		Environment:    cfg.Environment,
		DatabaseConfig: cfg.DatabaseConfig,
		ServerConfig:   cfg.ServerConfig,
		LoggingConfig:  cfg.LoggingConfig,
		StorageConfig:  cfg.StorageConfig,
		RepositoryScan: cfg.RepositoryScan,
		Geocoding:      cfg.Geocoding,
		Auth:           cfg.Auth,
		Transcode:      cfg.Transcode,
		Lumen:          cfg.Lumen,
		Tools:          cfg.Tools,
	}
}
