package config

import (
	"fmt"
	"strings"
)

// SchemaFile is the generated schema's path relative to this package.
const SchemaFile = "schema/lumilio-server.schema.json"

// GenerateManifest returns a complete schema-v3 manifest for one explicit
// operator profile, validated through the same resolver used at runtime.
//
// The output carries the generated per-key documentation, so a manifest an
// operator receives from `server config init` reads the same as the checked-in
// example for that profile.
func GenerateManifest(name ProfileName, inputs ProfileInputs) ([]byte, error) {
	profile, ok := ProfileByName(name)
	if !ok {
		return nil, fmt.Errorf(
			"unsupported config init profile %q (want one of %s)",
			name, strings.Join(ProfileNames(true), ", "),
		)
	}
	if !profile.Operator {
		return nil, fmt.Errorf(
			"profile %q documents a shape generated by Desktop or the dev toolchain, "+
				"not one config init produces (want one of %s)",
			name, strings.Join(ProfileNames(true), ", "),
		)
	}
	if err := validateOperatorInputs(name, inputs); err != nil {
		return nil, err
	}
	// Operator manifests land at a path we do not control, so the schema is
	// referenced by its published URL rather than a relative path.
	return EncodeProfile(profile, inputs, SchemaID)
}

// RenderExamples renders every profile as a checked-in example manifest, keyed
// by its path under the examples directory.
func RenderExamples() (map[string][]byte, error) {
	rendered := make(map[string][]byte, len(profileTable))
	for _, profile := range profileTable {
		data, err := EncodeProfile(profile, ProfileInputs{}, exampleSchemaRef(profile.Path))
		if err != nil {
			return nil, err
		}
		rendered[profile.Path] = data
	}
	return rendered, nil
}

// exampleSchemaRef points an example at the checked-in schema with a relative
// path, so editors resolve it without network access.
func exampleSchemaRef(examplePath string) string {
	depth := strings.Count(examplePath, "/")
	return strings.Repeat("../", depth+1) + SchemaFile
}
