export {
  LEGACY_THEME_STORAGE_KEY,
  SETTINGS_STORAGE_KEY,
  LEGACY_SETTINGS_STORAGE_KEY,
  SETTINGS_STORAGE_VERSION,
  SETTINGS_REGISTRY,
  LOCAL_STORAGE_REGISTRY,
  THEME_STORAGE_KEY,
} from "@/lib/settings/registry";
