// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_facets.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentFacetCameraCounts = `-- name: AgentFacetCameraCounts :many
SELECT
    (a.specific_metadata ->> 'camera_model')::text AS name,
    COUNT(*) AS count
FROM assets a
WHERE a.asset_id = ANY($1::uuid[])
  AND a.is_deleted = false
  AND a.specific_metadata ->> 'camera_model' IS NOT NULL
  AND a.specific_metadata ->> 'camera_model' <> ''
GROUP BY 1
ORDER BY count DESC
LIMIT $2
`

type AgentFacetCameraCountsParams struct {
	AssetIds []pgtype.UUID `db:"asset_ids" json:"asset_ids"`
	TopN     int32         `db:"top_n" json:"top_n"`
}

type AgentFacetCameraCountsRow struct {
	Name  string `db:"name" json:"name"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) AgentFacetCameraCounts(ctx context.Context, arg AgentFacetCameraCountsParams) ([]AgentFacetCameraCountsRow, error) {
	rows, err := q.db.Query(ctx, agentFacetCameraCounts, arg.AssetIds, arg.TopN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFacetCameraCountsRow
	for rows.Next() {
		var i AgentFacetCameraCountsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentFacetOverview = `-- name: AgentFacetOverview :one

SELECT
    COUNT(*) AS total,
    MIN(COALESCE(a.taken_time, a.upload_time))::timestamptz AS date_from,
    MAX(COALESCE(a.taken_time, a.upload_time))::timestamptz AS date_to,
    COUNT(*) FILTER (WHERE a.liked = true) AS liked_count,
    MIN(a.capture_offset_minutes)::smallint AS capture_offset_minutes
FROM assets a
WHERE a.asset_id = ANY($1::uuid[])
  AND a.is_deleted = false
`

type AgentFacetOverviewRow struct {
	Total                int64              `db:"total" json:"total"`
	DateFrom             pgtype.Timestamptz `db:"date_from" json:"date_from"`
	DateTo               pgtype.Timestamptz `db:"date_to" json:"date_to"`
	LikedCount           int64              `db:"liked_count" json:"liked_count"`
	CaptureOffsetMinutes int16              `db:"capture_offset_minutes" json:"capture_offset_minutes"`
}

// Facet aggregates over a ref snapshot (agent describe tool / hydration API).
// Every query takes the materialized asset id array; results feed
// ref.FacetSummary. User-content strings (labels, names, camera models) are
// sanitized in Go before reaching the LLM — never here.
func (q *Queries) AgentFacetOverview(ctx context.Context, assetIds []pgtype.UUID) (AgentFacetOverviewRow, error) {
	row := q.db.QueryRow(ctx, agentFacetOverview, assetIds)
	var i AgentFacetOverviewRow
	err := row.Scan(
		&i.Total,
		&i.DateFrom,
		&i.DateTo,
		&i.LikedCount,
		&i.CaptureOffsetMinutes,
	)
	return i, err
}

const agentFacetQualityStats = `-- name: AgentFacetQualityStats :one
SELECT
    COUNT(*) AS scored_count,
    COALESCE(percentile_cont(0.25) WITHIN GROUP (ORDER BY score), 0)::real AS p25,
    COALESCE(percentile_cont(0.50) WITHIN GROUP (ORDER BY score), 0)::real AS p50,
    COALESCE(percentile_cont(0.75) WITHIN GROUP (ORDER BY score), 0)::real AS p75,
    COALESCE(percentile_cont(0.90) WITHIN GROUP (ORDER BY score), 0)::real AS p90
FROM asset_quality_scores
WHERE asset_id = ANY($1::uuid[])
`

type AgentFacetQualityStatsRow struct {
	ScoredCount int64   `db:"scored_count" json:"scored_count"`
	P25         float32 `db:"p25" json:"p25"`
	P50         float32 `db:"p50" json:"p50"`
	P75         float32 `db:"p75" json:"p75"`
	P90         float32 `db:"p90" json:"p90"`
}

// Aesthetic-score distribution (percentiles) over a ref snapshot, for the
// describe tool. Unscored assets are excluded from the percentiles;
// scored_count lets callers report how many of the ref's assets carry a score.
// Percentiles are NULL when nothing in the set is scored.
func (q *Queries) AgentFacetQualityStats(ctx context.Context, assetIds []pgtype.UUID) (AgentFacetQualityStatsRow, error) {
	row := q.db.QueryRow(ctx, agentFacetQualityStats, assetIds)
	var i AgentFacetQualityStatsRow
	err := row.Scan(
		&i.ScoredCount,
		&i.P25,
		&i.P50,
		&i.P75,
		&i.P90,
	)
	return i, err
}

const agentFacetRatingDist = `-- name: AgentFacetRatingDist :many
SELECT COALESCE(a.rating, 0) AS rating, COUNT(*) AS count
FROM assets a
WHERE a.asset_id = ANY($1::uuid[])
  AND a.is_deleted = false
GROUP BY 1
ORDER BY 1
`

type AgentFacetRatingDistRow struct {
	Rating int32 `db:"rating" json:"rating"`
	Count  int64 `db:"count" json:"count"`
}

func (q *Queries) AgentFacetRatingDist(ctx context.Context, assetIds []pgtype.UUID) ([]AgentFacetRatingDistRow, error) {
	rows, err := q.db.Query(ctx, agentFacetRatingDist, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFacetRatingDistRow
	for rows.Next() {
		var i AgentFacetRatingDistRow
		if err := rows.Scan(&i.Rating, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentFacetTimeHistogram = `-- name: AgentFacetTimeHistogram :many
SELECT
    to_char(
        date_trunc($1::text, COALESCE(a.taken_time, a.upload_time)),
        CASE
            WHEN $1::text = 'hour' THEN 'YYYY-MM-DD HH24:00'
            WHEN $1::text = 'day' THEN 'YYYY-MM-DD'
            WHEN $1::text = 'year' THEN 'YYYY'
            ELSE 'YYYY-MM'
        END
    ) AS bucket,
    COUNT(*) AS count
FROM assets a
WHERE a.asset_id = ANY($2::uuid[])
  AND a.is_deleted = false
GROUP BY 1
ORDER BY 1
`

type AgentFacetTimeHistogramParams struct {
	Granularity string        `db:"granularity" json:"granularity"`
	AssetIds    []pgtype.UUID `db:"asset_ids" json:"asset_ids"`
}

type AgentFacetTimeHistogramRow struct {
	Bucket string `db:"bucket" json:"bucket"`
	Count  int64  `db:"count" json:"count"`
}

// granularity is 'hour', 'day', 'month' or 'year'.
func (q *Queries) AgentFacetTimeHistogram(ctx context.Context, arg AgentFacetTimeHistogramParams) ([]AgentFacetTimeHistogramRow, error) {
	rows, err := q.db.Query(ctx, agentFacetTimeHistogram, arg.Granularity, arg.AssetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFacetTimeHistogramRow
	for rows.Next() {
		var i AgentFacetTimeHistogramRow
		if err := rows.Scan(&i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentFacetTopFocalLengths = `-- name: AgentFacetTopFocalLengths :many
SELECT t.name::text AS name, t.count AS count FROM (
    SELECT
        (round((a.specific_metadata ->> 'focal_length')::numeric)::text || 'mm') AS name,
        COUNT(*) AS count
    FROM assets a
    WHERE a.asset_id = ANY($1::uuid[])
      AND a.is_deleted = false
      AND a.specific_metadata ->> 'focal_length' ~ '^[0-9]+(\.[0-9]+)?$'
    GROUP BY 1
) t
WHERE t.name <> '0mm'
ORDER BY t.count DESC
LIMIT $2
`

type AgentFacetTopFocalLengthsParams struct {
	AssetIds []pgtype.UUID `db:"asset_ids" json:"asset_ids"`
	TopN     int32         `db:"top_n" json:"top_n"`
}

type AgentFacetTopFocalLengthsRow struct {
	Name  string `db:"name" json:"name"`
	Count int64  `db:"count" json:"count"`
}

// Most-used focal lengths over a ref snapshot, rounded to whole millimetres so
// 34.9mm and 35mm collapse into one bucket. The regex guards the numeric cast.
func (q *Queries) AgentFacetTopFocalLengths(ctx context.Context, arg AgentFacetTopFocalLengthsParams) ([]AgentFacetTopFocalLengthsRow, error) {
	rows, err := q.db.Query(ctx, agentFacetTopFocalLengths, arg.AssetIds, arg.TopN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFacetTopFocalLengthsRow
	for rows.Next() {
		var i AgentFacetTopFocalLengthsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentFacetTopLenses = `-- name: AgentFacetTopLenses :many
SELECT
    (a.specific_metadata ->> 'lens_model')::text AS name,
    COUNT(*) AS count
FROM assets a
WHERE a.asset_id = ANY($1::uuid[])
  AND a.is_deleted = false
  AND a.specific_metadata ->> 'lens_model' IS NOT NULL
  AND a.specific_metadata ->> 'lens_model' <> ''
GROUP BY 1
ORDER BY count DESC
LIMIT $2
`

type AgentFacetTopLensesParams struct {
	AssetIds []pgtype.UUID `db:"asset_ids" json:"asset_ids"`
	TopN     int32         `db:"top_n" json:"top_n"`
}

type AgentFacetTopLensesRow struct {
	Name  string `db:"name" json:"name"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) AgentFacetTopLenses(ctx context.Context, arg AgentFacetTopLensesParams) ([]AgentFacetTopLensesRow, error) {
	rows, err := q.db.Query(ctx, agentFacetTopLenses, arg.AssetIds, arg.TopN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFacetTopLensesRow
	for rows.Next() {
		var i AgentFacetTopLensesRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentFacetTopPeople = `-- name: AgentFacetTopPeople :many
SELECT
    fc.cluster_name::text AS name,
    COUNT(DISTINCT fi.asset_id) AS count
FROM face_items fi
JOIN face_cluster_members fcm ON fcm.face_id = fi.id
JOIN face_clusters fc ON fc.cluster_id = fcm.cluster_id
WHERE fi.asset_id = ANY($1::uuid[])
  AND fc.cluster_name IS NOT NULL
  AND fc.cluster_name <> ''
GROUP BY 1
ORDER BY count DESC
LIMIT $2
`

type AgentFacetTopPeopleParams struct {
	AssetIds []pgtype.UUID `db:"asset_ids" json:"asset_ids"`
	TopN     int32         `db:"top_n" json:"top_n"`
}

type AgentFacetTopPeopleRow struct {
	Name  string `db:"name" json:"name"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) AgentFacetTopPeople(ctx context.Context, arg AgentFacetTopPeopleParams) ([]AgentFacetTopPeopleRow, error) {
	rows, err := q.db.Query(ctx, agentFacetTopPeople, arg.AssetIds, arg.TopN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFacetTopPeopleRow
	for rows.Next() {
		var i AgentFacetTopPeopleRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentFacetTopPlaces = `-- name: AgentFacetTopPlaces :many
SELECT
    COALESCE(lc.label, lc.city, lc.region, lc.country)::text AS name,
    COUNT(DISTINCT lca.asset_id) AS count
FROM location_cluster_assets lca
JOIN location_clusters lc ON lc.cluster_id = lca.cluster_id
WHERE lca.asset_id = ANY($1::uuid[])
  AND COALESCE(lc.label, lc.city, lc.region, lc.country) IS NOT NULL
GROUP BY 1
ORDER BY count DESC
LIMIT $2
`

type AgentFacetTopPlacesParams struct {
	AssetIds []pgtype.UUID `db:"asset_ids" json:"asset_ids"`
	TopN     int32         `db:"top_n" json:"top_n"`
}

type AgentFacetTopPlacesRow struct {
	Name  string `db:"name" json:"name"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) AgentFacetTopPlaces(ctx context.Context, arg AgentFacetTopPlacesParams) ([]AgentFacetTopPlacesRow, error) {
	rows, err := q.db.Query(ctx, agentFacetTopPlaces, arg.AssetIds, arg.TopN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFacetTopPlacesRow
	for rows.Next() {
		var i AgentFacetTopPlacesRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentFacetTypeCounts = `-- name: AgentFacetTypeCounts :many
SELECT a.type, COUNT(*) AS count
FROM assets a
WHERE a.asset_id = ANY($1::uuid[])
  AND a.is_deleted = false
GROUP BY a.type
`

type AgentFacetTypeCountsRow struct {
	Type  string `db:"type" json:"type"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) AgentFacetTypeCounts(ctx context.Context, assetIds []pgtype.UUID) ([]AgentFacetTypeCountsRow, error) {
	rows, err := q.db.Query(ctx, agentFacetTypeCounts, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFacetTypeCountsRow
	for rows.Next() {
		var i AgentFacetTypeCountsRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
