// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_facet_08.sql

package repo

import (
	"context"
	"strings"

	"github.com/google/uuid"
)

const agentFacetRatingDist = `-- name: AgentFacetRatingDist :many
SELECT COALESCE(a.rating, 0) AS rating, COUNT(*) AS count
FROM assets a
WHERE a.asset_id IN (/*SLICE:asset_ids*/?)
  AND a.is_deleted = false
GROUP BY 1
ORDER BY 1
`

type AgentFacetRatingDistRow struct {
	Rating int64 `db:"rating" json:"rating"`
	Count  int64 `db:"count" json:"count"`
}

func (q *Queries) AgentFacetRatingDist(ctx context.Context, assetIds []uuid.UUID) ([]AgentFacetRatingDistRow, error) {
	query := agentFacetRatingDist
	var queryParams []interface{}
	if len(assetIds) > 0 {
		for _, v := range assetIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", strings.Repeat(",?", len(assetIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFacetRatingDistRow
	for rows.Next() {
		var i AgentFacetRatingDistRow
		if err := rows.Scan(&i.Rating, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
