// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_facet_06.sql

package repo

import (
	"context"
	"strings"

	"github.com/google/uuid"
)

const agentFacetTopFocalLengths = `-- name: AgentFacetTopFocalLengths :many
SELECT t.name AS name, t.count AS count FROM (
    SELECT
        (round(json_extract(a.specific_metadata, char(36) || '.focal_length')) || 'mm') AS name,
        COUNT(*) AS count
    FROM assets a
    WHERE a.asset_id IN (/*SLICE:asset_ids*/?)
      AND a.is_deleted = false
      AND json_type(a.specific_metadata, char(36) || '.focal_length') IN ('integer', 'real')
    GROUP BY 1
) t
WHERE t.name <> '0mm'
ORDER BY t.count DESC
LIMIT ?2
`

type AgentFacetTopFocalLengthsParams struct {
	AssetIds []uuid.UUID `db:"asset_ids" json:"asset_ids"`
	TopN     int64       `db:"top_n" json:"top_n"`
}

type AgentFacetTopFocalLengthsRow struct {
	Name  interface{} `db:"name" json:"name"`
	Count int64       `db:"count" json:"count"`
}

// Most-used focal lengths over a ref snapshot, rounded to whole millimetres so
// 34.9mm and 35mm collapse into one bucket. JSON type checks guard the value.
func (q *Queries) AgentFacetTopFocalLengths(ctx context.Context, arg AgentFacetTopFocalLengthsParams) ([]AgentFacetTopFocalLengthsRow, error) {
	query := agentFacetTopFocalLengths
	var queryParams []interface{}
	if len(arg.AssetIds) > 0 {
		for _, v := range arg.AssetIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", strings.Repeat(",?", len(arg.AssetIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.TopN)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFacetTopFocalLengthsRow
	for rows.Next() {
		var i AgentFacetTopFocalLengthsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
