// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_tools.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentLookupPeople = `-- name: AgentLookupPeople :many
SELECT
    fc.cluster_id,
    fc.cluster_name::text AS name,
    COUNT(DISTINCT fi.asset_id) AS asset_count
FROM face_clusters fc
JOIN face_cluster_members fcm ON fcm.cluster_id = fc.cluster_id
JOIN face_items fi ON fi.id = fcm.face_id
WHERE fc.cluster_name IS NOT NULL
  AND fc.cluster_name <> ''
  AND ($1::text IS NULL OR fc.cluster_name ILIKE '%' || $1 || '%')
GROUP BY fc.cluster_id, fc.cluster_name
ORDER BY asset_count DESC
LIMIT $2
`

type AgentLookupPeopleParams struct {
	NameQuery *string `db:"name_query" json:"name_query"`
	Limit     int32   `db:"limit" json:"limit"`
}

type AgentLookupPeopleRow struct {
	ClusterID  int32  `db:"cluster_id" json:"cluster_id"`
	Name       string `db:"name" json:"name"`
	AssetCount int64  `db:"asset_count" json:"asset_count"`
}

// lookup_people entity resolver: named face clusters matching a name query.
func (q *Queries) AgentLookupPeople(ctx context.Context, arg AgentLookupPeopleParams) ([]AgentLookupPeopleRow, error) {
	rows, err := q.db.Query(ctx, agentLookupPeople, arg.NameQuery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentLookupPeopleRow
	for rows.Next() {
		var i AgentLookupPeopleRow
		if err := rows.Scan(&i.ClusterID, &i.Name, &i.AssetCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentPeekAssets = `-- name: AgentPeekAssets :many
SELECT asset_id, original_filename, type,
       COALESCE(taken_time, upload_time)::timestamptz AS captured_at,
       rating, liked
FROM assets
WHERE asset_id = ANY($1::uuid[])
  AND is_deleted = false
`

type AgentPeekAssetsRow struct {
	AssetID          pgtype.UUID        `db:"asset_id" json:"asset_id"`
	OriginalFilename string             `db:"original_filename" json:"original_filename"`
	Type             string             `db:"type" json:"type"`
	CapturedAt       pgtype.Timestamptz `db:"captured_at" json:"captured_at"`
	Rating           *int32             `db:"rating" json:"rating"`
	Liked            *bool              `db:"liked" json:"liked"`
}

// peek observer: minimal per-asset fields; snapshot order restored in Go.
func (q *Queries) AgentPeekAssets(ctx context.Context, assetIds []pgtype.UUID) ([]AgentPeekAssetsRow, error) {
	rows, err := q.db.Query(ctx, agentPeekAssets, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentPeekAssetsRow
	for rows.Next() {
		var i AgentPeekAssetsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.OriginalFilename,
			&i.Type,
			&i.CapturedAt,
			&i.Rating,
			&i.Liked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetIDsByPersonIDs = `-- name: GetAssetIDsByPersonIDs :many

SELECT a.asset_id
FROM assets a
WHERE a.is_deleted = false
  AND EXISTS (
    SELECT 1
    FROM face_items fi
    JOIN face_cluster_members fcm ON fcm.face_id = fi.id
    WHERE fi.asset_id = a.asset_id
      AND fcm.cluster_id = ANY($1::int[])
  )
ORDER BY COALESCE(a.taken_time, a.upload_time) DESC, a.asset_id DESC
LIMIT $2
`

type GetAssetIDsByPersonIDsParams struct {
	PersonIds []int32 `db:"person_ids" json:"person_ids"`
	Limit     int32   `db:"limit" json:"limit"`
}

// Queries backing the Phase 2 agent tools (producers, transformers,
// observers). All ANY(asset_ids) queries operate on ref snapshots.
// search_people producer: assets containing at least one of the given people
// (union semantics; the agent intersects refs for "both people" requests).
func (q *Queries) GetAssetIDsByPersonIDs(ctx context.Context, arg GetAssetIDsByPersonIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getAssetIDsByPersonIDs, arg.PersonIds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var asset_id pgtype.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankAssetIDsByQuality = `-- name: RankAssetIDsByQuality :many
SELECT asset_id
FROM assets a
WHERE asset_id = ANY($1::uuid[])
  AND is_deleted = false
ORDER BY (
    0.45 * COALESCE(a.rating, 0)::float8 / 5.0
  + 0.20 * (CASE WHEN a.liked THEN 1.0 ELSE 0.0 END)
  + 0.35 * LEAST(COALESCE(a.width, 0)::float8 * COALESCE(a.height, 0)::float8 / 24000000.0, 1.0)
) ASC, asset_id ASC
`

// rank(by=quality) ascending, using the featured-selector heuristic
// (rating, liked, resolution); callers reverse for descending order.
func (q *Queries) RankAssetIDsByQuality(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, rankAssetIDsByQuality, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var asset_id pgtype.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankAssetIDsByTime = `-- name: RankAssetIDsByTime :many
SELECT asset_id
FROM assets
WHERE asset_id = ANY($1::uuid[])
  AND is_deleted = false
ORDER BY COALESCE(taken_time, upload_time) ASC, asset_id ASC
`

// rank(by=time) ascending; callers reverse for descending order.
func (q *Queries) RankAssetIDsByTime(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, rankAssetIDsByTime, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var asset_id pgtype.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankAssetIDsByUploadTime = `-- name: RankAssetIDsByUploadTime :many
SELECT asset_id
FROM assets
WHERE asset_id = ANY($1::uuid[])
  AND is_deleted = false
ORDER BY upload_time ASC, asset_id ASC
`

// "recently added" presentation order, ascending; callers reverse for newest first.
func (q *Queries) RankAssetIDsByUploadTime(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, rankAssetIDsByUploadTime, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var asset_id pgtype.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
