// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_tools.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"server/internal/db/dbtypes"
)

const agentAssetAestheticScores = `-- name: AgentAssetAestheticScores :many
SELECT asset_id, score
FROM asset_quality_scores
WHERE asset_id = ANY($1::uuid[])
`

type AgentAssetAestheticScoresRow struct {
	AssetID pgtype.UUID `db:"asset_id" json:"asset_id"`
	Score   float32     `db:"score" json:"score"`
}

// Per-asset SigLIP aesthetic scores for a ref snapshot. Unscored assets are
// omitted; callers that filter by quality percentile drop them.
func (q *Queries) AgentAssetAestheticScores(ctx context.Context, assetIds []pgtype.UUID) ([]AgentAssetAestheticScoresRow, error) {
	rows, err := q.db.Query(ctx, agentAssetAestheticScores, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentAssetAestheticScoresRow
	for rows.Next() {
		var i AgentAssetAestheticScoresRow
		if err := rows.Scan(&i.AssetID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentCapturedTimes = `-- name: AgentCapturedTimes :many
SELECT COALESCE(taken_time, upload_time)::timestamptz AS captured_at
FROM assets
WHERE asset_id = ANY($1::uuid[])
  AND is_deleted = false
`

// Capture times for a set of assets, for the sample tool's distribution
// summary. Order is irrelevant; bucketing happens in Go.
func (q *Queries) AgentCapturedTimes(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, agentCapturedTimes, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var captured_at pgtype.Timestamptz
		if err := rows.Scan(&captured_at); err != nil {
			return nil, err
		}
		items = append(items, captured_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentInspectAssets = `-- name: AgentInspectAssets :many
SELECT asset_id, type, specific_metadata
FROM assets
WHERE asset_id = ANY($1::uuid[])
  AND is_deleted = false
`

type AgentInspectAssetsRow struct {
	AssetID          pgtype.UUID              `db:"asset_id" json:"asset_id"`
	Type             string                   `db:"type" json:"type"`
	SpecificMetadata dbtypes.SpecificMetadata `db:"specific_metadata" json:"specific_metadata"`
}

// inspect observer: per-asset EXIF facets for small refs.
func (q *Queries) AgentInspectAssets(ctx context.Context, assetIds []pgtype.UUID) ([]AgentInspectAssetsRow, error) {
	rows, err := q.db.Query(ctx, agentInspectAssets, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInspectAssetsRow
	for rows.Next() {
		var i AgentInspectAssetsRow
		if err := rows.Scan(&i.AssetID, &i.Type, &i.SpecificMetadata); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentLookupAlbums = `-- name: AgentLookupAlbums :many
SELECT
    al.album_id,
    al.album_name::text AS title,
    COUNT(DISTINCT aa.asset_id) AS asset_count
FROM albums al
LEFT JOIN album_assets aa ON aa.album_id = al.album_id
LEFT JOIN assets a ON a.asset_id = aa.asset_id AND a.is_deleted = false
WHERE al.user_id = $1
  AND ($2::text IS NULL OR al.album_name ILIKE '%' || $2 || '%')
GROUP BY al.album_id, al.album_name
ORDER BY asset_count DESC
LIMIT $3
`

type AgentLookupAlbumsParams struct {
	UserID     int32   `db:"user_id" json:"user_id"`
	TitleQuery *string `db:"title_query" json:"title_query"`
	Limit      int32   `db:"limit" json:"limit"`
}

type AgentLookupAlbumsRow struct {
	AlbumID    int32  `db:"album_id" json:"album_id"`
	Title      string `db:"title" json:"title"`
	AssetCount int64  `db:"asset_count" json:"asset_count"`
}

// lookup_albums entity resolver: albums matching a title query.
func (q *Queries) AgentLookupAlbums(ctx context.Context, arg AgentLookupAlbumsParams) ([]AgentLookupAlbumsRow, error) {
	rows, err := q.db.Query(ctx, agentLookupAlbums, arg.UserID, arg.TitleQuery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentLookupAlbumsRow
	for rows.Next() {
		var i AgentLookupAlbumsRow
		if err := rows.Scan(&i.AlbumID, &i.Title, &i.AssetCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentLookupPeople = `-- name: AgentLookupPeople :many
SELECT
    fc.cluster_id,
    fc.cluster_name::text AS name,
    COUNT(DISTINCT fi.asset_id) AS asset_count
FROM face_clusters fc
JOIN face_cluster_members fcm ON fcm.cluster_id = fc.cluster_id
JOIN face_items fi ON fi.id = fcm.face_id
WHERE fc.cluster_name IS NOT NULL
  AND fc.cluster_name <> ''
  AND ($1::text IS NULL OR fc.cluster_name ILIKE '%' || $1 || '%')
GROUP BY fc.cluster_id, fc.cluster_name
ORDER BY asset_count DESC
LIMIT $2
`

type AgentLookupPeopleParams struct {
	NameQuery *string `db:"name_query" json:"name_query"`
	Limit     int32   `db:"limit" json:"limit"`
}

type AgentLookupPeopleRow struct {
	ClusterID  int32  `db:"cluster_id" json:"cluster_id"`
	Name       string `db:"name" json:"name"`
	AssetCount int64  `db:"asset_count" json:"asset_count"`
}

// lookup_people entity resolver: named face clusters matching a name query.
func (q *Queries) AgentLookupPeople(ctx context.Context, arg AgentLookupPeopleParams) ([]AgentLookupPeopleRow, error) {
	rows, err := q.db.Query(ctx, agentLookupPeople, arg.NameQuery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentLookupPeopleRow
	for rows.Next() {
		var i AgentLookupPeopleRow
		if err := rows.Scan(&i.ClusterID, &i.Name, &i.AssetCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentPeekAssets = `-- name: AgentPeekAssets :many
SELECT
    a.asset_id,
    a.original_filename,
    a.type,
    COALESCE(a.taken_time, a.upload_time)::timestamptz AS captured_at,
    a.rating,
    a.liked,
    COALESCE((
        SELECT COALESCE(lc.label, lc.city, lc.region, lc.country)
        FROM location_cluster_assets lca
        JOIN location_clusters lc ON lc.cluster_id = lca.cluster_id
        WHERE lca.asset_id = a.asset_id
          AND COALESCE(lc.label, lc.city, lc.region, lc.country) IS NOT NULL
        LIMIT 1
    ), '')::text AS place,
    (
        SELECT array_agg(DISTINCT fc.cluster_name)
        FROM face_items fi
        JOIN face_cluster_members fcm ON fcm.face_id = fi.id
        JOIN face_clusters fc ON fc.cluster_id = fcm.cluster_id
        WHERE fi.asset_id = a.asset_id
          AND fc.cluster_name IS NOT NULL
          AND fc.cluster_name <> ''
    )::text[] AS people
FROM assets a
WHERE a.asset_id = ANY($1::uuid[])
  AND a.is_deleted = false
`

type AgentPeekAssetsRow struct {
	AssetID          pgtype.UUID        `db:"asset_id" json:"asset_id"`
	OriginalFilename string             `db:"original_filename" json:"original_filename"`
	Type             string             `db:"type" json:"type"`
	CapturedAt       pgtype.Timestamptz `db:"captured_at" json:"captured_at"`
	Rating           *int32             `db:"rating" json:"rating"`
	Liked            *bool              `db:"liked" json:"liked"`
	Place            string             `db:"place" json:"place"`
	People           []string           `db:"people" json:"people"`
}

// peek observer: minimal per-asset fields plus place + people; snapshot order
// restored in Go. place/people are correlated subqueries so each asset stays a
// single row (no fan-out from the cluster joins).
func (q *Queries) AgentPeekAssets(ctx context.Context, assetIds []pgtype.UUID) ([]AgentPeekAssetsRow, error) {
	rows, err := q.db.Query(ctx, agentPeekAssets, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentPeekAssetsRow
	for rows.Next() {
		var i AgentPeekAssetsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.OriginalFilename,
			&i.Type,
			&i.CapturedAt,
			&i.Rating,
			&i.Liked,
			&i.Place,
			&i.People,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetIDsByPersonIDs = `-- name: GetAssetIDsByPersonIDs :many

SELECT a.asset_id
FROM assets a
WHERE a.is_deleted = false
  AND EXISTS (
    SELECT 1
    FROM face_items fi
    JOIN face_cluster_members fcm ON fcm.face_id = fi.id
    WHERE fi.asset_id = a.asset_id
      AND fcm.cluster_id = ANY($1::int[])
  )
ORDER BY COALESCE(a.taken_time, a.upload_time) DESC, a.asset_id DESC
LIMIT $2
`

type GetAssetIDsByPersonIDsParams struct {
	PersonIds []int32 `db:"person_ids" json:"person_ids"`
	Limit     int32   `db:"limit" json:"limit"`
}

// Queries backing the Phase 2 agent tools (producers, transformers,
// observers). All ANY(asset_ids) queries operate on ref snapshots.
// search_people producer: assets containing at least one of the given people
// (union semantics; the agent intersects refs for "both people" requests).
func (q *Queries) GetAssetIDsByPersonIDs(ctx context.Context, arg GetAssetIDsByPersonIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getAssetIDsByPersonIDs, arg.PersonIds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var asset_id pgtype.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankAssetIDsByQuality = `-- name: RankAssetIDsByQuality :many
SELECT a.asset_id
FROM assets a
LEFT JOIN asset_quality_scores aqs ON aqs.asset_id = a.asset_id
WHERE a.asset_id = ANY($1::uuid[])
  AND a.is_deleted = false
ORDER BY COALESCE(
    aqs.score,
    1.0 + 0.45 * COALESCE(a.rating, 0)::float8 / 5.0
        + 0.20 * (CASE WHEN a.liked THEN 1.0 ELSE 0.0 END)
        + 0.35 * LEAST(COALESCE(a.width, 0)::float8 * COALESCE(a.height, 0)::float8 / 24000000.0, 1.0)
) ASC, a.asset_id ASC
`

// rank(by=quality) ascending, using the aesthetic score from the SigLIP MLP
// head when available, falling back to the legacy heuristic (rating, liked,
// resolution) for unscored assets. Callers reverse for descending order.
func (q *Queries) RankAssetIDsByQuality(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, rankAssetIDsByQuality, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var asset_id pgtype.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankAssetIDsByTime = `-- name: RankAssetIDsByTime :many
SELECT asset_id
FROM assets
WHERE asset_id = ANY($1::uuid[])
  AND is_deleted = false
ORDER BY COALESCE(taken_time, upload_time) ASC, asset_id ASC
`

// rank(by=time) ascending; callers reverse for descending order.
func (q *Queries) RankAssetIDsByTime(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, rankAssetIDsByTime, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var asset_id pgtype.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankAssetIDsByUploadTime = `-- name: RankAssetIDsByUploadTime :many
SELECT asset_id
FROM assets
WHERE asset_id = ANY($1::uuid[])
  AND is_deleted = false
ORDER BY upload_time ASC, asset_id ASC
`

// "recently added" presentation order, ascending; callers reverse for newest first.
func (q *Queries) RankAssetIDsByUploadTime(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, rankAssetIDsByUploadTime, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var asset_id pgtype.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
