// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: assets_02.sql

package repo

import (
	"context"
)

const getAssetsUnified = `-- name: GetAssetsUnified :many
WITH filter_params AS (
  SELECT
    CAST(?1 AS TEXT) AS asset_ids_json,
    CAST(?2 AS TEXT) AS asset_types_json,
    CAST(?3 AS TEXT) AS tag_names_json
),
page_ids AS (
  SELECT
    a.asset_id,
    CASE
      WHEN ?4 = 'recently_added' THEN a.upload_time
      ELSE COALESCE(a.taken_time, a.upload_time)
    END AS sort_time
  FROM assets a
  WHERE a.is_deleted = COALESCE(?5, false)
    AND (
      (SELECT asset_ids_json FROM filter_params) IS NULL
      OR a.asset_id IN (SELECT value FROM json_each((SELECT asset_ids_json FROM filter_params)))
    )
    AND (?6 IS NULL OR a.original_filename LIKE '%' || ?6 || '%')
    AND (?7 IS NULL OR a.type = ?7)
    AND (
      (SELECT asset_types_json FROM filter_params) IS NULL
      OR a.type IN (SELECT value FROM json_each((SELECT asset_types_json FROM filter_params)))
    )
    AND (?8 IS NULL OR a.owner_id = ?8)
    AND (?9 IS NULL OR a.repository_id = ?9)
    AND (
      ?10 IS NULL
      OR (
        CASE
          WHEN ?10 = '' THEN
            CASE WHEN COALESCE(?11, true) THEN true
              ELSE instr(a.storage_path, '/') = 0
            END
          ELSE
            CASE WHEN COALESCE(?11, true) THEN
              a.storage_path LIKE ?10 || '/%'
            ELSE
              a.storage_path LIKE ?10 || '/%'
              AND a.storage_path NOT LIKE ?10 || '/%/%'
            END
        END
      )
    )
    AND (
      ?12 IS NULL
      OR EXISTS (
        SELECT 1
        FROM face_cluster_members fcm
        JOIN face_items fi_person ON fi_person.id = fcm.face_id
        WHERE fcm.cluster_id = ?12
          AND fi_person.asset_id = a.asset_id
      )
    )
    AND (
      ?13 IS NULL
      OR EXISTS (
        SELECT 1
        FROM album_assets aa
        WHERE aa.asset_id = a.asset_id
          AND aa.album_id = ?13
      )
    )
    AND (
      ?14 IS NULL
      OR EXISTS (
        SELECT 1
        FROM asset_tags at
        JOIN tags t ON t.tag_id = at.tag_id
        WHERE at.asset_id = a.asset_id
          AND t.tag_name = ?14
          AND (?15 IS NULL OR at.source = ?15)
      )
    )
    AND (
      (SELECT tag_names_json FROM filter_params) IS NULL
      OR (
        SELECT COUNT(DISTINCT t2.tag_name)
        FROM asset_tags at2
        JOIN tags t2 ON t2.tag_id = at2.tag_id
        WHERE at2.asset_id = a.asset_id
          AND t2.tag_name IN (SELECT value FROM json_each((SELECT tag_names_json FROM filter_params)))
      ) = json_array_length((SELECT tag_names_json FROM filter_params))
    )
    AND (?16 IS NULL OR
      CASE COALESCE(?17, 'contains')
        WHEN 'matches' THEN a.original_filename LIKE ?16
        WHEN 'starts_with' THEN a.original_filename LIKE ?16 || '%'
        WHEN 'ends_with' THEN a.original_filename LIKE '%' || ?16
        ELSE a.original_filename LIKE '%' || ?16 || '%'
      END
    )
    AND (?18 IS NULL OR COALESCE(a.taken_time, a.upload_time) >= ?18)
    AND (?19 IS NULL OR COALESCE(a.taken_time, a.upload_time) <= ?19)
    AND (?20 IS NULL OR
      CASE
        WHEN ?20 = true THEN json_extract(a.specific_metadata, char(36) || '.is_raw') = 1
        ELSE json_extract(a.specific_metadata, char(36) || '.is_raw') = 0 OR json_extract(a.specific_metadata, char(36) || '.is_raw') IS NULL
      END
    )
    AND (?21 IS NULL OR
      CASE
        WHEN ?21 = 0 THEN a.rating IS NULL OR a.rating = 0
        ELSE a.rating = ?21
      END
    )
    AND (?22 IS NULL OR
      CASE
        WHEN ?22 = false THEN a.liked IS NULL OR a.liked = false
        ELSE a.liked = true
      END
    )
    AND (?23 IS NULL OR json_extract(a.specific_metadata, char(36) || '.camera_model') = ?23)
    AND (?24 IS NULL OR json_extract(a.specific_metadata, char(36) || '.lens_model') = ?24)
    AND (
      ?25 IS NULL
      OR ?26 IS NULL
      OR ?27 IS NULL
      OR ?28 IS NULL
      OR (
        a.gps_latitude IS NOT NULL
        AND a.gps_longitude IS NOT NULL
        AND a.gps_latitude
          BETWEEN min(?26, ?25)
          AND max(?26, ?25)
        AND (
          CASE
            WHEN ?28 <= ?27 THEN
              a.gps_longitude BETWEEN ?28 AND ?27
            ELSE
              a.gps_longitude >= ?28
              OR a.gps_longitude <= ?27
          END
        )
      )
    )
  ORDER BY
    sort_time DESC,
    a.asset_id DESC
  LIMIT ?30 OFFSET ?29
)
SELECT a.asset_id, a.owner_id, a.type, a.original_filename, a.storage_path, a.mime_type, a.file_size, a.content_hash, a.quick_fingerprint, a.quick_fingerprint_version, a.width, a.height, a.duration, a.upload_time, a.taken_time, a.capture_offset_minutes, a.is_deleted, a.deleted_at, a.specific_metadata, a.rating, a.liked, a.repository_id, a.status, a.updated_at, a.gps_latitude, a.gps_longitude, a.gps_geohash_5, a.gps_geohash_7, a.exif_raw
FROM page_ids p
JOIN assets a ON a.asset_id = p.asset_id
ORDER BY p.sort_time DESC, p.asset_id DESC
`

type GetAssetsUnifiedParams struct {
	AssetIds         *string     `db:"asset_ids" json:"asset_ids"`
	AssetTypes       *string     `db:"asset_types" json:"asset_types"`
	TagNames         *string     `db:"tag_names" json:"tag_names"`
	SortBy           interface{} `db:"sort_by" json:"sort_by"`
	IsDeleted        bool        `db:"is_deleted" json:"is_deleted"`
	Query            interface{} `db:"query" json:"query"`
	AssetType        interface{} `db:"asset_type" json:"asset_type"`
	OwnerID          interface{} `db:"owner_id" json:"owner_id"`
	RepositoryID     interface{} `db:"repository_id" json:"repository_id"`
	FolderPath       interface{} `db:"folder_path" json:"folder_path"`
	FolderRecursive  interface{} `db:"folder_recursive" json:"folder_recursive"`
	PersonID         interface{} `db:"person_id" json:"person_id"`
	AlbumID          interface{} `db:"album_id" json:"album_id"`
	TagName          interface{} `db:"tag_name" json:"tag_name"`
	TagSource        interface{} `db:"tag_source" json:"tag_source"`
	FilenameVal      interface{} `db:"filename_val" json:"filename_val"`
	FilenameOperator interface{} `db:"filename_operator" json:"filename_operator"`
	DateFrom         interface{} `db:"date_from" json:"date_from"`
	DateTo           interface{} `db:"date_to" json:"date_to"`
	IsRaw            interface{} `db:"is_raw" json:"is_raw"`
	Rating           interface{} `db:"rating" json:"rating"`
	Liked            interface{} `db:"liked" json:"liked"`
	CameraModel      interface{} `db:"camera_model" json:"camera_model"`
	LensModel        interface{} `db:"lens_model" json:"lens_model"`
	LocationNorth    interface{} `db:"location_north" json:"location_north"`
	LocationSouth    interface{} `db:"location_south" json:"location_south"`
	LocationEast     interface{} `db:"location_east" json:"location_east"`
	LocationWest     interface{} `db:"location_west" json:"location_west"`
	Offset           int64       `db:"offset" json:"offset"`
	Limit            int64       `db:"limit" json:"limit"`
}

// Handles: listing, filename search, and all filtering
// Use this for most queries unless semantic search is needed
func (q *Queries) GetAssetsUnified(ctx context.Context, arg GetAssetsUnifiedParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, getAssetsUnified,
		arg.AssetIds,
		arg.AssetTypes,
		arg.TagNames,
		arg.SortBy,
		arg.IsDeleted,
		arg.Query,
		arg.AssetType,
		arg.OwnerID,
		arg.RepositoryID,
		arg.FolderPath,
		arg.FolderRecursive,
		arg.PersonID,
		arg.AlbumID,
		arg.TagName,
		arg.TagSource,
		arg.FilenameVal,
		arg.FilenameOperator,
		arg.DateFrom,
		arg.DateTo,
		arg.IsRaw,
		arg.Rating,
		arg.Liked,
		arg.CameraModel,
		arg.LensModel,
		arg.LocationNorth,
		arg.LocationSouth,
		arg.LocationEast,
		arg.LocationWest,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.AssetID,
			&i.OwnerID,
			&i.Type,
			&i.OriginalFilename,
			&i.StoragePath,
			&i.MimeType,
			&i.FileSize,
			&i.ContentHash,
			&i.QuickFingerprint,
			&i.QuickFingerprintVersion,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.UploadTime,
			&i.TakenTime,
			&i.CaptureOffsetMinutes,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.SpecificMetadata,
			&i.Rating,
			&i.Liked,
			&i.RepositoryID,
			&i.Status,
			&i.UpdatedAt,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.GpsGeohash5,
			&i.GpsGeohash7,
			&i.ExifRaw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
