// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: asset_quality_scores.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssetQualityScore = `-- name: GetAssetQualityScore :one
SELECT asset_id, score, model_version, created_at, updated_at
FROM asset_quality_scores
WHERE asset_id = $1
`

func (q *Queries) GetAssetQualityScore(ctx context.Context, assetID pgtype.UUID) (AssetQualityScore, error) {
	row := q.db.QueryRow(ctx, getAssetQualityScore, assetID)
	var i AssetQualityScore
	err := row.Scan(
		&i.AssetID,
		&i.Score,
		&i.ModelVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAssetQualityScore = `-- name: UpsertAssetQualityScore :one

INSERT INTO asset_quality_scores (asset_id, score, model_version)
VALUES ($1, $2, $3)
ON CONFLICT (asset_id)
DO UPDATE SET
    score = EXCLUDED.score,
    model_version = EXCLUDED.model_version,
    updated_at = NOW()
RETURNING asset_id, score, model_version, created_at, updated_at
`

type UpsertAssetQualityScoreParams struct {
	AssetID      pgtype.UUID `db:"asset_id" json:"asset_id"`
	Score        float32     `db:"score" json:"score"`
	ModelVersion string      `db:"model_version" json:"model_version"`
}

// Asset quality scores: per-asset aesthetic score from MLP head on SigLIP.
func (q *Queries) UpsertAssetQualityScore(ctx context.Context, arg UpsertAssetQualityScoreParams) (AssetQualityScore, error) {
	row := q.db.QueryRow(ctx, upsertAssetQualityScore, arg.AssetID, arg.Score, arg.ModelVersion)
	var i AssetQualityScore
	err := row.Scan(
		&i.AssetID,
		&i.Score,
		&i.ModelVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
