// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"server/internal/db/dbtypes"
)

const agentLookupEvents = `-- name: AgentLookupEvents :many
SELECT e.event_id,e.start_at,e.end_at,e.title_override,count(emi.media_item_id) AS media_count
FROM events e
JOIN event_media_items emi ON emi.event_id=e.event_id AND emi.owner_id=e.owner_id
WHERE e.owner_id=? AND e.status='active'
  AND (?3 IS NULL OR e.title_override LIKE '%' || ?3 || '%')
GROUP BY e.event_id
ORDER BY e.start_at DESC,e.event_id DESC
LIMIT ?
`

type AgentLookupEventsParams struct {
	OwnerID    int32       `db:"owner_id" json:"owner_id"`
	TitleQuery interface{} `db:"title_query" json:"title_query"`
	Limit      int64       `db:"limit" json:"limit"`
}

type AgentLookupEventsRow struct {
	EventID       string  `db:"event_id" json:"event_id"`
	StartAt       int64   `db:"start_at" json:"start_at"`
	EndAt         int64   `db:"end_at" json:"end_at"`
	TitleOverride *string `db:"title_override" json:"title_override"`
	MediaCount    int64   `db:"media_count" json:"media_count"`
}

func (q *Queries) AgentLookupEvents(ctx context.Context, arg AgentLookupEventsParams) ([]AgentLookupEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, agentLookupEvents, arg.OwnerID, arg.TitleQuery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentLookupEventsRow
	for rows.Next() {
		var i AgentLookupEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.StartAt,
			&i.EndAt,
			&i.TitleOverride,
			&i.MediaCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimEventDirtyRanges = `-- name: ClaimEventDirtyRanges :execrows
UPDATE event_dirty_ranges
SET claimed_at = ?, claim_token = ?
WHERE owner_id = ? AND claim_token IS NULL
`

type ClaimEventDirtyRangesParams struct {
	ClaimedAt  *int64  `db:"claimed_at" json:"claimed_at"`
	ClaimToken *string `db:"claim_token" json:"claim_token"`
	OwnerID    int32   `db:"owner_id" json:"owner_id"`
}

func (q *Queries) ClaimEventDirtyRanges(ctx context.Context, arg ClaimEventDirtyRangesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimEventDirtyRanges, arg.ClaimedAt, arg.ClaimToken, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearEventCovers = `-- name: ClearEventCovers :exec
UPDATE events
SET generated_cover_media_item_id = NULL, cover_override_media_item_id = NULL,
    updated_at = ?
WHERE event_id = ? AND owner_id = ?
`

type ClearEventCoversParams struct {
	UpdatedAt dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
	EventID   string            `db:"event_id" json:"event_id"`
	OwnerID   int32             `db:"owner_id" json:"owner_id"`
}

func (q *Queries) ClearEventCovers(ctx context.Context, arg ClearEventCoversParams) error {
	_, err := q.db.ExecContext(ctx, clearEventCovers, arg.UpdatedAt, arg.EventID, arg.OwnerID)
	return err
}

const clearStaleEventDirtyClaims = `-- name: ClearStaleEventDirtyClaims :execrows
UPDATE event_dirty_ranges
SET claimed_at = NULL, claim_token = NULL
WHERE claimed_at IS NOT NULL AND claimed_at < ?
`

func (q *Queries) ClearStaleEventDirtyClaims(ctx context.Context, claimedAt *int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearStaleEventDirtyClaims, claimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const compareAndAdvanceEventRevision = `-- name: CompareAndAdvanceEventRevision :execrows
UPDATE event_owner_state
SET revision = revision + 1, updated_at = ?
WHERE owner_id = ? AND revision = ? AND automatic_rebuild_paused = 0
`

type CompareAndAdvanceEventRevisionParams struct {
	UpdatedAt dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
	OwnerID   int32             `db:"owner_id" json:"owner_id"`
	Revision  int64             `db:"revision" json:"revision"`
}

func (q *Queries) CompareAndAdvanceEventRevision(ctx context.Context, arg CompareAndAdvanceEventRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, compareAndAdvanceEventRevision, arg.UpdatedAt, arg.OwnerID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteClaimedEventDirtyRanges = `-- name: DeleteClaimedEventDirtyRanges :execrows
DELETE FROM event_dirty_ranges WHERE owner_id = ? AND claim_token = ?
`

type DeleteClaimedEventDirtyRangesParams struct {
	OwnerID    int32   `db:"owner_id" json:"owner_id"`
	ClaimToken *string `db:"claim_token" json:"claim_token"`
}

func (q *Queries) DeleteClaimedEventDirtyRanges(ctx context.Context, arg DeleteClaimedEventDirtyRangesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteClaimedEventDirtyRanges, arg.OwnerID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEventConstraint = `-- name: DeleteEventConstraint :exec
DELETE FROM event_constraints WHERE constraint_id = ? AND owner_id = ?
`

type DeleteEventConstraintParams struct {
	ConstraintID string `db:"constraint_id" json:"constraint_id"`
	OwnerID      int32  `db:"owner_id" json:"owner_id"`
}

func (q *Queries) DeleteEventConstraint(ctx context.Context, arg DeleteEventConstraintParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventConstraint, arg.ConstraintID, arg.OwnerID)
	return err
}

const deleteEventMemberships = `-- name: DeleteEventMemberships :exec
DELETE FROM event_media_items WHERE event_id = ? AND owner_id = ?
`

type DeleteEventMembershipsParams struct {
	EventID string `db:"event_id" json:"event_id"`
	OwnerID int32  `db:"owner_id" json:"owner_id"`
}

func (q *Queries) DeleteEventMemberships(ctx context.Context, arg DeleteEventMembershipsParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventMemberships, arg.EventID, arg.OwnerID)
	return err
}

const eventCandidateTimeBounds = `-- name: EventCandidateTimeBounds :one
SELECT
  min(COALESCE(a.taken_time, a.upload_time, mi.created_at)) AS range_start,
  max(COALESCE(a.taken_time, a.upload_time, mi.created_at)) AS range_end
FROM media_items mi
LEFT JOIN assets a ON a.asset_id = mi.primary_asset_id
WHERE mi.owner_id = ?
`

type EventCandidateTimeBoundsRow struct {
	RangeStart interface{} `db:"range_start" json:"range_start"`
	RangeEnd   interface{} `db:"range_end" json:"range_end"`
}

func (q *Queries) EventCandidateTimeBounds(ctx context.Context, ownerID *int32) (EventCandidateTimeBoundsRow, error) {
	row := q.db.QueryRowContext(ctx, eventCandidateTimeBounds, ownerID)
	var i EventCandidateTimeBoundsRow
	err := row.Scan(&i.RangeStart, &i.RangeEnd)
	return i, err
}

const getEventAssetIDsForAgent = `-- name: GetEventAssetIDsForAgent :many
SELECT COALESCE(
  CASE WHEN primary_asset.is_deleted = 0 THEN primary_asset.asset_id END,
  (
    SELECT a.asset_id FROM media_item_assets mia
    JOIN assets a ON a.asset_id=mia.asset_id
    WHERE mia.media_item_id=emi.media_item_id
      AND a.owner_id=emi.owner_id AND a.is_deleted=0
    ORDER BY mia.position,mia.asset_id LIMIT 1
  )
) AS resolved_asset_id
FROM event_media_items emi
JOIN events e ON e.event_id=emi.event_id AND e.owner_id=emi.owner_id
JOIN media_items mi ON mi.media_item_id=emi.media_item_id AND mi.owner_id=emi.owner_id
LEFT JOIN assets primary_asset ON primary_asset.asset_id=mi.primary_asset_id
WHERE emi.event_id=? AND emi.owner_id=? AND e.status='active'
ORDER BY emi.position,emi.media_item_id
LIMIT ?
`

type GetEventAssetIDsForAgentParams struct {
	EventID string `db:"event_id" json:"event_id"`
	OwnerID int32  `db:"owner_id" json:"owner_id"`
	Limit   int64  `db:"limit" json:"limit"`
}

func (q *Queries) GetEventAssetIDsForAgent(ctx context.Context, arg GetEventAssetIDsForAgentParams) ([]interface{}, error) {
	rows, err := q.db.QueryContext(ctx, getEventAssetIDsForAgent, arg.EventID, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var resolved_asset_id interface{}
		if err := rows.Scan(&resolved_asset_id); err != nil {
			return nil, err
		}
		items = append(items, resolved_asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventForOwner = `-- name: GetEventForOwner :one
SELECT event_id, owner_id, status, start_at, end_at, timezone, generated_title, title_override, generated_cover_media_item_id, cover_override_media_item_id, is_hidden, algorithm_version, created_at, updated_at FROM events WHERE event_id = ? AND owner_id = ?
`

type GetEventForOwnerParams struct {
	EventID string `db:"event_id" json:"event_id"`
	OwnerID int32  `db:"owner_id" json:"owner_id"`
}

func (q *Queries) GetEventForOwner(ctx context.Context, arg GetEventForOwnerParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventForOwner, arg.EventID, arg.OwnerID)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.OwnerID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.Timezone,
		&i.GeneratedTitle,
		&i.TitleOverride,
		&i.GeneratedCoverMediaItemID,
		&i.CoverOverrideMediaItemID,
		&i.IsHidden,
		&i.AlgorithmVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventOwnerState = `-- name: GetEventOwnerState :one
SELECT owner_id, active_algorithm_version, initialized_at, last_full_rebuild_at, automatic_rebuild_paused, revision, updated_at, source_revision, published_revision, rebuild_lease_token, rebuild_lease_expires_at FROM event_owner_state WHERE owner_id = ?
`

func (q *Queries) GetEventOwnerState(ctx context.Context, ownerID int32) (EventOwnerState, error) {
	row := q.db.QueryRowContext(ctx, getEventOwnerState, ownerID)
	var i EventOwnerState
	err := row.Scan(
		&i.OwnerID,
		&i.ActiveAlgorithmVersion,
		&i.InitializedAt,
		&i.LastFullRebuildAt,
		&i.AutomaticRebuildPaused,
		&i.Revision,
		&i.UpdatedAt,
		&i.SourceRevision,
		&i.PublishedRevision,
		&i.RebuildLeaseToken,
		&i.RebuildLeaseExpiresAt,
	)
	return i, err
}

const getEventRedirectForOwner = `-- name: GetEventRedirectForOwner :one
SELECT r.new_event_id
FROM event_redirects r
JOIN events target
  ON target.event_id = r.new_event_id AND target.owner_id = r.owner_id
WHERE r.old_event_id = ? AND r.owner_id = ? AND target.status = 'active'
`

type GetEventRedirectForOwnerParams struct {
	OldEventID string `db:"old_event_id" json:"old_event_id"`
	OwnerID    int32  `db:"owner_id" json:"owner_id"`
}

func (q *Queries) GetEventRedirectForOwner(ctx context.Context, arg GetEventRedirectForOwnerParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getEventRedirectForOwner, arg.OldEventID, arg.OwnerID)
	var new_event_id string
	err := row.Scan(&new_event_id)
	return new_event_id, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
  event_id, owner_id, status, start_at, end_at, timezone, generated_title,
  title_override, generated_cover_media_item_id, cover_override_media_item_id,
  is_hidden, algorithm_version, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, NULL, ?, NULL, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	EventID                  string            `db:"event_id" json:"event_id"`
	OwnerID                  int32             `db:"owner_id" json:"owner_id"`
	Status                   string            `db:"status" json:"status"`
	StartAt                  int64             `db:"start_at" json:"start_at"`
	EndAt                    int64             `db:"end_at" json:"end_at"`
	Timezone                 *string           `db:"timezone" json:"timezone"`
	TitleOverride            *string           `db:"title_override" json:"title_override"`
	CoverOverrideMediaItemID *string           `db:"cover_override_media_item_id" json:"cover_override_media_item_id"`
	IsHidden                 bool              `db:"is_hidden" json:"is_hidden"`
	AlgorithmVersion         string            `db:"algorithm_version" json:"algorithm_version"`
	CreatedAt                dbtypes.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt                dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.EventID,
		arg.OwnerID,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.Timezone,
		arg.TitleOverride,
		arg.CoverOverrideMediaItemID,
		arg.IsHidden,
		arg.AlgorithmVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertEventConstraint = `-- name: InsertEventConstraint :exec
INSERT INTO event_constraints (
  constraint_id, owner_id, kind, event_id, left_media_item_id,
  right_media_item_id, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventConstraintParams struct {
	ConstraintID     string            `db:"constraint_id" json:"constraint_id"`
	OwnerID          int32             `db:"owner_id" json:"owner_id"`
	Kind             string            `db:"kind" json:"kind"`
	EventID          *string           `db:"event_id" json:"event_id"`
	LeftMediaItemID  string            `db:"left_media_item_id" json:"left_media_item_id"`
	RightMediaItemID *string           `db:"right_media_item_id" json:"right_media_item_id"`
	CreatedAt        dbtypes.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertEventConstraint(ctx context.Context, arg InsertEventConstraintParams) error {
	_, err := q.db.ExecContext(ctx, insertEventConstraint,
		arg.ConstraintID,
		arg.OwnerID,
		arg.Kind,
		arg.EventID,
		arg.LeftMediaItemID,
		arg.RightMediaItemID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertEventDirtyRange = `-- name: InsertEventDirtyRange :exec
INSERT INTO event_dirty_ranges (
  dirty_range_id, owner_id, range_start, range_end, reason, created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertEventDirtyRangeParams struct {
	DirtyRangeID string            `db:"dirty_range_id" json:"dirty_range_id"`
	OwnerID      int32             `db:"owner_id" json:"owner_id"`
	RangeStart   int64             `db:"range_start" json:"range_start"`
	RangeEnd     int64             `db:"range_end" json:"range_end"`
	Reason       string            `db:"reason" json:"reason"`
	CreatedAt    dbtypes.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertEventDirtyRange(ctx context.Context, arg InsertEventDirtyRangeParams) error {
	_, err := q.db.ExecContext(ctx, insertEventDirtyRange,
		arg.DirtyRangeID,
		arg.OwnerID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const insertEventMembership = `-- name: InsertEventMembership :exec
INSERT INTO event_media_items (
  event_id, owner_id, media_item_id, position, source, confidence, evidence,
  derivation_run_id, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventMembershipParams struct {
	EventID         string            `db:"event_id" json:"event_id"`
	OwnerID         int32             `db:"owner_id" json:"owner_id"`
	MediaItemID     uuid.UUID         `db:"media_item_id" json:"media_item_id"`
	Position        int64             `db:"position" json:"position"`
	Source          string            `db:"source" json:"source"`
	Confidence      *float64          `db:"confidence" json:"confidence"`
	Evidence        string            `db:"evidence" json:"evidence"`
	DerivationRunID *string           `db:"derivation_run_id" json:"derivation_run_id"`
	CreatedAt       dbtypes.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertEventMembership(ctx context.Context, arg InsertEventMembershipParams) error {
	_, err := q.db.ExecContext(ctx, insertEventMembership,
		arg.EventID,
		arg.OwnerID,
		arg.MediaItemID,
		arg.Position,
		arg.Source,
		arg.Confidence,
		arg.Evidence,
		arg.DerivationRunID,
		arg.CreatedAt,
	)
	return err
}

const insertEventRedirect = `-- name: InsertEventRedirect :exec
INSERT INTO event_redirects (old_event_id, owner_id, new_event_id, reason, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertEventRedirectParams struct {
	OldEventID string            `db:"old_event_id" json:"old_event_id"`
	OwnerID    int32             `db:"owner_id" json:"owner_id"`
	NewEventID string            `db:"new_event_id" json:"new_event_id"`
	Reason     string            `db:"reason" json:"reason"`
	CreatedAt  dbtypes.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertEventRedirect(ctx context.Context, arg InsertEventRedirectParams) error {
	_, err := q.db.ExecContext(ctx, insertEventRedirect,
		arg.OldEventID,
		arg.OwnerID,
		arg.NewEventID,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const listClaimedEventDirtyRanges = `-- name: ListClaimedEventDirtyRanges :many
SELECT dirty_range_id, owner_id, range_start, range_end, reason, claimed_at, claim_token, created_at FROM event_dirty_ranges
WHERE owner_id = ? AND claim_token = ?
ORDER BY range_start, range_end, dirty_range_id
`

type ListClaimedEventDirtyRangesParams struct {
	OwnerID    int32   `db:"owner_id" json:"owner_id"`
	ClaimToken *string `db:"claim_token" json:"claim_token"`
}

func (q *Queries) ListClaimedEventDirtyRanges(ctx context.Context, arg ListClaimedEventDirtyRangesParams) ([]EventDirtyRange, error) {
	rows, err := q.db.QueryContext(ctx, listClaimedEventDirtyRanges, arg.OwnerID, arg.ClaimToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventDirtyRange
	for rows.Next() {
		var i EventDirtyRange
		if err := rows.Scan(
			&i.DirtyRangeID,
			&i.OwnerID,
			&i.RangeStart,
			&i.RangeEnd,
			&i.Reason,
			&i.ClaimedAt,
			&i.ClaimToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventCandidates = `-- name: ListEventCandidates :many
SELECT
  mi.media_item_id,
  COALESCE(capture.taken_time, upload.upload_time, mi.created_at) AS captured_at,
  CASE
    WHEN capture.taken_time IS NOT NULL THEN 'taken_time'
    WHEN upload.upload_time IS NOT NULL THEN 'upload_time'
    ELSE 'created_at'
  END AS time_source,
  CASE WHEN capture.taken_time IS NOT NULL THEN capture.capture_offset_minutes END AS capture_offset_minutes,
  COALESCE(primary_asset.gps_latitude, component.gps_latitude) AS gps_latitude,
  COALESCE(primary_asset.gps_longitude, component.gps_longitude) AS gps_longitude,
  COALESCE(asm.stack_id, '') AS stack_key
FROM media_items mi
LEFT JOIN assets primary_asset ON primary_asset.asset_id = mi.primary_asset_id
LEFT JOIN asset_stack_members asm ON asm.media_item_id = mi.media_item_id
LEFT JOIN assets capture ON capture.asset_id = (
  SELECT mia.asset_id
  FROM media_item_assets mia
  JOIN assets ca ON ca.asset_id = mia.asset_id
  WHERE mia.media_item_id = mi.media_item_id AND ca.taken_time IS NOT NULL
  ORDER BY ca.taken_time, ca.asset_id
  LIMIT 1
)
LEFT JOIN assets upload ON upload.asset_id = (
  SELECT mia.asset_id
  FROM media_item_assets mia
  JOIN assets ua ON ua.asset_id = mia.asset_id
  WHERE mia.media_item_id = mi.media_item_id
  ORDER BY ua.upload_time, ua.asset_id
  LIMIT 1
)
LEFT JOIN assets component ON component.asset_id = (
  SELECT mia.asset_id
  FROM media_item_assets mia
  JOIN assets ga ON ga.asset_id = mia.asset_id
  WHERE mia.media_item_id = mi.media_item_id
    AND ga.gps_latitude IS NOT NULL AND ga.gps_longitude IS NOT NULL
  ORDER BY CASE mia.relation
    WHEN 'live_photo_still' THEN 0 WHEN 'jpeg_original' THEN 1
    WHEN 'raw_original' THEN 2 WHEN 'original' THEN 3
    WHEN 'edited_version' THEN 4 WHEN 'alternative' THEN 5
    WHEN 'component' THEN 6 WHEN 'live_photo_video' THEN 7 ELSE 8 END,
    mia.position, mia.asset_id
  LIMIT 1
)
WHERE mi.owner_id = ?
ORDER BY captured_at, mi.media_item_id
`

type ListEventCandidatesRow struct {
	MediaItemID          uuid.UUID         `db:"media_item_id" json:"media_item_id"`
	CapturedAt           dbtypes.Timestamp `db:"captured_at" json:"captured_at"`
	TimeSource           string            `db:"time_source" json:"time_source"`
	CaptureOffsetMinutes interface{}       `db:"capture_offset_minutes" json:"capture_offset_minutes"`
	GpsLatitude          *float64          `db:"gps_latitude" json:"gps_latitude"`
	GpsLongitude         *float64          `db:"gps_longitude" json:"gps_longitude"`
	StackKey             uuid.UUID         `db:"stack_key" json:"stack_key"`
}

func (q *Queries) ListEventCandidates(ctx context.Context, ownerID *int32) ([]ListEventCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventCandidates, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventCandidatesRow
	for rows.Next() {
		var i ListEventCandidatesRow
		if err := rows.Scan(
			&i.MediaItemID,
			&i.CapturedAt,
			&i.TimeSource,
			&i.CaptureOffsetMinutes,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.StackKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventConstraints = `-- name: ListEventConstraints :many
SELECT constraint_id, owner_id, kind, event_id, left_media_item_id, right_media_item_id, created_at, updated_at FROM event_constraints WHERE owner_id = ?
ORDER BY kind, event_id, left_media_item_id, right_media_item_id
`

func (q *Queries) ListEventConstraints(ctx context.Context, ownerID int32) ([]EventConstraint, error) {
	rows, err := q.db.QueryContext(ctx, listEventConstraints, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventConstraint
	for rows.Next() {
		var i EventConstraint
		if err := rows.Scan(
			&i.ConstraintID,
			&i.OwnerID,
			&i.Kind,
			&i.EventID,
			&i.LeftMediaItemID,
			&i.RightMediaItemID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventMembership = `-- name: ListEventMembership :many
SELECT event_id, owner_id, media_item_id, position, source, confidence, evidence, derivation_run_id, created_at
FROM event_media_items
WHERE event_id = ? AND owner_id = ?
ORDER BY position, media_item_id
`

type ListEventMembershipParams struct {
	EventID string `db:"event_id" json:"event_id"`
	OwnerID int32  `db:"owner_id" json:"owner_id"`
}

func (q *Queries) ListEventMembership(ctx context.Context, arg ListEventMembershipParams) ([]EventMediaItem, error) {
	rows, err := q.db.QueryContext(ctx, listEventMembership, arg.EventID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventMediaItem
	for rows.Next() {
		var i EventMediaItem
		if err := rows.Scan(
			&i.EventID,
			&i.OwnerID,
			&i.MediaItemID,
			&i.Position,
			&i.Source,
			&i.Confidence,
			&i.Evidence,
			&i.DerivationRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventMembershipPage = `-- name: ListEventMembershipPage :many
SELECT event_id, owner_id, media_item_id, position, source, confidence, evidence, derivation_run_id, created_at
FROM event_media_items
WHERE event_id = ? AND owner_id = ?
  AND (
    position > ?4
    OR (position = ?4 AND media_item_id > ?5)
  )
ORDER BY position, media_item_id
LIMIT ?
`

type ListEventMembershipPageParams struct {
	EventID           string    `db:"event_id" json:"event_id"`
	OwnerID           int32     `db:"owner_id" json:"owner_id"`
	CursorPosition    int64     `db:"cursor_position" json:"cursor_position"`
	CursorMediaItemID uuid.UUID `db:"cursor_media_item_id" json:"cursor_media_item_id"`
	Limit             int64     `db:"limit" json:"limit"`
}

func (q *Queries) ListEventMembershipPage(ctx context.Context, arg ListEventMembershipPageParams) ([]EventMediaItem, error) {
	rows, err := q.db.QueryContext(ctx, listEventMembershipPage,
		arg.EventID,
		arg.OwnerID,
		arg.CursorPosition,
		arg.CursorMediaItemID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventMediaItem
	for rows.Next() {
		var i EventMediaItem
		if err := rows.Scan(
			&i.EventID,
			&i.OwnerID,
			&i.MediaItemID,
			&i.Position,
			&i.Source,
			&i.Confidence,
			&i.Evidence,
			&i.DerivationRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsPage = `-- name: ListEventsPage :many
SELECT event_id, owner_id, status, start_at, end_at, timezone, generated_title, title_override, generated_cover_media_item_id, cover_override_media_item_id, is_hidden, algorithm_version, created_at, updated_at
FROM events
WHERE owner_id = ?
  AND status = 'active'
  AND is_hidden = 0
  AND (
    ?3 IS NULL
    OR start_at < ?3
    OR (start_at = ?3 AND event_id < ?4)
  )
ORDER BY start_at DESC, event_id DESC
LIMIT ?
`

type ListEventsPageParams struct {
	OwnerID       int32       `db:"owner_id" json:"owner_id"`
	CursorStartAt interface{} `db:"cursor_start_at" json:"cursor_start_at"`
	CursorEventID *string     `db:"cursor_event_id" json:"cursor_event_id"`
	Limit         int64       `db:"limit" json:"limit"`
}

func (q *Queries) ListEventsPage(ctx context.Context, arg ListEventsPageParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsPage,
		arg.OwnerID,
		arg.CursorStartAt,
		arg.CursorEventID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.OwnerID,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.Timezone,
			&i.GeneratedTitle,
			&i.TitleOverride,
			&i.GeneratedCoverMediaItemID,
			&i.CoverOverrideMediaItemID,
			&i.IsHidden,
			&i.AlgorithmVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnersWithEventDirtyRanges = `-- name: ListOwnersWithEventDirtyRanges :many
SELECT DISTINCT owner_id FROM event_dirty_ranges
WHERE claim_token IS NULL OR claimed_at < ?
ORDER BY owner_id
`

func (q *Queries) ListOwnersWithEventDirtyRanges(ctx context.Context, claimedAt *int64) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listOwnersWithEventDirtyRanges, claimedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var owner_id int32
		if err := rows.Scan(&owner_id); err != nil {
			return nil, err
		}
		items = append(items, owner_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventRedirected = `-- name: MarkEventRedirected :exec
UPDATE events SET status = 'redirected', updated_at = ?
WHERE event_id = ? AND owner_id = ? AND status = 'active'
`

type MarkEventRedirectedParams struct {
	UpdatedAt dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
	EventID   string            `db:"event_id" json:"event_id"`
	OwnerID   int32             `db:"owner_id" json:"owner_id"`
}

func (q *Queries) MarkEventRedirected(ctx context.Context, arg MarkEventRedirectedParams) error {
	_, err := q.db.ExecContext(ctx, markEventRedirected, arg.UpdatedAt, arg.EventID, arg.OwnerID)
	return err
}

const renewEventDirtyClaim = `-- name: RenewEventDirtyClaim :execrows
UPDATE event_dirty_ranges
SET claimed_at = ?
WHERE owner_id = ? AND claim_token = ?
`

type RenewEventDirtyClaimParams struct {
	ClaimedAt  *int64  `db:"claimed_at" json:"claimed_at"`
	OwnerID    int32   `db:"owner_id" json:"owner_id"`
	ClaimToken *string `db:"claim_token" json:"claim_token"`
}

func (q *Queries) RenewEventDirtyClaim(ctx context.Context, arg RenewEventDirtyClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewEventDirtyClaim, arg.ClaimedAt, arg.OwnerID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rewriteRedirectTargets = `-- name: RewriteRedirectTargets :exec
UPDATE event_redirects SET new_event_id = ?
WHERE owner_id = ? AND new_event_id = ?
`

type RewriteRedirectTargetsParams struct {
	NewEventID   string `db:"new_event_id" json:"new_event_id"`
	OwnerID      int32  `db:"owner_id" json:"owner_id"`
	NewEventID_2 string `db:"new_event_id_2" json:"new_event_id_2"`
}

func (q *Queries) RewriteRedirectTargets(ctx context.Context, arg RewriteRedirectTargetsParams) error {
	_, err := q.db.ExecContext(ctx, rewriteRedirectTargets, arg.NewEventID, arg.OwnerID, arg.NewEventID_2)
	return err
}

const setEventRebuildPaused = `-- name: SetEventRebuildPaused :execrows
UPDATE event_owner_state
SET automatic_rebuild_paused = ?, revision = revision + 1, updated_at = ?
WHERE owner_id = ?
`

type SetEventRebuildPausedParams struct {
	AutomaticRebuildPaused int64             `db:"automatic_rebuild_paused" json:"automatic_rebuild_paused"`
	UpdatedAt              dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
	OwnerID                int32             `db:"owner_id" json:"owner_id"`
}

func (q *Queries) SetEventRebuildPaused(ctx context.Context, arg SetEventRebuildPausedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setEventRebuildPaused, arg.AutomaticRebuildPaused, arg.UpdatedAt, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEventBoundsAndGeneratedCover = `-- name: UpdateEventBoundsAndGeneratedCover :exec
UPDATE events
SET start_at = ?, end_at = ?, timezone = ?, generated_title = NULL,
    generated_cover_media_item_id = ?, updated_at = ?
WHERE event_id = ? AND owner_id = ? AND status = 'active'
`

type UpdateEventBoundsAndGeneratedCoverParams struct {
	StartAt                   int64             `db:"start_at" json:"start_at"`
	EndAt                     int64             `db:"end_at" json:"end_at"`
	Timezone                  *string           `db:"timezone" json:"timezone"`
	GeneratedCoverMediaItemID *string           `db:"generated_cover_media_item_id" json:"generated_cover_media_item_id"`
	UpdatedAt                 dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
	EventID                   string            `db:"event_id" json:"event_id"`
	OwnerID                   int32             `db:"owner_id" json:"owner_id"`
}

func (q *Queries) UpdateEventBoundsAndGeneratedCover(ctx context.Context, arg UpdateEventBoundsAndGeneratedCoverParams) error {
	_, err := q.db.ExecContext(ctx, updateEventBoundsAndGeneratedCover,
		arg.StartAt,
		arg.EndAt,
		arg.Timezone,
		arg.GeneratedCoverMediaItemID,
		arg.UpdatedAt,
		arg.EventID,
		arg.OwnerID,
	)
	return err
}

const updateEventOverrides = `-- name: UpdateEventOverrides :exec
UPDATE events
SET title_override = ?, cover_override_media_item_id = ?, is_hidden = ?, updated_at = ?
WHERE event_id = ? AND owner_id = ? AND status = 'active'
`

type UpdateEventOverridesParams struct {
	TitleOverride            *string           `db:"title_override" json:"title_override"`
	CoverOverrideMediaItemID *string           `db:"cover_override_media_item_id" json:"cover_override_media_item_id"`
	IsHidden                 bool              `db:"is_hidden" json:"is_hidden"`
	UpdatedAt                dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
	EventID                  string            `db:"event_id" json:"event_id"`
	OwnerID                  int32             `db:"owner_id" json:"owner_id"`
}

func (q *Queries) UpdateEventOverrides(ctx context.Context, arg UpdateEventOverridesParams) error {
	_, err := q.db.ExecContext(ctx, updateEventOverrides,
		arg.TitleOverride,
		arg.CoverOverrideMediaItemID,
		arg.IsHidden,
		arg.UpdatedAt,
		arg.EventID,
		arg.OwnerID,
	)
	return err
}

const upsertEventOwnerState = `-- name: UpsertEventOwnerState :exec
INSERT INTO event_owner_state (
  owner_id, active_algorithm_version, initialized_at, last_full_rebuild_at,
  automatic_rebuild_paused, revision, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(owner_id) DO NOTHING
`

type UpsertEventOwnerStateParams struct {
	OwnerID                int32             `db:"owner_id" json:"owner_id"`
	ActiveAlgorithmVersion string            `db:"active_algorithm_version" json:"active_algorithm_version"`
	InitializedAt          int64             `db:"initialized_at" json:"initialized_at"`
	LastFullRebuildAt      *int64            `db:"last_full_rebuild_at" json:"last_full_rebuild_at"`
	AutomaticRebuildPaused int64             `db:"automatic_rebuild_paused" json:"automatic_rebuild_paused"`
	Revision               int64             `db:"revision" json:"revision"`
	UpdatedAt              dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertEventOwnerState(ctx context.Context, arg UpsertEventOwnerStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertEventOwnerState,
		arg.OwnerID,
		arg.ActiveAlgorithmVersion,
		arg.InitializedAt,
		arg.LastFullRebuildAt,
		arg.AutomaticRebuildPaused,
		arg.Revision,
		arg.UpdatedAt,
	)
	return err
}
