// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: folders.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const getFolderChildSummaries = `-- name: GetFolderChildSummaries :many

WITH RECURSIVE node_paths (repository_id, node_id, relative_path) AS (
  SELECT repository_id, node_id, CAST('' AS TEXT)
  FROM repository_nodes
  WHERE parent_node_id IS NULL AND lifecycle = 'active'

  UNION ALL

  SELECT
    child.repository_id,
    child.node_id,
    CASE
      WHEN parent.relative_path = '' THEN child.name
      ELSE parent.relative_path || '/' || child.name
    END
  FROM repository_nodes child
  JOIN node_paths parent
    ON parent.repository_id = child.repository_id
   AND parent.node_id = child.parent_node_id
  WHERE child.lifecycle = 'active'
),
scoped AS (
  SELECT
    asset.asset_id,
    asset.type,
    asset.taken_time,
    asset.upload_time,
    occurrence.repository_id,
    CASE
      WHEN ?1 = '' THEN node_path.relative_path
      ELSE substr(node_path.relative_path, length(?1) + 2)
    END AS remainder
  FROM assets asset
  JOIN active_asset_occurrences occurrence
    ON occurrence.asset_id = asset.asset_id
  JOIN node_paths node_path
    ON node_path.repository_id = occurrence.repository_id
   AND node_path.node_id = occurrence.node_id
  WHERE asset.is_deleted = false
    AND (?2 IS NULL OR asset.owner_id = ?2)
    AND (?3 IS NULL OR occurrence.repository_id = ?3)
    AND node_path.relative_path NOT LIKE '.lumilio/%'
    AND node_path.relative_path NOT LIKE 'inbox/%'
    AND (
      ?1 = ''
      OR node_path.relative_path LIKE ?1 || '/%'
    )
),
child_folders AS (
  SELECT
    asset_id,
    type,
    taken_time,
    upload_time,
    repository_id,
    substr(remainder, 1, instr(remainder, '/') - 1) AS child_name
  FROM scoped
  WHERE remainder LIKE '%/%'
),
ranked AS (
  SELECT
    child_folders.asset_id, child_folders.type, child_folders.taken_time, child_folders.upload_time, child_folders.repository_id, child_folders.child_name,
    ROW_NUMBER() OVER (
      PARTITION BY repository_id, child_name
      ORDER BY COALESCE(taken_time, upload_time) DESC, asset_id DESC
    ) AS cover_rank
  FROM child_folders
)
SELECT
  repository_id,
  child_name,
  COUNT(DISTINCT asset_id) AS asset_count,
  COUNT(DISTINCT asset_id) FILTER (WHERE type = 'PHOTO') AS photo_count,
  COUNT(DISTINCT asset_id) FILTER (WHERE type = 'VIDEO') AS video_count,
  COUNT(DISTINCT asset_id) FILTER (WHERE type = 'AUDIO') AS audio_count,
  MIN(COALESCE(taken_time, upload_time)) AS date_start,
  MAX(COALESCE(taken_time, upload_time)) AS date_end,
  MAX(CASE WHEN cover_rank = 1 THEN asset_id END) AS cover_asset_id
FROM ranked
GROUP BY repository_id, child_name
ORDER BY child_name ASC
`

type GetFolderChildSummariesParams struct {
	ParentPath   interface{} `db:"parent_path" json:"parent_path"`
	OwnerID      interface{} `db:"owner_id" json:"owner_id"`
	RepositoryID interface{} `db:"repository_id" json:"repository_id"`
}

type GetFolderChildSummariesRow struct {
	RepositoryID uuid.UUID   `db:"repository_id" json:"repository_id"`
	ChildName    string      `db:"child_name" json:"child_name"`
	AssetCount   int64       `db:"asset_count" json:"asset_count"`
	PhotoCount   int64       `db:"photo_count" json:"photo_count"`
	VideoCount   int64       `db:"video_count" json:"video_count"`
	AudioCount   int64       `db:"audio_count" json:"audio_count"`
	DateStart    interface{} `db:"date_start" json:"date_start"`
	DateEnd      interface{} `db:"date_end" json:"date_end"`
	CoverAssetID interface{} `db:"cover_asset_id" json:"cover_asset_id"`
}

// Folder collection views are graph projections. Repository-relative paths
// are assembled by traversing repository_nodes and are never stored on Asset.
// Lists immediate child folders of parent_path and computes recursive
// descendant counts/covers from active Locations.
func (q *Queries) GetFolderChildSummaries(ctx context.Context, arg GetFolderChildSummariesParams) ([]GetFolderChildSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, getFolderChildSummaries, arg.ParentPath, arg.OwnerID, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFolderChildSummariesRow
	for rows.Next() {
		var i GetFolderChildSummariesRow
		if err := rows.Scan(
			&i.RepositoryID,
			&i.ChildName,
			&i.AssetCount,
			&i.PhotoCount,
			&i.VideoCount,
			&i.AudioCount,
			&i.DateStart,
			&i.DateEnd,
			&i.CoverAssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderSummary = `-- name: GetFolderSummary :one
WITH RECURSIVE node_paths (repository_id, node_id, relative_path) AS (
  SELECT repository_id, node_id, CAST('' AS TEXT)
  FROM repository_nodes
  WHERE parent_node_id IS NULL AND lifecycle = 'active'

  UNION ALL

  SELECT
    child.repository_id,
    child.node_id,
    CASE
      WHEN parent.relative_path = '' THEN child.name
      ELSE parent.relative_path || '/' || child.name
    END
  FROM repository_nodes child
  JOIN node_paths parent
    ON parent.repository_id = child.repository_id
   AND parent.node_id = child.parent_node_id
  WHERE child.lifecycle = 'active'
),
scoped AS (
  SELECT
    asset.asset_id,
    asset.type,
    asset.taken_time,
    asset.upload_time,
    ROW_NUMBER() OVER (
      ORDER BY COALESCE(asset.taken_time, asset.upload_time) DESC, asset.asset_id DESC
    ) AS cover_rank
  FROM assets asset
  JOIN active_asset_occurrences occurrence
    ON occurrence.asset_id = asset.asset_id
   AND occurrence.repository_id = ?1
  JOIN node_paths node_path
    ON node_path.repository_id = occurrence.repository_id
   AND node_path.node_id = occurrence.node_id
  WHERE asset.is_deleted = false
    AND (?2 IS NULL OR asset.owner_id = ?2)
    AND node_path.relative_path NOT LIKE '.lumilio/%'
    AND node_path.relative_path NOT LIKE 'inbox/%'
    AND (
      ?3 = ''
      OR node_path.relative_path LIKE ?3 || '/%'
    )
)
SELECT
  COUNT(DISTINCT asset_id) AS asset_count,
  COUNT(DISTINCT asset_id) FILTER (WHERE type = 'PHOTO') AS photo_count,
  COUNT(DISTINCT asset_id) FILTER (WHERE type = 'VIDEO') AS video_count,
  COUNT(DISTINCT asset_id) FILTER (WHERE type = 'AUDIO') AS audio_count,
  MIN(COALESCE(taken_time, upload_time)) AS date_start,
  MAX(COALESCE(taken_time, upload_time)) AS date_end,
  MAX(CASE WHEN cover_rank = 1 THEN asset_id END) AS cover_asset_id
FROM scoped
`

type GetFolderSummaryParams struct {
	RepositoryID uuid.UUID   `db:"repository_id" json:"repository_id"`
	OwnerID      interface{} `db:"owner_id" json:"owner_id"`
	FolderPath   interface{} `db:"folder_path" json:"folder_path"`
}

type GetFolderSummaryRow struct {
	AssetCount   int64       `db:"asset_count" json:"asset_count"`
	PhotoCount   int64       `db:"photo_count" json:"photo_count"`
	VideoCount   int64       `db:"video_count" json:"video_count"`
	AudioCount   int64       `db:"audio_count" json:"audio_count"`
	DateStart    interface{} `db:"date_start" json:"date_start"`
	DateEnd      interface{} `db:"date_end" json:"date_end"`
	CoverAssetID interface{} `db:"cover_asset_id" json:"cover_asset_id"`
}

// Aggregate stats for one graph-derived folder path and all descendants.
func (q *Queries) GetFolderSummary(ctx context.Context, arg GetFolderSummaryParams) (GetFolderSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getFolderSummary, arg.RepositoryID, arg.OwnerID, arg.FolderPath)
	var i GetFolderSummaryRow
	err := row.Scan(
		&i.AssetCount,
		&i.PhotoCount,
		&i.VideoCount,
		&i.AudioCount,
		&i.DateStart,
		&i.DateEnd,
		&i.CoverAssetID,
	)
	return i, err
}
