// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lifecycle_audit_events.sql

package repo

import (
	"context"
)

const insertLifecycleAuditEvent = `-- name: InsertLifecycleAuditEvent :one
INSERT INTO lifecycle_audit_events (
    event_id, occurred_at, actor, actor_user_id, host_instance_id, request_id,
    operation_id, action, target_type, target_id, source, confirmation_type,
    old_path, new_path, result, failure_stage, details
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17
)
RETURNING event_id, occurred_at, actor, actor_user_id, host_instance_id, request_id, operation_id, "action", target_type, target_id, source, confirmation_type, old_path, new_path, result, failure_stage, details
`

type InsertLifecycleAuditEventParams struct {
	EventID          string  `db:"event_id" json:"event_id"`
	OccurredAt       int64   `db:"occurred_at" json:"occurred_at"`
	Actor            string  `db:"actor" json:"actor"`
	ActorUserID      *int64  `db:"actor_user_id" json:"actor_user_id"`
	HostInstanceID   string  `db:"host_instance_id" json:"host_instance_id"`
	RequestID        string  `db:"request_id" json:"request_id"`
	OperationID      *string `db:"operation_id" json:"operation_id"`
	Action           string  `db:"action" json:"action"`
	TargetType       string  `db:"target_type" json:"target_type"`
	TargetID         *string `db:"target_id" json:"target_id"`
	Source           string  `db:"source" json:"source"`
	ConfirmationType string  `db:"confirmation_type" json:"confirmation_type"`
	OldPath          *string `db:"old_path" json:"old_path"`
	NewPath          *string `db:"new_path" json:"new_path"`
	Result           string  `db:"result" json:"result"`
	FailureStage     *string `db:"failure_stage" json:"failure_stage"`
	Details          string  `db:"details" json:"details"`
}

func (q *Queries) InsertLifecycleAuditEvent(ctx context.Context, arg InsertLifecycleAuditEventParams) (LifecycleAuditEvent, error) {
	row := q.db.QueryRowContext(ctx, insertLifecycleAuditEvent,
		arg.EventID,
		arg.OccurredAt,
		arg.Actor,
		arg.ActorUserID,
		arg.HostInstanceID,
		arg.RequestID,
		arg.OperationID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Source,
		arg.ConfirmationType,
		arg.OldPath,
		arg.NewPath,
		arg.Result,
		arg.FailureStage,
		arg.Details,
	)
	var i LifecycleAuditEvent
	err := row.Scan(
		&i.EventID,
		&i.OccurredAt,
		&i.Actor,
		&i.ActorUserID,
		&i.HostInstanceID,
		&i.RequestID,
		&i.OperationID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Source,
		&i.ConfirmationType,
		&i.OldPath,
		&i.NewPath,
		&i.Result,
		&i.FailureStage,
		&i.Details,
	)
	return i, err
}

const listLifecycleAuditEvents = `-- name: ListLifecycleAuditEvents :many
SELECT event_id, occurred_at, actor, actor_user_id, host_instance_id, request_id, operation_id, "action", target_type, target_id, source, confirmation_type, old_path, new_path, result, failure_stage, details FROM lifecycle_audit_events
ORDER BY occurred_at DESC, event_id DESC
LIMIT ?1 OFFSET ?2
`

type ListLifecycleAuditEventsParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) ListLifecycleAuditEvents(ctx context.Context, arg ListLifecycleAuditEventsParams) ([]LifecycleAuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listLifecycleAuditEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LifecycleAuditEvent
	for rows.Next() {
		var i LifecycleAuditEvent
		if err := rows.Scan(
			&i.EventID,
			&i.OccurredAt,
			&i.Actor,
			&i.ActorUserID,
			&i.HostInstanceID,
			&i.RequestID,
			&i.OperationID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Source,
			&i.ConfirmationType,
			&i.OldPath,
			&i.NewPath,
			&i.Result,
			&i.FailureStage,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifecycleAuditEventsForTarget = `-- name: ListLifecycleAuditEventsForTarget :many
SELECT event_id, occurred_at, actor, actor_user_id, host_instance_id, request_id, operation_id, "action", target_type, target_id, source, confirmation_type, old_path, new_path, result, failure_stage, details FROM lifecycle_audit_events
WHERE target_type = ?1 AND target_id = ?2
ORDER BY occurred_at DESC, event_id DESC
LIMIT ?3 OFFSET ?4
`

type ListLifecycleAuditEventsForTargetParams struct {
	TargetType string  `db:"target_type" json:"target_type"`
	TargetID   *string `db:"target_id" json:"target_id"`
	Limit      int64   `db:"limit" json:"limit"`
	Offset     int64   `db:"offset" json:"offset"`
}

func (q *Queries) ListLifecycleAuditEventsForTarget(ctx context.Context, arg ListLifecycleAuditEventsForTargetParams) ([]LifecycleAuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listLifecycleAuditEventsForTarget,
		arg.TargetType,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LifecycleAuditEvent
	for rows.Next() {
		var i LifecycleAuditEvent
		if err := rows.Scan(
			&i.EventID,
			&i.OccurredAt,
			&i.Actor,
			&i.ActorUserID,
			&i.HostInstanceID,
			&i.RequestID,
			&i.OperationID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Source,
			&i.ConfirmationType,
			&i.OldPath,
			&i.NewPath,
			&i.Result,
			&i.FailureStage,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
