// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
	"server/internal/db/dbtypes"
	"server/internal/storage/repocfg"
)

// AI-generated image descriptions table, storing detailed descriptions and metadata
type AiDescription struct {
	AssetID pgtype.UUID `db:"asset_id" json:"asset_id"`
	// AI model identifier, such as "gpt-4-vision", "llava-v1.5", etc.
	ModelID string `db:"model_id" json:"model_id"`
	// Generated detailed description of the image
	Description string `db:"description" json:"description"`
	// Brief summary of the description for quick display
	Summary *string `db:"summary" json:"summary"`
	// Model confidence score, between 0.0-1.0
	Confidence *float32 `db:"confidence" json:"confidence"`
	// Number of tokens generated by the model
	TokensGenerated *int32 `db:"tokens_generated" json:"tokens_generated"`
	// Processing time in milliseconds
	ProcessingTimeMs *int32 `db:"processing_time_ms" json:"processing_time_ms"`
	// The prompt template used for generation
	PromptUsed *string `db:"prompt_used" json:"prompt_used"`
	// Generation finish reason, such as "stop", "length", "content_filter"
	FinishReason *string            `db:"finish_reason" json:"finish_reason"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Album struct {
	AlbumID      int32              `db:"album_id" json:"album_id"`
	UserID       int32              `db:"user_id" json:"user_id"`
	AlbumName    string             `db:"album_name" json:"album_name"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Description  *string            `db:"description" json:"description"`
	CoverAssetID pgtype.UUID        `db:"cover_asset_id" json:"cover_asset_id"`
}

type AlbumAsset struct {
	AlbumID   int32              `db:"album_id" json:"album_id"`
	AssetID   pgtype.UUID        `db:"asset_id" json:"asset_id"`
	Position  *int32             `db:"position" json:"position"`
	AddedTime pgtype.Timestamptz `db:"added_time" json:"added_time"`
}

type Asset struct {
	AssetID          pgtype.UUID              `db:"asset_id" json:"asset_id"`
	OwnerID          *int32                   `db:"owner_id" json:"owner_id"`
	Type             string                   `db:"type" json:"type"`
	OriginalFilename string                   `db:"original_filename" json:"original_filename"`
	StoragePath      *string                  `db:"storage_path" json:"storage_path"`
	MimeType         string                   `db:"mime_type" json:"mime_type"`
	FileSize         int64                    `db:"file_size" json:"file_size"`
	Hash             *string                  `db:"hash" json:"hash"`
	Width            *int32                   `db:"width" json:"width"`
	Height           *int32                   `db:"height" json:"height"`
	Duration         *float64                 `db:"duration" json:"duration"`
	UploadTime       pgtype.Timestamptz       `db:"upload_time" json:"upload_time"`
	TakenTime        pgtype.Timestamptz       `db:"taken_time" json:"taken_time"`
	IsDeleted        *bool                    `db:"is_deleted" json:"is_deleted"`
	DeletedAt        pgtype.Timestamptz       `db:"deleted_at" json:"deleted_at"`
	SpecificMetadata dbtypes.SpecificMetadata `db:"specific_metadata" json:"specific_metadata"`
	Rating           *int32                   `db:"rating" json:"rating"`
	Liked            *bool                    `db:"liked" json:"liked"`
	RepositoryID     pgtype.UUID              `db:"repository_id" json:"repository_id"`
	Status           []byte                   `db:"status" json:"status"`
}

type AssetTag struct {
	AssetID    pgtype.UUID    `db:"asset_id" json:"asset_id"`
	TagID      int32          `db:"tag_id" json:"tag_id"`
	Confidence pgtype.Numeric `db:"confidence" json:"confidence"`
	Source     string         `db:"source" json:"source"`
}

type Embedding struct {
	ID                  int32              `db:"id" json:"id"`
	AssetID             pgtype.UUID        `db:"asset_id" json:"asset_id"`
	EmbeddingType       string             `db:"embedding_type" json:"embedding_type"`
	EmbeddingModel      string             `db:"embedding_model" json:"embedding_model"`
	EmbeddingDimensions int32              `db:"embedding_dimensions" json:"embedding_dimensions"`
	Vector              *pgvector.Vector   `db:"vector" json:"vector"`
	IsPrimary           *bool              `db:"is_primary" json:"is_primary"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Face recognition clusters table, grouping similar faces together
type FaceCluster struct {
	ClusterID int32 `db:"cluster_id" json:"cluster_id"`
	// User-assigned name for the person in this cluster
	ClusterName          *string `db:"cluster_name" json:"cluster_name"`
	RepresentativeFaceID int32   `db:"representative_face_id" json:"representative_face_id"`
	// Overall confidence score for this cluster
	ConfidenceScore *float32 `db:"confidence_score" json:"confidence_score"`
	// Number of faces currently in this cluster
	MemberCount *int32 `db:"member_count" json:"member_count"`
	// Whether this cluster has been confirmed and named by user
	IsConfirmed *bool              `db:"is_confirmed" json:"is_confirmed"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Face cluster membership table, linking faces to clusters
type FaceClusterMember struct {
	ID        int32 `db:"id" json:"id"`
	ClusterID int32 `db:"cluster_id" json:"cluster_id"`
	FaceID    int32 `db:"face_id" json:"face_id"`
	// Similarity score to cluster representative (0.0-1.0)
	SimilarityScore float32 `db:"similarity_score" json:"similarity_score"`
	// Assignment confidence to this cluster (0.0-1.0)
	Confidence float32 `db:"confidence" json:"confidence"`
	// Whether this face was manually assigned to this cluster
	IsManual  *bool              `db:"is_manual" json:"is_manual"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Detected face items table, storing detailed information for each face
type FaceItem struct {
	ID      int32       `db:"id" json:"id"`
	AssetID pgtype.UUID `db:"asset_id" json:"asset_id"`
	// Face identifier for tracking the same person across images
	FaceID *string `db:"face_id" json:"face_id"`
	// Face bounding box coordinates, format: {x, y, width, height}
	BoundingBox []byte `db:"bounding_box" json:"bounding_box"`
	// Face detection confidence score, between 0.0-1.0
	Confidence float32 `db:"confidence" json:"confidence"`
	// Predicted age group: child, teen, adult, senior
	AgeGroup *string `db:"age_group" json:"age_group"`
	// Predicted gender: male, female
	Gender *string `db:"gender" json:"gender"`
	// Predicted ethnicity group
	Ethnicity *string `db:"ethnicity" json:"ethnicity"`
	// Detected facial expression
	Expression *string `db:"expression" json:"expression"`
	// Approximate face size in pixels
	FaceSize      *int32  `db:"face_size" json:"face_size"`
	FaceImagePath *string `db:"face_image_path" json:"face_image_path"`
	// Face embedding vector for recognition and similarity matching
	Embedding      *pgvector.Vector `db:"embedding" json:"embedding"`
	EmbeddingModel *string          `db:"embedding_model" json:"embedding_model"`
	// Mark as the primary/most prominent face in the image
	IsPrimary *bool `db:"is_primary" json:"is_primary"`
	// Overall face quality score (0.0-1.0)
	QualityScore *float32 `db:"quality_score" json:"quality_score"`
	// Blur detection score (0.0-1.0, lower values indicate less blur)
	BlurScore *float32 `db:"blur_score" json:"blur_score"`
	// Head pose angles in degrees, format: {yaw, pitch, roll}
	PoseAngles []byte             `db:"pose_angles" json:"pose_angles"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Face detection results main table, storing face detection summary for each image
type FaceResult struct {
	AssetID pgtype.UUID `db:"asset_id" json:"asset_id"`
	// Face detection model identifier, such as "retinaface-v1", "mtcnn-v1", etc.
	ModelID string `db:"model_id" json:"model_id"`
	// Total number of detected faces in the image
	TotalFaces int32 `db:"total_faces" json:"total_faces"`
	// Face detection processing time in milliseconds
	ProcessingTimeMs *int32             `db:"processing_time_ms" json:"processing_time_ms"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type FileRecord struct {
	ID             int64              `db:"id" json:"id"`
	RepositoryID   pgtype.UUID        `db:"repository_id" json:"repository_id"`
	FilePath       string             `db:"file_path" json:"file_path"`
	FileSize       int64              `db:"file_size" json:"file_size"`
	ModTime        pgtype.Timestamptz `db:"mod_time" json:"mod_time"`
	ContentHash    *string            `db:"content_hash" json:"content_hash"`
	LastScanned    pgtype.Timestamptz `db:"last_scanned" json:"last_scanned"`
	ScanGeneration *int64             `db:"scan_generation" json:"scan_generation"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// OCR recognition results main table, storing OCR processing summary for each image
type OcrResult struct {
	AssetID pgtype.UUID `db:"asset_id" json:"asset_id"`
	// OCR model identifier, such as "paddleocr-v2", "easyocr-v1", etc.
	ModelID string `db:"model_id" json:"model_id"`
	// Total number of detected text regions
	TotalCount int32 `db:"total_count" json:"total_count"`
	// OCR processing time in milliseconds
	ProcessingTimeMs *int32             `db:"processing_time_ms" json:"processing_time_ms"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// OCR recognized text items table, storing detailed information for each text region
type OcrTextItem struct {
	ID      int32       `db:"id" json:"id"`
	AssetID pgtype.UUID `db:"asset_id" json:"asset_id"`
	// Recognized text content, supports multiple languages
	TextContent string `db:"text_content" json:"text_content"`
	// Recognition confidence score, between 0.0-1.0
	Confidence float32 `db:"confidence" json:"confidence"`
	// Polygon coordinates, format: [[x1,y1], [x2,y2], [x3,y3], [x4,y4]]
	BoundingBox []byte `db:"bounding_box" json:"bounding_box"`
	TextLength  int32  `db:"text_length" json:"text_length"`
	// Approximate area of text region, can be used to filter larger text
	AreaPixels *float32           `db:"area_pixels" json:"area_pixels"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RefreshToken struct {
	TokenID   int32              `db:"token_id" json:"token_id"`
	UserID    int32              `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	IsRevoked *bool              `db:"is_revoked" json:"is_revoked"`
}

type Repository struct {
	RepoID    pgtype.UUID              `db:"repo_id" json:"repo_id"`
	Name      string                   `db:"name" json:"name"`
	Path      string                   `db:"path" json:"path"`
	Config    repocfg.RepositoryConfig `db:"config" json:"config"`
	Status    dbtypes.RepoStatus       `db:"status" json:"status"`
	LastSync  pgtype.Timestamptz       `db:"last_sync" json:"last_sync"`
	CreatedAt pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
}

type SpeciesPrediction struct {
	AssetID pgtype.UUID `db:"asset_id" json:"asset_id"`
	Label   string      `db:"label" json:"label"`
	Score   float32     `db:"score" json:"score"`
}

type SyncOperation struct {
	ID            int64              `db:"id" json:"id"`
	RepositoryID  pgtype.UUID        `db:"repository_id" json:"repository_id"`
	OperationType string             `db:"operation_type" json:"operation_type"`
	FilesScanned  *int32             `db:"files_scanned" json:"files_scanned"`
	FilesAdded    *int32             `db:"files_added" json:"files_added"`
	FilesUpdated  *int32             `db:"files_updated" json:"files_updated"`
	FilesRemoved  *int32             `db:"files_removed" json:"files_removed"`
	StartTime     pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime       pgtype.Timestamptz `db:"end_time" json:"end_time"`
	DurationMs    *int64             `db:"duration_ms" json:"duration_ms"`
	Status        *string            `db:"status" json:"status"`
	ErrorMessage  *string            `db:"error_message" json:"error_message"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Tag struct {
	TagID         int32   `db:"tag_id" json:"tag_id"`
	TagName       string  `db:"tag_name" json:"tag_name"`
	Category      *string `db:"category" json:"category"`
	IsAiGenerated *bool   `db:"is_ai_generated" json:"is_ai_generated"`
}

type Thumbnail struct {
	ThumbnailID int32              `db:"thumbnail_id" json:"thumbnail_id"`
	AssetID     pgtype.UUID        `db:"asset_id" json:"asset_id"`
	Size        string             `db:"size" json:"size"`
	StoragePath string             `db:"storage_path" json:"storage_path"`
	MimeType    string             `db:"mime_type" json:"mime_type"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	UserID    int32              `db:"user_id" json:"user_id"`
	Username  string             `db:"username" json:"username"`
	Email     string             `db:"email" json:"email"`
	Password  string             `db:"password" json:"password"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	IsActive  *bool              `db:"is_active" json:"is_active"`
	LastLogin pgtype.Timestamptz `db:"last_login" json:"last_login"`
}
