// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
	"server/internal/db/dbtypes"
)

type Querier interface {
	AddAssetToAlbum(ctx context.Context, arg AddAssetToAlbumParams) error
	AddStackMember(ctx context.Context, arg AddStackMemberParams) error
	AddTagToAsset(ctx context.Context, arg AddTagToAssetParams) error
	AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error)
	// Capture times for a set of assets, for the sample tool's distribution
	// summary. Order is irrelevant; bucketing happens in Go.
	AgentCapturedTimes(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.Timestamptz, error)
	AgentFacetCameraCounts(ctx context.Context, arg AgentFacetCameraCountsParams) ([]AgentFacetCameraCountsRow, error)
	// Facet aggregates over a ref snapshot (agent describe tool / hydration API).
	// Every query takes the materialized asset id array; results feed
	// ref.FacetSummary. User-content strings (labels, names, camera models) are
	// sanitized in Go before reaching the LLM — never here.
	AgentFacetOverview(ctx context.Context, assetIds []pgtype.UUID) (AgentFacetOverviewRow, error)
	// Aesthetic-score distribution (percentiles) over a ref snapshot, for the
	// describe tool. Unscored assets are excluded from the percentiles;
	// scored_count lets callers report how many of the ref's assets carry a score.
	// Percentiles are NULL when nothing in the set is scored.
	AgentFacetQualityStats(ctx context.Context, assetIds []pgtype.UUID) (AgentFacetQualityStatsRow, error)
	AgentFacetRatingDist(ctx context.Context, assetIds []pgtype.UUID) ([]AgentFacetRatingDistRow, error)
	// granularity is 'hour', 'day', 'month' or 'year'.
	AgentFacetTimeHistogram(ctx context.Context, arg AgentFacetTimeHistogramParams) ([]AgentFacetTimeHistogramRow, error)
	// Most-used focal lengths over a ref snapshot, rounded to whole millimetres so
	// 34.9mm and 35mm collapse into one bucket. The regex guards the numeric cast.
	AgentFacetTopFocalLengths(ctx context.Context, arg AgentFacetTopFocalLengthsParams) ([]AgentFacetTopFocalLengthsRow, error)
	AgentFacetTopLenses(ctx context.Context, arg AgentFacetTopLensesParams) ([]AgentFacetTopLensesRow, error)
	AgentFacetTopPeople(ctx context.Context, arg AgentFacetTopPeopleParams) ([]AgentFacetTopPeopleRow, error)
	AgentFacetTopPlaces(ctx context.Context, arg AgentFacetTopPlacesParams) ([]AgentFacetTopPlacesRow, error)
	AgentFacetTypeCounts(ctx context.Context, assetIds []pgtype.UUID) ([]AgentFacetTypeCountsRow, error)
	// inspect observer: per-asset EXIF facets for small refs.
	AgentInspectAssets(ctx context.Context, assetIds []pgtype.UUID) ([]AgentInspectAssetsRow, error)
	// lookup_albums entity resolver: albums matching a title query.
	AgentLookupAlbums(ctx context.Context, arg AgentLookupAlbumsParams) ([]AgentLookupAlbumsRow, error)
	// lookup_people entity resolver: named face clusters matching a name query.
	AgentLookupPeople(ctx context.Context, arg AgentLookupPeopleParams) ([]AgentLookupPeopleRow, error)
	// peek observer: minimal per-asset fields plus place + people; snapshot order
	// restored in Go. place/people are correlated subqueries so each asset stays a
	// single row (no fan-out from the cluster joins).
	AgentPeekAssets(ctx context.Context, assetIds []pgtype.UUID) ([]AgentPeekAssetsRow, error)
	// Applies merged rating/liked/description on top of the existing keeper values.
	// Rating uses MAX, liked is OR'd, description is set only when keeper currently
	// has no description (or the field is empty).
	ApplyMergedKeeperPreferences(ctx context.Context, arg ApplyMergedKeeperPreferencesParams) error
	AssignFaceClusterMemberExclusive(ctx context.Context, arg AssignFaceClusterMemberExclusiveParams) (FaceClusterMember, error)
	BulkToggleAssetLiked(ctx context.Context, assetIds []pgtype.UUID) error
	BulkUpdateAssetLiked(ctx context.Context, arg BulkUpdateAssetLikedParams) error
	BulkUpdateAssetRating(ctx context.Context, arg BulkUpdateAssetRatingParams) error
	BulkUpdateAssetStatus(ctx context.Context, arg BulkUpdateAssetStatusParams) error
	CancelRepositoryScanRun(ctx context.Context, arg CancelRepositoryScanRunParams) (RepositoryScanRun, error)
	CompleteRepositoryScanRun(ctx context.Context, arg CompleteRepositoryScanRunParams) (RepositoryScanRun, error)
	CopyFaceClusterMembersToCluster(ctx context.Context, arg CopyFaceClusterMembersToClusterParams) error
	CountActivePrimaryRepositories(ctx context.Context) (int64, error)
	CountActiveUsersByRole(ctx context.Context, role string) (int64, error)
	CountAlbumsByUserScoped(ctx context.Context, arg CountAlbumsByUserScopedParams) (int64, error)
	CountAssetsByRating(ctx context.Context, ownerID *int32) ([]CountAssetsByRatingRow, error)
	CountAssetsByStatus(ctx context.Context, status []byte) (int64, error)
	CountAssetsByStatusAndOwner(ctx context.Context, arg CountAssetsByStatusAndOwnerParams) (int64, error)
	CountAssetsByStatusAndRepository(ctx context.Context, arg CountAssetsByStatusAndRepositoryParams) (int64, error)
	// Count query matching GetAssetsUnified WHERE clause
	// Returns total count of assets matching the filters (for pagination)
	CountAssetsUnified(ctx context.Context, arg CountAssetsUnifiedParams) (int64, error)
	CountBioAlbumPhotoAssets(ctx context.Context, repositoryID pgtype.UUID) (int64, error)
	CountBioAlbumPhotoAssetsWithSpeciesPredictions(ctx context.Context, repositoryID pgtype.UUID) (int64, error)
	CountCollapsedBrowseItemsUnified(ctx context.Context, arg CountCollapsedBrowseItemsUnifiedParams) (int64, error)
	CountDuplicateGroups(ctx context.Context, arg CountDuplicateGroupsParams) (int64, error)
	CountEmbeddingsByType(ctx context.Context, embeddingType string) (int64, error)
	// DBSCAN core check runs over the whole owner scope: clusters span
	// repositories, so neighbors are never repository-filtered.
	CountIncrementalFaceNeighbors(ctx context.Context, arg CountIncrementalFaceNeighborsParams) (int64, error)
	CountLikedAssets(ctx context.Context, ownerID *int32) (int64, error)
	CountLocationClusters(ctx context.Context, arg CountLocationClustersParams) (int64, error)
	// owner_id filters on the cluster's structural owner (NULL-owner clusters are
	// admin-only); repository_id stays a member-asset display filter because
	// people legitimately span repositories.
	CountPeopleScoped(ctx context.Context, arg CountPeopleScopedParams) (int64, error)
	CountPersonFacesScoped(ctx context.Context, arg CountPersonFacesScopedParams) (int64, error)
	CountPhotoAssetsForIndexing(ctx context.Context, repositoryID pgtype.UUID) (int64, error)
	CountPhotoAssetsWithEmbeddingType(ctx context.Context, arg CountPhotoAssetsWithEmbeddingTypeParams) (int64, error)
	CountPhotoAssetsWithFaceResults(ctx context.Context, repositoryID pgtype.UUID) (int64, error)
	CountPhotoAssetsWithOCRResults(ctx context.Context, repositoryID pgtype.UUID) (int64, error)
	// Count query matching GetPhotoMapPoints.
	CountPhotoMapPoints(ctx context.Context, arg CountPhotoMapPointsParams) (int64, error)
	CountRepositories(ctx context.Context) (int64, error)
	CountRepositoriesByStatus(ctx context.Context, status dbtypes.RepoStatus) (int64, error)
	CountRepositoryCloudBindingsByCredential(ctx context.Context, credentialID pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAgentPin(ctx context.Context, arg CreateAgentPinParams) (AgentPin, error)
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateCloudCredential(ctx context.Context, arg CreateCloudCredentialParams) (CloudCredential, error)
	CreateCloudImportRun(ctx context.Context, arg CreateCloudImportRunParams) (CloudImportRun, error)
	CreateDuplicateGroup(ctx context.Context, arg CreateDuplicateGroupParams) (pgtype.UUID, error)
	// owner_id is the cluster's structural owner (rule: a cluster never spans
	// owners). NULL means the cluster groups ownerless assets and is admin-only.
	CreateFaceCluster(ctx context.Context, arg CreateFaceClusterParams) (FaceCluster, error)
	CreateFaceClusterMember(ctx context.Context, arg CreateFaceClusterMemberParams) (FaceClusterMember, error)
	CreateFaceItem(ctx context.Context, arg CreateFaceItemParams) (FaceItem, error)
	CreateFaceResult(ctx context.Context, arg CreateFaceResultParams) (FaceResult, error)
	CreateOCRResult(ctx context.Context, arg CreateOCRResultParams) (OcrResult, error)
	CreateOCRTextItem(ctx context.Context, arg CreateOCRTextItemParams) (OcrTextItem, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRegistrationSession(ctx context.Context, arg CreateRegistrationSessionParams) (RegistrationSession, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateRepositoryScanRun(ctx context.Context, arg CreateRepositoryScanRunParams) (RepositoryScanRun, error)
	CreateSpeciesPrediction(ctx context.Context, arg CreateSpeciesPredictionParams) (SpeciesPrediction, error)
	CreateStack(ctx context.Context) (AssetStack, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateThumbnail(ctx context.Context, arg CreateThumbnailParams) (Thumbnail, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserRecoveryCode(ctx context.Context, arg CreateUserRecoveryCodeParams) error
	CreateUserWebAuthnCredential(ctx context.Context, arg CreateUserWebAuthnCredentialParams) (UserWebauthnCredential, error)
	DeleteAgentPin(ctx context.Context, arg DeleteAgentPinParams) error
	DeleteAlbum(ctx context.Context, albumID int32) error
	DeleteAllEmbeddingsForAsset(ctx context.Context, assetID pgtype.UUID) error
	DeleteAsset(ctx context.Context, assetID pgtype.UUID) error
	DeleteCloudCredential(ctx context.Context, credentialID pgtype.UUID) error
	DeleteEmbedding(ctx context.Context, arg DeleteEmbeddingParams) error
	DeleteEmptyFaceClusters(ctx context.Context) error
	DeleteEmptyUnconfirmedFaceClusters(ctx context.Context) error
	DeleteExpiredRegistrationSessions(ctx context.Context) error
	DeleteFaceCluster(ctx context.Context, clusterID int32) error
	DeleteFaceClusterMember(ctx context.Context, arg DeleteFaceClusterMemberParams) error
	DeleteFaceClusterMembersByCluster(ctx context.Context, clusterID int32) error
	DeleteFaceClusterMembersForScope(ctx context.Context, arg DeleteFaceClusterMembersForScopeParams) error
	DeleteFaceItemsByAsset(ctx context.Context, assetID pgtype.UUID) error
	DeleteFaceResultByAsset(ctx context.Context, assetID pgtype.UUID) error
	DeleteLocationClustersForScope(ctx context.Context, arg DeleteLocationClustersForScopeParams) error
	DeleteOCRResultByAsset(ctx context.Context, assetID pgtype.UUID) error
	DeleteOCRTextItemsByAsset(ctx context.Context, assetID pgtype.UUID) error
	// ============================================================================
	// Duplicate group lifecycle
	// ============================================================================
	// Removes the pending detection state for a repository. Merged and dismissed
	// groups are preserved so the user retains an audit trail of resolved sets.
	DeletePendingDuplicateGroupsByRepository(ctx context.Context, repositoryID pgtype.UUID) error
	DeleteRegistrationSession(ctx context.Context, sessionID pgtype.UUID) error
	DeleteRegistrationSessionsByUsername(ctx context.Context, username string) error
	DeleteRepositories(ctx context.Context, dollar_1 []pgtype.UUID) error
	DeleteRepository(ctx context.Context, repoID pgtype.UUID) error
	DeleteSpeciesPredictionsByAsset(ctx context.Context, assetID pgtype.UUID) error
	DeleteStack(ctx context.Context, stackID pgtype.UUID) error
	DeleteTag(ctx context.Context, tagID int32) error
	DeleteUser(ctx context.Context, userID int32) error
	DeleteUserRecoveryCodes(ctx context.Context, userID int32) error
	DeleteUserTOTPCredential(ctx context.Context, userID int32) error
	DeleteUserWebAuthnCredential(ctx context.Context, arg DeleteUserWebAuthnCredentialParams) (int64, error)
	DeleteUserWebAuthnCredentials(ctx context.Context, userID int32) error
	DisableRepositoryCloudBindingsByCredential(ctx context.Context, credentialID pgtype.UUID) error
	FailRepositoryScanRun(ctx context.Context, arg FailRepositoryScanRunParams) (RepositoryScanRun, error)
	// Find all assets sharing the same base filename (without extension and without iteration suffix)
	FindAssetsByBaseName(ctx context.Context, arg FindAssetsByBaseNameParams) ([]FindAssetsByBaseNameRow, error)
	// Find assets in the same repository that share a base filename pattern
	// This is used for auto-detecting RAW+JPEG stacks
	FindCandidatesForStacking(ctx context.Context, repositoryID pgtype.UUID) ([]FindCandidatesForStackingRow, error)
	// Find assets that share base names but are not yet in any stack.
	// Includes taken_time and upload_time for time-based clustering, and
	// owner_id because auto-detected stacks never span owners.
	FindCandidatesForStackingByName(ctx context.Context, repositoryID pgtype.UUID) ([]FindCandidatesForStackingByNameRow, error)
	FinishCloudImportRun(ctx context.Context, arg FinishCloudImportRunParams) (CloudImportRun, error)
	GetActiveRepositoryCloudBinding(ctx context.Context, repositoryID pgtype.UUID) (RepositoryCloudBinding, error)
	GetAgentPin(ctx context.Context, arg GetAgentPinParams) (AgentPin, error)
	GetAlbumAssetCount(ctx context.Context, albumID int32) (int64, error)
	GetAlbumAssetCountScoped(ctx context.Context, arg GetAlbumAssetCountScopedParams) (int64, error)
	GetAlbumAssets(ctx context.Context, albumID int32) ([]GetAlbumAssetsRow, error)
	GetAlbumAssetsScoped(ctx context.Context, arg GetAlbumAssetsScopedParams) ([]GetAlbumAssetsScopedRow, error)
	GetAlbumByID(ctx context.Context, albumID int32) (Album, error)
	GetAlbumByIDScoped(ctx context.Context, arg GetAlbumByIDScopedParams) (GetAlbumByIDScopedRow, error)
	GetAlbumsByUser(ctx context.Context, arg GetAlbumsByUserParams) ([]Album, error)
	GetAlbumsByUserScoped(ctx context.Context, arg GetAlbumsByUserScopedParams) ([]GetAlbumsByUserScopedRow, error)
	GetAllEmbeddingsForAsset(ctx context.Context, assetID pgtype.UUID) ([]GetAllEmbeddingsForAssetRow, error)
	GetAllFaceClusters(ctx context.Context) ([]FaceCluster, error)
	GetAssetAlbums(ctx context.Context, assetID pgtype.UUID) ([]GetAssetAlbumsRow, error)
	GetAssetByHashAndRepository(ctx context.Context, arg GetAssetByHashAndRepositoryParams) (Asset, error)
	GetAssetByID(ctx context.Context, assetID pgtype.UUID) (Asset, error)
	GetAssetByIDAny(ctx context.Context, assetID pgtype.UUID) (Asset, error)
	GetAssetByRepositoryAndStoragePathAny(ctx context.Context, arg GetAssetByRepositoryAndStoragePathAnyParams) (Asset, error)
	GetAssetExifRaw(ctx context.Context, assetID pgtype.UUID) (json.RawMessage, error)
	// Queries backing the Phase 2 agent tools (producers, transformers,
	// observers). All ANY(asset_ids) queries operate on ref snapshots.
	// search_people producer: assets containing at least one of the given people
	// (union semantics; the agent intersects refs for "both people" requests).
	GetAssetIDsByPersonIDs(ctx context.Context, arg GetAssetIDsByPersonIDsParams) ([]pgtype.UUID, error)
	// ============================================================================
	// UNIFIED QUERY API
	// These queries consolidate List, Filter, and Search operations with shared WHERE logic
	// ============================================================================
	// Agent ref materialization: same filter semantics as GetAssetsUnified but
	// returns ordered asset ids only (capture time desc). The limit is the ref
	// snapshot cap; callers detect truncation by requesting cap+1.
	GetAssetIDsUnified(ctx context.Context, arg GetAssetIDsUnifiedParams) ([]pgtype.UUID, error)
	GetAssetQualityScore(ctx context.Context, assetID pgtype.UUID) (AssetQualityScore, error)
	GetAssetStatsForOwner(ctx context.Context, ownerID int32) (GetAssetStatsForOwnerRow, error)
	GetAssetWithRelations(ctx context.Context, assetID pgtype.UUID) (GetAssetWithRelationsRow, error)
	GetAssetWithTags(ctx context.Context, assetID pgtype.UUID) (GetAssetWithTagsRow, error)
	GetAssetWithThumbnails(ctx context.Context, assetID pgtype.UUID) (GetAssetWithThumbnailsRow, error)
	GetAssetsByHash(ctx context.Context, hash *string) ([]Asset, error)
	GetAssetsByIDs(ctx context.Context, assetIds []pgtype.UUID) ([]Asset, error)
	GetAssetsByIDsAny(ctx context.Context, assetIds []pgtype.UUID) ([]Asset, error)
	GetAssetsByOwner(ctx context.Context, arg GetAssetsByOwnerParams) ([]Asset, error)
	GetAssetsByOwnerAndTypesSorted(ctx context.Context, arg GetAssetsByOwnerAndTypesSortedParams) ([]Asset, error)
	GetAssetsByOwnerSorted(ctx context.Context, arg GetAssetsByOwnerSortedParams) ([]Asset, error)
	GetAssetsByOwnerWithRatingLiked(ctx context.Context, arg GetAssetsByOwnerWithRatingLikedParams) ([]Asset, error)
	GetAssetsByRating(ctx context.Context, arg GetAssetsByRatingParams) ([]Asset, error)
	GetAssetsByRatingAndType(ctx context.Context, arg GetAssetsByRatingAndTypeParams) ([]Asset, error)
	GetAssetsByRatingRange(ctx context.Context, arg GetAssetsByRatingRangeParams) ([]Asset, error)
	GetAssetsByStatus(ctx context.Context, arg GetAssetsByStatusParams) ([]Asset, error)
	GetAssetsByStatusAndOwner(ctx context.Context, arg GetAssetsByStatusAndOwnerParams) ([]Asset, error)
	GetAssetsByStatusAndRepository(ctx context.Context, arg GetAssetsByStatusAndRepositoryParams) ([]Asset, error)
	GetAssetsByType(ctx context.Context, arg GetAssetsByTypeParams) ([]Asset, error)
	GetAssetsByTypesSorted(ctx context.Context, arg GetAssetsByTypesSortedParams) ([]Asset, error)
	// Handles: listing, filename search, and all filtering
	// Use this for most queries unless semantic search is needed
	GetAssetsUnified(ctx context.Context, arg GetAssetsUnifiedParams) ([]Asset, error)
	GetAssetsWithErrors(ctx context.Context, arg GetAssetsWithErrorsParams) ([]Asset, error)
	GetAssetsWithWarnings(ctx context.Context, arg GetAssetsWithWarningsParams) ([]Asset, error)
	// 获取所有有照片的年份列表
	GetAvailableYears(ctx context.Context, repositoryID pgtype.UUID) ([]int32, error)
	// 获取相机+镜头组合统计
	GetCameraLensStats(ctx context.Context, arg GetCameraLensStatsParams) ([]GetCameraLensStatsRow, error)
	GetCheckpoint(ctx context.Context, id string) ([]byte, error)
	GetCloudCredential(ctx context.Context, credentialID pgtype.UUID) (CloudCredential, error)
	GetCloudCredentialByIdentity(ctx context.Context, arg GetCloudCredentialByIdentityParams) (CloudCredential, error)
	GetCloudImportRun(ctx context.Context, runID pgtype.UUID) (CloudImportRun, error)
	GetCloudSyncCursor(ctx context.Context, arg GetCloudSyncCursorParams) (string, error)
	GetCloudSyncFile(ctx context.Context, arg GetCloudSyncFileParams) (GetCloudSyncFileRow, error)
	// Merge suggestions never pair clusters of different owners; owner_id
	// optionally restricts candidates to one owner's clusters (nil = admin).
	GetClusterMergeCandidates(ctx context.Context, arg GetClusterMergeCandidatesParams) ([]GetClusterMergeCandidatesRow, error)
	GetCollapsedBrowseItemsUnified(ctx context.Context, arg GetCollapsedBrowseItemsUnifiedParams) ([]GetCollapsedBrowseItemsUnifiedRow, error)
	GetConfirmedFaceClusters(ctx context.Context) ([]FaceCluster, error)
	// 获取每日拍摄活跃度热力图数据
	GetDailyActivityHeatmap(ctx context.Context, arg GetDailyActivityHeatmapParams) ([]GetDailyActivityHeatmapRow, error)
	GetDefaultEmbeddingSpaceByType(ctx context.Context, embeddingType string) (EmbeddingSpace, error)
	GetDistinctCameraModels(ctx context.Context) ([]interface{}, error)
	GetDistinctLenses(ctx context.Context) ([]interface{}, error)
	GetDuplicateGroupAssets(ctx context.Context, groupID pgtype.UUID) ([]DuplicateGroupAsset, error)
	// Bulk variant used for the list endpoint to enrich many groups in one query.
	GetDuplicateGroupAssetsBatch(ctx context.Context, groupIds []pgtype.UUID) ([]DuplicateGroupAsset, error)
	GetDuplicateGroupByID(ctx context.Context, groupID pgtype.UUID) (DuplicateGroup, error)
	GetDuplicateGroupEdges(ctx context.Context, groupID pgtype.UUID) ([]DuplicateGroupEdge, error)
	// Top-level metrics for the Utilities rail card.
	GetDuplicateSummary(ctx context.Context, arg GetDuplicateSummaryParams) (GetDuplicateSummaryRow, error)
	GetEmbedding(ctx context.Context, arg GetEmbeddingParams) (GetEmbeddingRow, error)
	GetEmbeddingByType(ctx context.Context, arg GetEmbeddingByTypeParams) (GetEmbeddingByTypeRow, error)
	GetEmbeddingModels(ctx context.Context, embeddingType string) ([]GetEmbeddingModelsRow, error)
	GetEmbeddingSpaceByAttributes(ctx context.Context, arg GetEmbeddingSpaceByAttributesParams) (EmbeddingSpace, error)
	// Returns assets in a repository that share the exact same (hash, file_size)
	// with at least one other asset of the same owner. Only photos are considered,
	// and only non-deleted assets. Results are ordered so members of the same
	// duplicate set (owner included in the grouping key) are adjacent.
	GetExactDuplicateCandidates(ctx context.Context, repositoryID pgtype.UUID) ([]GetExactDuplicateCandidatesRow, error)
	GetFaceClusterAssignmentsForScope(ctx context.Context, arg GetFaceClusterAssignmentsForScopeParams) ([]GetFaceClusterAssignmentsForScopeRow, error)
	GetFaceClusterByFaceID(ctx context.Context, faceID int32) (FaceCluster, error)
	GetFaceClusterByID(ctx context.Context, clusterID int32) (FaceCluster, error)
	GetFaceClusterByRepresentative(ctx context.Context, representativeFaceID *int32) (FaceCluster, error)
	GetFaceClusterMembers(ctx context.Context, clusterID int32) ([]GetFaceClusterMembersRow, error)
	GetFaceClusterMembershipsByFaceIDs(ctx context.Context, faceIds []int32) ([]GetFaceClusterMembershipsByFaceIDsRow, error)
	GetFaceClusteringCandidates(ctx context.Context, arg GetFaceClusteringCandidatesParams) ([]GetFaceClusteringCandidatesRow, error)
	GetFaceDemographics(ctx context.Context, confidence float32) ([]GetFaceDemographicsRow, error)
	GetFaceEmbeddingsForClustering(ctx context.Context, arg GetFaceEmbeddingsForClusteringParams) ([]GetFaceEmbeddingsForClusteringRow, error)
	GetFaceForCorrectionScoped(ctx context.Context, arg GetFaceForCorrectionScopedParams) (GetFaceForCorrectionScopedRow, error)
	GetFaceItemByID(ctx context.Context, id int32) (FaceItem, error)
	GetFaceItemsByAsset(ctx context.Context, assetID pgtype.UUID) ([]FaceItem, error)
	GetFaceItemsByAssetWithLimit(ctx context.Context, arg GetFaceItemsByAssetWithLimitParams) ([]FaceItem, error)
	GetFaceResultByAsset(ctx context.Context, assetID pgtype.UUID) (FaceResult, error)
	GetFaceStatsByAsset(ctx context.Context, assetID pgtype.UUID) (GetFaceStatsByAssetRow, error)
	GetFaceStatsByModel(ctx context.Context) ([]GetFaceStatsByModelRow, error)
	GetFacesByExpression(ctx context.Context, arg GetFacesByExpressionParams) ([]FaceItem, error)
	// 获取焦距分布统计
	GetFocalLengthDistribution(ctx context.Context, repositoryID pgtype.UUID) ([]GetFocalLengthDistributionRow, error)
	// Folder browsing has no dedicated table: "folders" are derived from the
	// repository-relative prefix of assets.storage_path. All queries here treat
	// storage_path as relative (see assets_repository_id_storage_path_key) and
	// must never expose repositories.path (the absolute host path).
	// Lists immediate child folders of parent_path (recursive descendant
	// counts/covers). Excludes internal .lumilio paths, app-managed inbox
	// uploads, and any asset that sits directly in parent_path (files, not
	// folders).
	GetFolderChildSummaries(ctx context.Context, arg GetFolderChildSummariesParams) ([]GetFolderChildSummariesRow, error)
	// Aggregate stats for one folder path (recursive descendants), used for the
	// folder detail header/hero.
	GetFolderSummary(ctx context.Context, arg GetFolderSummaryParams) (GetFolderSummaryRow, error)
	GetHighConfidenceTextItems(ctx context.Context, arg GetHighConfidenceTextItemsParams) ([]OcrTextItem, error)
	GetLatestRepositoryScanRun(ctx context.Context, repositoryID pgtype.UUID) (RepositoryScanRun, error)
	GetLikedAssets(ctx context.Context, arg GetLikedAssetsParams) ([]Asset, error)
	GetLikedAssetsByOwner(ctx context.Context, arg GetLikedAssetsByOwnerParams) ([]Asset, error)
	GetLikedAssetsByType(ctx context.Context, arg GetLikedAssetsByTypeParams) ([]Asset, error)
	GetManualFaceClusterMembershipsForScope(ctx context.Context, arg GetManualFaceClusterMembershipsForScopeParams) ([]GetManualFaceClusterMembershipsForScopeRow, error)
	// Cluster attachment is owner-scoped only: a face may join a cluster whose
	// members live in a different repository, same owner.
	GetNearestAssignedFaceCluster(ctx context.Context, arg GetNearestAssignedFaceClusterParams) (GetNearestAssignedFaceClusterRow, error)
	GetOCRResultByAsset(ctx context.Context, assetID pgtype.UUID) (OcrResult, error)
	GetOCRStatsByModel(ctx context.Context) ([]GetOCRStatsByModelRow, error)
	GetOCRTextItemStatsByAsset(ctx context.Context, assetID pgtype.UUID) (GetOCRTextItemStatsByAssetRow, error)
	GetOCRTextItemsByAsset(ctx context.Context, assetID pgtype.UUID) ([]OcrTextItem, error)
	GetOCRTextItemsByAssetWithLimit(ctx context.Context, arg GetOCRTextItemsByAssetWithLimitParams) ([]OcrTextItem, error)
	// Ref-scoped variant of ListPHashEmbeddingsForRepository: pHash embeddings for
	// a specific asset set, for the agent dedupe tool's in-memory similarity graph.
	GetPHashEmbeddingsByAssetIDs(ctx context.Context, assetIds []pgtype.UUID) ([]GetPHashEmbeddingsByAssetIDsRow, error)
	// Authorization is an equality check on the cluster's structural owner;
	// repository_id remains a read-time display filter on member counts/covers.
	GetPersonByIDScoped(ctx context.Context, arg GetPersonByIDScopedParams) (GetPersonByIDScopedRow, error)
	GetPersonFaceScoped(ctx context.Context, arg GetPersonFaceScopedParams) (GetPersonFaceScopedRow, error)
	// Lightweight photo locations for map clustering/rendering.
	GetPhotoMapPoints(ctx context.Context, arg GetPhotoMapPointsParams) ([]GetPhotoMapPointsRow, error)
	GetPrimaryEmbedding(ctx context.Context, arg GetPrimaryEmbeddingParams) (GetPrimaryEmbeddingRow, error)
	GetPrimaryFaces(ctx context.Context, arg GetPrimaryFacesParams) ([]FaceItem, error)
	GetPrimaryRepository(ctx context.Context) (Repository, error)
	GetRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error)
	GetRegistrationSessionByID(ctx context.Context, sessionID pgtype.UUID) (RegistrationSession, error)
	GetRepository(ctx context.Context, repoID pgtype.UUID) (Repository, error)
	// Repository Asset Statistics (kept for repository management)
	GetRepositoryAssetStats(ctx context.Context, arg GetRepositoryAssetStatsParams) (GetRepositoryAssetStatsRow, error)
	GetRepositoryByPath(ctx context.Context, path string) (Repository, error)
	GetRepositoryCloudBinding(ctx context.Context, arg GetRepositoryCloudBindingParams) (RepositoryCloudBinding, error)
	GetRepositoryDefaults(ctx context.Context) (RepositoryDefault, error)
	GetRepositoryScanRun(ctx context.Context, scanID pgtype.UUID) (RepositoryScanRun, error)
	GetReverseGeocodeCache(ctx context.Context, arg GetReverseGeocodeCacheParams) (ReverseGeocodeCache, error)
	GetSettings(ctx context.Context) (Setting, error)
	GetSimilarFaces(ctx context.Context, arg GetSimilarFacesParams) ([]GetSimilarFacesRow, error)
	GetSpeciesPredictionsByAsset(ctx context.Context, assetID pgtype.UUID) ([]SpeciesPrediction, error)
	GetSpeciesPredictionsByLabel(ctx context.Context, arg GetSpeciesPredictionsByLabelParams) ([]SpeciesPrediction, error)
	GetSpeciesStats(ctx context.Context) (GetSpeciesStatsRow, error)
	GetStackByAssetID(ctx context.Context, assetID pgtype.UUID) (GetStackByAssetIDRow, error)
	GetStackByID(ctx context.Context, stackID pgtype.UUID) (AssetStack, error)
	GetStackMemberCount(ctx context.Context, arg GetStackMemberCountParams) (int64, error)
	GetStackMemberCountAny(ctx context.Context, arg GetStackMemberCountAnyParams) (int64, error)
	// owner_id restricts the member list to assets the caller may see (nil = admin).
	GetStackMembers(ctx context.Context, arg GetStackMembersParams) ([]AssetStackMember, error)
	// owner_id restricts the member list to assets the caller may see (nil = admin).
	GetStackMembersAny(ctx context.Context, arg GetStackMembersAnyParams) ([]AssetStackMember, error)
	// ============================================================================
	// Duplicate detection candidate queries
	// ============================================================================
	// Each stacked asset in the repository mapped to its stack. Used to skip
	// duplicate edges between intentional stack members (e.g. bursts, RAW+JPEG).
	GetStackMembershipForRepository(ctx context.Context, repositoryID pgtype.UUID) ([]GetStackMembershipForRepositoryRow, error)
	GetStacksByAssetIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetStacksByAssetIDsRow, error)
	GetSystemState(ctx context.Context) (SystemState, error)
	GetTagByID(ctx context.Context, tagID int32) (Tag, error)
	GetTagByName(ctx context.Context, tagName string) (Tag, error)
	// Browsable tag vocabulary with counts/cover, distinct from
	// SearchTagsByName (definition-only autocomplete). Groups by (tag_id,
	// source) because the same tag_id can carry manual assignments on some
	// assets and AI/system assignments on others.
	GetTagSummaries(ctx context.Context, arg GetTagSummariesParams) ([]GetTagSummariesRow, error)
	GetTagsByCategory(ctx context.Context, category *string) ([]Tag, error)
	GetThumbnailByAssetAndSize(ctx context.Context, arg GetThumbnailByAssetAndSizeParams) (Thumbnail, error)
	GetThumbnailByID(ctx context.Context, thumbnailID int32) (Thumbnail, error)
	GetThumbnailsByAsset(ctx context.Context, assetID pgtype.UUID) ([]Thumbnail, error)
	// 获取按小时的拍摄时间分布
	GetTimeDistributionHourly(ctx context.Context, repositoryID pgtype.UUID) ([]GetTimeDistributionHourlyRow, error)
	// 获取按月的拍摄时间分布
	GetTimeDistributionMonthly(ctx context.Context, repositoryID pgtype.UUID) ([]GetTimeDistributionMonthlyRow, error)
	GetTopFacesByQuality(ctx context.Context, arg GetTopFacesByQualityParams) ([]FaceItem, error)
	GetTopRatedAssets(ctx context.Context, arg GetTopRatedAssetsParams) ([]Asset, error)
	GetTopSpeciesForAsset(ctx context.Context, arg GetTopSpeciesForAssetParams) ([]SpeciesPrediction, error)
	GetTopSpeciesLabels(ctx context.Context, limit int32) ([]GetTopSpeciesLabelsRow, error)
	GetUnclusteredFaces(ctx context.Context, arg GetUnclusteredFacesParams) ([]FaceItem, error)
	// repository_id is a face *selection* filter (which faces get processed),
	// not part of cluster identity — clusters span repositories, never owners.
	GetUnclusteredFacesInScope(ctx context.Context, arg GetUnclusteredFacesInScopeParams) ([]FaceItem, error)
	GetUserByID(ctx context.Context, userID int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserMFAStatus(ctx context.Context, userID int32) (GetUserMFAStatusRow, error)
	GetUserTOTPCredential(ctx context.Context, userID int32) (UserMfaTotpCredential, error)
	IncrementCloudImportRunCounts(ctx context.Context, arg IncrementCloudImportRunCountsParams) (CloudImportRun, error)
	InsertDuplicateGroupAsset(ctx context.Context, arg InsertDuplicateGroupAssetParams) error
	// Stores pair-level evidence. Callers must order endpoints so asset_id_a < asset_id_b.
	InsertDuplicateGroupEdge(ctx context.Context, arg InsertDuplicateGroupEdgeParams) error
	InsertLocationClusterAssetsForScope(ctx context.Context, arg InsertLocationClusterAssetsForScopeParams) error
	InsertLocationClustersForScope(ctx context.Context, arg InsertLocationClustersForScopeParams) ([]LocationCluster, error)
	ListActiveRepositories(ctx context.Context) ([]Repository, error)
	ListAgentPins(ctx context.Context, userID int32) ([]AgentPin, error)
	ListAssetEmbeddings(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListAssetEmbeddingsRow, error)
	ListAssetsByRepositoryAny(ctx context.Context, repositoryID pgtype.UUID) ([]Asset, error)
	ListBioAlbumAssetsMissingSpeciesPredictions(ctx context.Context, albumID int32) ([]Asset, error)
	ListCloudCredentials(ctx context.Context) ([]CloudCredential, error)
	ListCloudImportRunsForRepository(ctx context.Context, arg ListCloudImportRunsForRepositoryParams) ([]CloudImportRun, error)
	// Paginated list of duplicate groups for the given repository, owner, and
	// status. owner_id NULL means no owner scope (admin); non-admin callers pass
	// their own ID and never see NULL-owner or foreign groups.
	// Pending groups are returned newest-first; resolved groups by resolution time.
	ListDuplicateGroups(ctx context.Context, arg ListDuplicateGroupsParams) ([]DuplicateGroup, error)
	ListLocationClusters(ctx context.Context, arg ListLocationClustersParams) ([]LocationCluster, error)
	// Loads pHash embeddings for every non-deleted photo in a repository so the
	// service layer can build a similarity graph in-memory. owner_id is included
	// because duplicate edges never cross owners.
	ListPHashEmbeddingsForRepository(ctx context.Context, repositoryID pgtype.UUID) ([]ListPHashEmbeddingsForRepositoryRow, error)
	ListPendingLocationClusters(ctx context.Context, arg ListPendingLocationClustersParams) ([]LocationCluster, error)
	ListPeopleScoped(ctx context.Context, arg ListPeopleScopedParams) ([]ListPeopleScopedRow, error)
	ListPersonFacesScoped(ctx context.Context, arg ListPersonFacesScopedParams) ([]ListPersonFacesScopedRow, error)
	ListPhotoAssetsForIndexingBatch(ctx context.Context, arg ListPhotoAssetsForIndexingBatchParams) ([]Asset, error)
	ListPhotoAssetsMissingEmbeddingType(ctx context.Context, arg ListPhotoAssetsMissingEmbeddingTypeParams) ([]Asset, error)
	ListPhotoAssetsMissingFaceResults(ctx context.Context, arg ListPhotoAssetsMissingFaceResultsParams) ([]Asset, error)
	ListPhotoAssetsMissingOCRResults(ctx context.Context, arg ListPhotoAssetsMissingOCRResultsParams) ([]Asset, error)
	ListRepositories(ctx context.Context) ([]Repository, error)
	ListRepositoryCloudBindings(ctx context.Context, repositoryID pgtype.UUID) ([]RepositoryCloudBinding, error)
	ListRepositoryScanRuns(ctx context.Context, arg ListRepositoryScanRunsParams) ([]RepositoryScanRun, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	ListUserWebAuthnCredentialSummaries(ctx context.Context, userID int32) ([]ListUserWebAuthnCredentialSummariesRow, error)
	ListUserWebAuthnCredentials(ctx context.Context, userID int32) ([]UserWebauthnCredential, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersWithStats(ctx context.Context, arg ListUsersWithStatsParams) ([]ListUsersWithStatsRow, error)
	MarkCloudImportRunStarted(ctx context.Context, runID pgtype.UUID) (CloudImportRun, error)
	MarkCloudSyncFile(ctx context.Context, arg MarkCloudSyncFileParams) error
	MarkDuplicateGroupDismissed(ctx context.Context, groupID pgtype.UUID) error
	MarkDuplicateGroupMerged(ctx context.Context, arg MarkDuplicateGroupMergedParams) error
	MarkLocationClustersGeocodeDisabled(ctx context.Context, arg MarkLocationClustersGeocodeDisabledParams) error
	MarkStaleCloudImportRunsInterrupted(ctx context.Context) error
	// ============================================================================
	// Metadata merge helpers (used inside merge transactions)
	// ============================================================================
	// Copies a duplicate asset's album memberships onto the keeper asset.
	// Existing keeper memberships are preserved (the conflict clause is a no-op).
	MergeAlbumAssetsForDuplicate(ctx context.Context, arg MergeAlbumAssetsForDuplicateParams) error
	// Copies duplicate tags onto the keeper, choosing the higher confidence and
	// preferring user-provided tags over AI-generated ones on conflict.
	MergeAssetTagsForDuplicate(ctx context.Context, arg MergeAssetTagsForDuplicateParams) error
	MergeFaceClusters(ctx context.Context, arg MergeFaceClustersParams) error
	// Re-parents the duplicate asset's face_items onto the keeper so cluster
	// memberships (and thus person assignments) follow the keeper after merge.
	// Used only for exact duplicates where bounding boxes match by construction.
	MergeFaceClustersForDuplicate(ctx context.Context, arg MergeFaceClustersForDuplicateParams) error
	MoveAssetWithinRepository(ctx context.Context, arg MoveAssetWithinRepositoryParams) (Asset, error)
	MoveClusterMembersToClusterManual(ctx context.Context, arg MoveClusterMembersToClusterManualParams) error
	PromoteEmbeddingSpaceAsDefaultIfNone(ctx context.Context, arg PromoteEmbeddingSpaceAsDefaultIfNoneParams) (EmbeddingSpace, error)
	// rank(by=quality) ascending, using the aesthetic score from the SigLIP MLP
	// head when available, falling back to the legacy heuristic (rating, liked,
	// resolution) for unscored assets. Callers reverse for descending order.
	RankAssetIDsByQuality(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.UUID, error)
	// rank(by=time) ascending; callers reverse for descending order.
	RankAssetIDsByTime(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.UUID, error)
	// "recently added" presentation order, ascending; callers reverse for newest first.
	RankAssetIDsByUploadTime(ctx context.Context, assetIds []pgtype.UUID) ([]pgtype.UUID, error)
	ReclaimInterruptedRepositoryScanRuns(ctx context.Context) (int64, error)
	RemoveAssetFromAlbum(ctx context.Context, arg RemoveAssetFromAlbumParams) error
	RemoveAssetTagsBySources(ctx context.Context, arg RemoveAssetTagsBySourcesParams) error
	RemoveStackMember(ctx context.Context, assetID pgtype.UUID) error
	RemoveTagFromAsset(ctx context.Context, arg RemoveTagFromAssetParams) error
	RenameFaceCluster(ctx context.Context, arg RenameFaceClusterParams) (FaceCluster, error)
	RepositoryExists(ctx context.Context, path string) (bool, error)
	ResetAssetStatusForRetry(ctx context.Context, assetID pgtype.UUID) (Asset, error)
	RestoreAsset(ctx context.Context, assetID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenID int32) error
	RevokeUserRefreshTokens(ctx context.Context, userID int32) error
	SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]Asset, error)
	SearchAssetsByFaceCluster(ctx context.Context, arg SearchAssetsByFaceClusterParams) ([]Asset, error)
	SearchAssetsByFaceID(ctx context.Context, arg SearchAssetsByFaceIDParams) ([]Asset, error)
	SearchAssetsBySpecies(ctx context.Context, arg SearchAssetsBySpeciesParams) ([]Asset, error)
	SearchTagsByName(ctx context.Context, arg SearchTagsByNameParams) ([]Tag, error)
	SetBootstrapPhase(ctx context.Context, bootstrapPhase string) (SystemState, error)
	SetFaceClusterHidden(ctx context.Context, arg SetFaceClusterHiddenParams) (FaceCluster, error)
	SetPrimaryEmbedding(ctx context.Context, arg SetPrimaryEmbeddingParams) error
	SetPrimaryEmbeddingForAsset(ctx context.Context, arg SetPrimaryEmbeddingForAssetParams) error
	SetPrimaryRepositoryOwner(ctx context.Context, defaultOwnerID *int32) (Repository, error)
	SoftDeleteAssetByRepositoryAndStoragePath(ctx context.Context, arg SoftDeleteAssetByRepositoryAndStoragePathParams) (int64, error)
	UpdateAgentPinLayout(ctx context.Context, arg UpdateAgentPinLayoutParams) error
	UpdateAgentPinTitle(ctx context.Context, arg UpdateAgentPinTitleParams) error
	UpdateAgentPinWidget(ctx context.Context, arg UpdateAgentPinWidgetParams) error
	UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error)
	UpdateAssetDescription(ctx context.Context, arg UpdateAssetDescriptionParams) error
	UpdateAssetDimensions(ctx context.Context, arg UpdateAssetDimensionsParams) error
	UpdateAssetDuration(ctx context.Context, arg UpdateAssetDurationParams) error
	UpdateAssetLike(ctx context.Context, arg UpdateAssetLikeParams) error
	UpdateAssetMetadata(ctx context.Context, arg UpdateAssetMetadataParams) error
	UpdateAssetMetadataWithTakenTime(ctx context.Context, arg UpdateAssetMetadataWithTakenTimeParams) error
	UpdateAssetPositionInAlbum(ctx context.Context, arg UpdateAssetPositionInAlbumParams) error
	UpdateAssetRating(ctx context.Context, arg UpdateAssetRatingParams) error
	UpdateAssetRatingAndLike(ctx context.Context, arg UpdateAssetRatingAndLikeParams) error
	UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (Asset, error)
	UpdateAssetStatusWithErrors(ctx context.Context, arg UpdateAssetStatusWithErrorsParams) (Asset, error)
	UpdateAssetStoragePathAndStatus(ctx context.Context, arg UpdateAssetStoragePathAndStatusParams) (Asset, error)
	UpdateCloudCredentialAuthState(ctx context.Context, arg UpdateCloudCredentialAuthStateParams) (CloudCredential, error)
	UpdateCloudCredentialStatus(ctx context.Context, arg UpdateCloudCredentialStatusParams) (CloudCredential, error)
	UpdateDiscoveredAssetByID(ctx context.Context, arg UpdateDiscoveredAssetByIDParams) (Asset, error)
	// Resets all asset roles in a group, then flags the chosen keeper.
	UpdateDuplicateGroupKeeperRole(ctx context.Context, arg UpdateDuplicateGroupKeeperRoleParams) error
	UpdateFaceCluster(ctx context.Context, arg UpdateFaceClusterParams) (FaceCluster, error)
	UpdateFaceClusterRepresentative(ctx context.Context, arg UpdateFaceClusterRepresentativeParams) (FaceCluster, error)
	UpdateFaceItemEmbedding(ctx context.Context, arg UpdateFaceItemEmbeddingParams) (FaceItem, error)
	UpdateFaceResultStats(ctx context.Context, assetID pgtype.UUID) error
	UpdateLocationClusterGeocode(ctx context.Context, arg UpdateLocationClusterGeocodeParams) error
	UpdateOCRFullText(ctx context.Context, arg UpdateOCRFullTextParams) error
	UpdateOCRResultStats(ctx context.Context, assetID pgtype.UUID) error
	UpdateRegistrationSessionTOTPSecret(ctx context.Context, arg UpdateRegistrationSessionTOTPSecretParams) (RegistrationSession, error)
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error)
	UpdateRepositoryCloudBindingLastRun(ctx context.Context, arg UpdateRepositoryCloudBindingLastRunParams) (RepositoryCloudBinding, error)
	UpdateRepositoryLastSync(ctx context.Context, arg UpdateRepositoryLastSyncParams) (Repository, error)
	UpdateRepositoryStatus(ctx context.Context, arg UpdateRepositoryStatusParams) (Repository, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserTOTPLastUsed(ctx context.Context, userID int32) error
	UpdateUserWebAuthnCredentialUsage(ctx context.Context, arg UpdateUserWebAuthnCredentialUsageParams) (UserWebauthnCredential, error)
	// Asset quality scores: per-asset aesthetic score from MLP head on SigLIP.
	UpsertAssetQualityScore(ctx context.Context, arg UpsertAssetQualityScoreParams) (AssetQualityScore, error)
	UpsertCheckpoint(ctx context.Context, arg UpsertCheckpointParams) error
	UpsertCloudSyncCursor(ctx context.Context, arg UpsertCloudSyncCursorParams) error
	// Unified embeddings table queries
	UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error
	// Embedding spaces
	UpsertEmbeddingSpace(ctx context.Context, arg UpsertEmbeddingSpaceParams) (EmbeddingSpace, error)
	UpsertRepositoryCloudBinding(ctx context.Context, arg UpsertRepositoryCloudBindingParams) (RepositoryCloudBinding, error)
	UpsertRepositoryDefaults(ctx context.Context, arg UpsertRepositoryDefaultsParams) (RepositoryDefault, error)
	UpsertReverseGeocodeCache(ctx context.Context, arg UpsertReverseGeocodeCacheParams) (ReverseGeocodeCache, error)
	UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error)
	UpsertUserTOTPCredential(ctx context.Context, arg UpsertUserTOTPCredentialParams) (UserMfaTotpCredential, error)
	UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
