// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: repository_roots.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"server/internal/db/dbtypes"
)

const deleteExternalRepositoryRoot = `-- name: DeleteExternalRepositoryRoot :execrows
DELETE FROM repository_roots
WHERE repository_roots.root_id = $1
  AND repository_roots.kind = 'external'
  AND NOT EXISTS (
      SELECT 1 FROM repositories WHERE repositories.root_id = repository_roots.root_id
  )
`

func (q *Queries) DeleteExternalRepositoryRoot(ctx context.Context, rootID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExternalRepositoryRoot, rootID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDefaultRepositoryRoot = `-- name: GetDefaultRepositoryRoot :one
SELECT root_id, name, path, kind, status, created_at, updated_at FROM repository_roots
WHERE kind = 'default'
`

func (q *Queries) GetDefaultRepositoryRoot(ctx context.Context) (RepositoryRoot, error) {
	row := q.db.QueryRow(ctx, getDefaultRepositoryRoot)
	var i RepositoryRoot
	err := row.Scan(
		&i.RootID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryRoot = `-- name: GetRepositoryRoot :one
SELECT root_id, name, path, kind, status, created_at, updated_at FROM repository_roots
WHERE root_id = $1
`

func (q *Queries) GetRepositoryRoot(ctx context.Context, rootID pgtype.UUID) (RepositoryRoot, error) {
	row := q.db.QueryRow(ctx, getRepositoryRoot, rootID)
	var i RepositoryRoot
	err := row.Scan(
		&i.RootID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryRootByPath = `-- name: GetRepositoryRootByPath :one
SELECT root_id, name, path, kind, status, created_at, updated_at FROM repository_roots
WHERE path = $1
`

func (q *Queries) GetRepositoryRootByPath(ctx context.Context, path string) (RepositoryRoot, error) {
	row := q.db.QueryRow(ctx, getRepositoryRootByPath, path)
	var i RepositoryRoot
	err := row.Scan(
		&i.RootID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositoryRoots = `-- name: ListRepositoryRoots :many
SELECT root_id, name, path, kind, status, created_at, updated_at FROM repository_roots
ORDER BY kind ASC, created_at ASC
`

func (q *Queries) ListRepositoryRoots(ctx context.Context) ([]RepositoryRoot, error) {
	rows, err := q.db.Query(ctx, listRepositoryRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryRoot
	for rows.Next() {
		var i RepositoryRoot
		if err := rows.Scan(
			&i.RootID,
			&i.Name,
			&i.Path,
			&i.Kind,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryRoot = `-- name: SetRepositoryRoot :one
UPDATE repositories
SET root_id = $2, updated_at = $3
WHERE repo_id = $1
RETURNING repo_id, name, path, config, status, last_sync, created_at, updated_at, default_owner_id, role, root_id
`

type SetRepositoryRootParams struct {
	RepoID    pgtype.UUID        `db:"repo_id" json:"repo_id"`
	RootID    pgtype.UUID        `db:"root_id" json:"root_id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SetRepositoryRoot(ctx context.Context, arg SetRepositoryRootParams) (Repository, error) {
	row := q.db.QueryRow(ctx, setRepositoryRoot, arg.RepoID, arg.RootID, arg.UpdatedAt)
	var i Repository
	err := row.Scan(
		&i.RepoID,
		&i.Name,
		&i.Path,
		&i.Config,
		&i.Status,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultOwnerID,
		&i.Role,
		&i.RootID,
	)
	return i, err
}

const updateRepositoryRootFromDisk = `-- name: UpdateRepositoryRootFromDisk :one
UPDATE repository_roots
SET
    name = $2,
    status = $3,
    updated_at = $4
WHERE root_id = $1
RETURNING root_id, name, path, kind, status, created_at, updated_at
`

type UpdateRepositoryRootFromDiskParams struct {
	RootID    pgtype.UUID                  `db:"root_id" json:"root_id"`
	Name      string                       `db:"name" json:"name"`
	Status    dbtypes.RepositoryRootStatus `db:"status" json:"status"`
	UpdatedAt pgtype.Timestamptz           `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateRepositoryRootFromDisk(ctx context.Context, arg UpdateRepositoryRootFromDiskParams) (RepositoryRoot, error) {
	row := q.db.QueryRow(ctx, updateRepositoryRootFromDisk,
		arg.RootID,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
	)
	var i RepositoryRoot
	err := row.Scan(
		&i.RootID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepositoryRoot = `-- name: UpsertRepositoryRoot :one
INSERT INTO repository_roots (
    root_id,
    name,
    path,
    kind,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (root_id) DO UPDATE SET
    name = EXCLUDED.name,
    path = EXCLUDED.path,
    kind = EXCLUDED.kind,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
RETURNING root_id, name, path, kind, status, created_at, updated_at
`

type UpsertRepositoryRootParams struct {
	RootID    pgtype.UUID                  `db:"root_id" json:"root_id"`
	Name      string                       `db:"name" json:"name"`
	Path      string                       `db:"path" json:"path"`
	Kind      dbtypes.RepositoryRootKind   `db:"kind" json:"kind"`
	Status    dbtypes.RepositoryRootStatus `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz           `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz           `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertRepositoryRoot(ctx context.Context, arg UpsertRepositoryRootParams) (RepositoryRoot, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryRoot,
		arg.RootID,
		arg.Name,
		arg.Path,
		arg.Kind,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RepositoryRoot
	err := row.Scan(
		&i.RootID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
