// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: share_links.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (owner_id, token_hash, title, description, source_kind, source_ref, asset_ids, asset_count, allow_download, include_originals, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING share_id, owner_id, token_hash, title, description, source_kind, source_ref, asset_ids, asset_count, allow_download, include_originals, status, expires_at, created_at, updated_at, revoked_at, last_viewed_at, view_count
`

type CreateShareLinkParams struct {
	OwnerID          int32              `db:"owner_id" json:"owner_id"`
	TokenHash        []byte             `db:"token_hash" json:"token_hash"`
	Title            string             `db:"title" json:"title"`
	Description      *string            `db:"description" json:"description"`
	SourceKind       string             `db:"source_kind" json:"source_kind"`
	SourceRef        *string            `db:"source_ref" json:"source_ref"`
	AssetIds         []pgtype.UUID      `db:"asset_ids" json:"asset_ids"`
	AssetCount       int32              `db:"asset_count" json:"asset_count"`
	AllowDownload    bool               `db:"allow_download" json:"allow_download"`
	IncludeOriginals bool               `db:"include_originals" json:"include_originals"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink,
		arg.OwnerID,
		arg.TokenHash,
		arg.Title,
		arg.Description,
		arg.SourceKind,
		arg.SourceRef,
		arg.AssetIds,
		arg.AssetCount,
		arg.AllowDownload,
		arg.IncludeOriginals,
		arg.ExpiresAt,
	)
	var i ShareLink
	err := row.Scan(
		&i.ShareID,
		&i.OwnerID,
		&i.TokenHash,
		&i.Title,
		&i.Description,
		&i.SourceKind,
		&i.SourceRef,
		&i.AssetIds,
		&i.AssetCount,
		&i.AllowDownload,
		&i.IncludeOriginals,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const deleteShareLink = `-- name: DeleteShareLink :execrows
DELETE FROM share_links
WHERE share_id = $1 AND owner_id = $2 AND (status = 'revoked' OR expires_at < CURRENT_TIMESTAMP)
`

type DeleteShareLinkParams struct {
	ShareID pgtype.UUID `db:"share_id" json:"share_id"`
	OwnerID int32       `db:"owner_id" json:"owner_id"`
}

func (q *Queries) DeleteShareLink(ctx context.Context, arg DeleteShareLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShareLink, arg.ShareID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendShareLinkExpiry = `-- name: ExtendShareLinkExpiry :one
UPDATE share_links
SET expires_at = $3, updated_at = CURRENT_TIMESTAMP
WHERE share_id = $1 AND owner_id = $2
RETURNING share_id, owner_id, token_hash, title, description, source_kind, source_ref, asset_ids, asset_count, allow_download, include_originals, status, expires_at, created_at, updated_at, revoked_at, last_viewed_at, view_count
`

type ExtendShareLinkExpiryParams struct {
	ShareID   pgtype.UUID        `db:"share_id" json:"share_id"`
	OwnerID   int32              `db:"owner_id" json:"owner_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ExtendShareLinkExpiry(ctx context.Context, arg ExtendShareLinkExpiryParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, extendShareLinkExpiry, arg.ShareID, arg.OwnerID, arg.ExpiresAt)
	var i ShareLink
	err := row.Scan(
		&i.ShareID,
		&i.OwnerID,
		&i.TokenHash,
		&i.Title,
		&i.Description,
		&i.SourceKind,
		&i.SourceRef,
		&i.AssetIds,
		&i.AssetCount,
		&i.AllowDownload,
		&i.IncludeOriginals,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const getActiveShareLinkByTokenHash = `-- name: GetActiveShareLinkByTokenHash :one
SELECT share_id, owner_id, token_hash, title, description, source_kind, source_ref, asset_ids, asset_count, allow_download, include_originals, status, expires_at, created_at, updated_at, revoked_at, last_viewed_at, view_count FROM share_links
WHERE token_hash = $1 AND status = 'active' AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetActiveShareLinkByTokenHash(ctx context.Context, tokenHash []byte) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getActiveShareLinkByTokenHash, tokenHash)
	var i ShareLink
	err := row.Scan(
		&i.ShareID,
		&i.OwnerID,
		&i.TokenHash,
		&i.Title,
		&i.Description,
		&i.SourceKind,
		&i.SourceRef,
		&i.AssetIds,
		&i.AssetCount,
		&i.AllowDownload,
		&i.IncludeOriginals,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const getShareLinkByID = `-- name: GetShareLinkByID :one
SELECT share_id, owner_id, token_hash, title, description, source_kind, source_ref, asset_ids, asset_count, allow_download, include_originals, status, expires_at, created_at, updated_at, revoked_at, last_viewed_at, view_count FROM share_links WHERE share_id = $1 AND owner_id = $2
`

type GetShareLinkByIDParams struct {
	ShareID pgtype.UUID `db:"share_id" json:"share_id"`
	OwnerID int32       `db:"owner_id" json:"owner_id"`
}

func (q *Queries) GetShareLinkByID(ctx context.Context, arg GetShareLinkByIDParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByID, arg.ShareID, arg.OwnerID)
	var i ShareLink
	err := row.Scan(
		&i.ShareID,
		&i.OwnerID,
		&i.TokenHash,
		&i.Title,
		&i.Description,
		&i.SourceKind,
		&i.SourceRef,
		&i.AssetIds,
		&i.AssetCount,
		&i.AllowDownload,
		&i.IncludeOriginals,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const incrementShareLinkView = `-- name: IncrementShareLinkView :exec
UPDATE share_links
SET view_count = view_count + 1, last_viewed_at = CURRENT_TIMESTAMP
WHERE share_id = $1
`

func (q *Queries) IncrementShareLinkView(ctx context.Context, shareID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementShareLinkView, shareID)
	return err
}

const listShareLinksByOwner = `-- name: ListShareLinksByOwner :many
SELECT share_id, owner_id, token_hash, title, description, source_kind, source_ref, asset_ids, asset_count, allow_download, include_originals, status, expires_at, created_at, updated_at, revoked_at, last_viewed_at, view_count FROM share_links WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListShareLinksByOwner(ctx context.Context, ownerID int32) ([]ShareLink, error) {
	rows, err := q.db.Query(ctx, listShareLinksByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareLink
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ShareID,
			&i.OwnerID,
			&i.TokenHash,
			&i.Title,
			&i.Description,
			&i.SourceKind,
			&i.SourceRef,
			&i.AssetIds,
			&i.AssetCount,
			&i.AllowDownload,
			&i.IncludeOriginals,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.LastViewedAt,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShareLink = `-- name: RevokeShareLink :one
UPDATE share_links
SET status = 'revoked', revoked_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE share_id = $1 AND owner_id = $2
RETURNING share_id, owner_id, token_hash, title, description, source_kind, source_ref, asset_ids, asset_count, allow_download, include_originals, status, expires_at, created_at, updated_at, revoked_at, last_viewed_at, view_count
`

type RevokeShareLinkParams struct {
	ShareID pgtype.UUID `db:"share_id" json:"share_id"`
	OwnerID int32       `db:"owner_id" json:"owner_id"`
}

func (q *Queries) RevokeShareLink(ctx context.Context, arg RevokeShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, revokeShareLink, arg.ShareID, arg.OwnerID)
	var i ShareLink
	err := row.Scan(
		&i.ShareID,
		&i.OwnerID,
		&i.TokenHash,
		&i.Title,
		&i.Description,
		&i.SourceKind,
		&i.SourceRef,
		&i.AssetIds,
		&i.AssetCount,
		&i.AllowDownload,
		&i.IncludeOriginals,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const updateShareLinkSettings = `-- name: UpdateShareLinkSettings :one
UPDATE share_links
SET title = $3, description = $4, allow_download = $5, include_originals = $6, updated_at = CURRENT_TIMESTAMP
WHERE share_id = $1 AND owner_id = $2
RETURNING share_id, owner_id, token_hash, title, description, source_kind, source_ref, asset_ids, asset_count, allow_download, include_originals, status, expires_at, created_at, updated_at, revoked_at, last_viewed_at, view_count
`

type UpdateShareLinkSettingsParams struct {
	ShareID          pgtype.UUID `db:"share_id" json:"share_id"`
	OwnerID          int32       `db:"owner_id" json:"owner_id"`
	Title            string      `db:"title" json:"title"`
	Description      *string     `db:"description" json:"description"`
	AllowDownload    bool        `db:"allow_download" json:"allow_download"`
	IncludeOriginals bool        `db:"include_originals" json:"include_originals"`
}

func (q *Queries) UpdateShareLinkSettings(ctx context.Context, arg UpdateShareLinkSettingsParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, updateShareLinkSettings,
		arg.ShareID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.AllowDownload,
		arg.IncludeOriginals,
	)
	var i ShareLink
	err := row.Scan(
		&i.ShareID,
		&i.OwnerID,
		&i.TokenHash,
		&i.Title,
		&i.Description,
		&i.SourceKind,
		&i.SourceRef,
		&i.AssetIds,
		&i.AssetCount,
		&i.AllowDownload,
		&i.IncludeOriginals,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.LastViewedAt,
		&i.ViewCount,
	)
	return i, err
}
