// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stacks.sql

package repo

import (
	"context"
	"strings"

	"github.com/google/uuid"
	"server/internal/db/dbtypes"
)

const addStackMember = `-- name: AddStackMember :exec
INSERT INTO asset_stack_members (media_item_id, stack_id, position, created_at)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4
)
ON CONFLICT (media_item_id) DO NOTHING
`

type AddStackMemberParams struct {
	MediaItemID uuid.UUID         `db:"media_item_id" json:"media_item_id"`
	StackID     uuid.UUID         `db:"stack_id" json:"stack_id"`
	Position    int64             `db:"position" json:"position"`
	CreatedAt   dbtypes.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) AddStackMember(ctx context.Context, arg AddStackMemberParams) error {
	_, err := q.db.ExecContext(ctx, addStackMember,
		arg.MediaItemID,
		arg.StackID,
		arg.Position,
		arg.CreatedAt,
	)
	return err
}

const countStackedMediaItems = `-- name: CountStackedMediaItems :one
SELECT COUNT(DISTINCT media_item_id)
FROM asset_stack_members
WHERE media_item_id IN (/*SLICE:media_item_ids*/?)
`

func (q *Queries) CountStackedMediaItems(ctx context.Context, mediaItemIds []uuid.UUID) (int64, error) {
	query := countStackedMediaItems
	var queryParams []interface{}
	if len(mediaItemIds) > 0 {
		for _, v := range mediaItemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:media_item_ids*/?", strings.Repeat(",?", len(mediaItemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:media_item_ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssetStack = `-- name: CreateAssetStack :one
INSERT INTO asset_stacks (
  stack_id, owner_id, repository_id, stack_kind, cover_media_item_id,
  group_key, created_at, updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
RETURNING stack_id, owner_id, repository_id, stack_kind, cover_media_item_id, group_key, created_at, updated_at
`

type CreateAssetStackParams struct {
	StackID          uuid.UUID         `db:"stack_id" json:"stack_id"`
	OwnerID          *int32            `db:"owner_id" json:"owner_id"`
	RepositoryID     uuid.NullUUID     `db:"repository_id" json:"repository_id"`
	StackKind        string            `db:"stack_kind" json:"stack_kind"`
	CoverMediaItemID uuid.NullUUID     `db:"cover_media_item_id" json:"cover_media_item_id"`
	GroupKey         *string           `db:"group_key" json:"group_key"`
	CreatedAt        dbtypes.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateAssetStack(ctx context.Context, arg CreateAssetStackParams) (AssetStack, error) {
	row := q.db.QueryRowContext(ctx, createAssetStack,
		arg.StackID,
		arg.OwnerID,
		arg.RepositoryID,
		arg.StackKind,
		arg.CoverMediaItemID,
		arg.GroupKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AssetStack
	err := row.Scan(
		&i.StackID,
		&i.OwnerID,
		&i.RepositoryID,
		&i.StackKind,
		&i.CoverMediaItemID,
		&i.GroupKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaItem = `-- name: DeleteMediaItem :exec
DELETE FROM media_items WHERE media_item_id = ?1
`

func (q *Queries) DeleteMediaItem(ctx context.Context, mediaItemID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMediaItem, mediaItemID)
	return err
}

const deleteStack = `-- name: DeleteStack :exec

DELETE FROM asset_stacks WHERE stack_id = ?1
`

// Presentation stacks ------------------------------------------------------
func (q *Queries) DeleteStack(ctx context.Context, stackID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStack, stackID)
	return err
}

const findCandidatesForStackingByName = `-- name: FindCandidatesForStackingByName :many

SELECT a.asset_id,
       mia.media_item_id,
       mia.relation,
       a.owner_id,
       a.original_filename,
       a.mime_type,
       CAST(COALESCE(json_extract(a.specific_metadata, '$.is_raw'), 0) AS INTEGER) AS is_raw,
       CAST(COALESCE(json_extract(a.specific_metadata, '$.camera_model'), '') AS TEXT) AS camera_model,
       CAST(COALESCE(
           NULLIF(json_extract(a.exif_raw, '$.BurstUUID'), ''),
           NULLIF(json_extract(a.exif_raw, '$.BurstID'), ''),
           NULLIF(json_extract(a.exif_raw, '$.BurstGroupID'), ''),
           ''
       ) AS TEXT) AS burst_id,
       a.taken_time,
       a.upload_time,
       CAST(lower(a.original_filename) AS TEXT) AS base_name
FROM assets a
JOIN media_item_assets mia ON mia.asset_id = a.asset_id
WHERE a.is_deleted = false
  AND EXISTS (
    SELECT 1 FROM active_asset_occurrences occurrence
    WHERE occurrence.asset_id = a.asset_id
      AND occurrence.repository_id = ?1
  )
  AND a.type = 'PHOTO'
ORDER BY base_name, a.original_filename
`

type FindCandidatesForStackingByNameRow struct {
	AssetID          uuid.UUID         `db:"asset_id" json:"asset_id"`
	MediaItemID      uuid.UUID         `db:"media_item_id" json:"media_item_id"`
	Relation         string            `db:"relation" json:"relation"`
	OwnerID          *int32            `db:"owner_id" json:"owner_id"`
	OriginalFilename string            `db:"original_filename" json:"original_filename"`
	MimeType         string            `db:"mime_type" json:"mime_type"`
	IsRaw            int64             `db:"is_raw" json:"is_raw"`
	CameraModel      string            `db:"camera_model" json:"camera_model"`
	BurstID          string            `db:"burst_id" json:"burst_id"`
	TakenTime        dbtypes.Timestamp `db:"taken_time" json:"taken_time"`
	UploadTime       dbtypes.Timestamp `db:"upload_time" json:"upload_time"`
	BaseName         string            `db:"base_name" json:"base_name"`
}

// Structural and burst detection ------------------------------------------
func (q *Queries) FindCandidatesForStackingByName(ctx context.Context, repositoryID uuid.UUID) ([]FindCandidatesForStackingByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, findCandidatesForStackingByName, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCandidatesForStackingByNameRow
	for rows.Next() {
		var i FindCandidatesForStackingByNameRow
		if err := rows.Scan(
			&i.AssetID,
			&i.MediaItemID,
			&i.Relation,
			&i.OwnerID,
			&i.OriginalFilename,
			&i.MimeType,
			&i.IsRaw,
			&i.CameraModel,
			&i.BurstID,
			&i.TakenTime,
			&i.UploadTime,
			&i.BaseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLivePhotoPair = `-- name: FindLivePhotoPair :many
SELECT asset_id, type
FROM assets
WHERE owner_id = ?1
  AND is_deleted = false
  AND type IN ('PHOTO', 'VIDEO')
  AND json_extract(specific_metadata, '$.content_identifier')
      = CAST(?2 AS TEXT)
ORDER BY type, asset_id
`

type FindLivePhotoPairParams struct {
	OwnerID           *int32 `db:"owner_id" json:"owner_id"`
	ContentIdentifier string `db:"content_identifier" json:"content_identifier"`
}

type FindLivePhotoPairRow struct {
	AssetID uuid.UUID `db:"asset_id" json:"asset_id"`
	Type    string    `db:"type" json:"type"`
}

func (q *Queries) FindLivePhotoPair(ctx context.Context, arg FindLivePhotoPairParams) ([]FindLivePhotoPairRow, error) {
	rows, err := q.db.QueryContext(ctx, findLivePhotoPair, arg.OwnerID, arg.ContentIdentifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindLivePhotoPairRow
	for rows.Next() {
		var i FindLivePhotoPairRow
		if err := rows.Scan(&i.AssetID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMediaItemsForBurstDetection = `-- name: FindMediaItemsForBurstDetection :many
SELECT mi.media_item_id,
       mi.owner_id,
       mi.repository_id,
       mi.primary_asset_id,
       primary_asset.original_filename,
       primary_asset.taken_time,
       primary_asset.upload_time,
       CAST(COALESCE(json_extract(primary_asset.specific_metadata, '$.camera_model'), '') AS TEXT) AS camera_model,
       CAST(COALESCE(
           MAX(NULLIF(json_extract(component.exif_raw, '$.BurstUUID'), '')),
           MAX(NULLIF(json_extract(component.exif_raw, '$.BurstID'), '')),
           MAX(NULLIF(json_extract(component.exif_raw, '$.BurstGroupID'), '')),
           ''
       ) AS TEXT) AS burst_id
FROM media_items mi
JOIN assets primary_asset ON primary_asset.asset_id = mi.primary_asset_id
JOIN media_item_assets mia ON mia.media_item_id = mi.media_item_id
JOIN assets component ON component.asset_id = mia.asset_id
LEFT JOIN asset_stack_members asm ON asm.media_item_id = mi.media_item_id
WHERE mi.repository_id = ?1
  AND mi.media_kind = 'photo'
  AND primary_asset.is_deleted = false
  AND asm.media_item_id IS NULL
GROUP BY mi.media_item_id, primary_asset.asset_id
ORDER BY COALESCE(primary_asset.taken_time, primary_asset.upload_time), mi.media_item_id
`

type FindMediaItemsForBurstDetectionRow struct {
	MediaItemID      uuid.UUID         `db:"media_item_id" json:"media_item_id"`
	OwnerID          *int32            `db:"owner_id" json:"owner_id"`
	RepositoryID     uuid.NullUUID     `db:"repository_id" json:"repository_id"`
	PrimaryAssetID   uuid.NullUUID     `db:"primary_asset_id" json:"primary_asset_id"`
	OriginalFilename string            `db:"original_filename" json:"original_filename"`
	TakenTime        dbtypes.Timestamp `db:"taken_time" json:"taken_time"`
	UploadTime       dbtypes.Timestamp `db:"upload_time" json:"upload_time"`
	CameraModel      string            `db:"camera_model" json:"camera_model"`
	BurstID          string            `db:"burst_id" json:"burst_id"`
}

func (q *Queries) FindMediaItemsForBurstDetection(ctx context.Context, repositoryID uuid.NullUUID) ([]FindMediaItemsForBurstDetectionRow, error) {
	rows, err := q.db.QueryContext(ctx, findMediaItemsForBurstDetection, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindMediaItemsForBurstDetectionRow
	for rows.Next() {
		var i FindMediaItemsForBurstDetectionRow
		if err := rows.Scan(
			&i.MediaItemID,
			&i.OwnerID,
			&i.RepositoryID,
			&i.PrimaryAssetID,
			&i.OriginalFilename,
			&i.TakenTime,
			&i.UploadTime,
			&i.CameraModel,
			&i.BurstID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUnmatchedLivePhotoPairs = `-- name: FindUnmatchedLivePhotoPairs :many
WITH identified AS (
  SELECT a.owner_id AS owner_id,
         a.asset_id AS asset_id,
         a.type AS asset_type,
         mia.media_item_id AS media_item_id,
         CAST(json_extract(a.specific_metadata, '$.content_identifier') AS TEXT) AS content_identifier
  FROM assets a
  JOIN media_item_assets mia ON mia.asset_id = a.asset_id
  WHERE a.is_deleted = false
    AND EXISTS (
      SELECT 1 FROM active_asset_occurrences occurrence
      WHERE occurrence.asset_id = a.asset_id
        AND occurrence.repository_id = ?1
    )
    AND a.type IN ('PHOTO', 'VIDEO')
    AND NULLIF(json_extract(a.specific_metadata, '$.content_identifier'), '') IS NOT NULL
),
paired AS (
  SELECT owner_id, content_identifier
  FROM identified
  GROUP BY owner_id, content_identifier
  HAVING COUNT(DISTINCT asset_type) = 2
)
SELECT i.owner_id, i.asset_id, i.asset_type, i.media_item_id, i.content_identifier
FROM identified i
JOIN paired p
  ON p.owner_id = i.owner_id
 AND p.content_identifier = i.content_identifier
WHERE NOT EXISTS (
  SELECT 1
  FROM media_item_assets existing
  WHERE existing.media_item_id = i.media_item_id
    AND existing.relation IN ('live_photo_still', 'live_photo_video')
)
ORDER BY i.content_identifier, i.asset_type, i.asset_id
`

type FindUnmatchedLivePhotoPairsRow struct {
	OwnerID           int32     `db:"owner_id" json:"owner_id"`
	AssetID           uuid.UUID `db:"asset_id" json:"asset_id"`
	AssetType         string    `db:"asset_type" json:"asset_type"`
	MediaItemID       uuid.UUID `db:"media_item_id" json:"media_item_id"`
	ContentIdentifier string    `db:"content_identifier" json:"content_identifier"`
}

// Live Photo post-consistency: still/motion components in this repository
// that share a content identifier but whose media items never joined (for
// example because matching ran before the pair finished metadata extraction).
// Items already carrying live_photo_* components are excluded.
func (q *Queries) FindUnmatchedLivePhotoPairs(ctx context.Context, repositoryID uuid.UUID) ([]FindUnmatchedLivePhotoPairsRow, error) {
	rows, err := q.db.QueryContext(ctx, findUnmatchedLivePhotoPairs, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUnmatchedLivePhotoPairsRow
	for rows.Next() {
		var i FindUnmatchedLivePhotoPairsRow
		if err := rows.Scan(
			&i.OwnerID,
			&i.AssetID,
			&i.AssetType,
			&i.MediaItemID,
			&i.ContentIdentifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBurstStackByGroupKey = `-- name: GetBurstStackByGroupKey :one
SELECT stack_id, owner_id, repository_id, stack_kind, cover_media_item_id, group_key, created_at, updated_at
FROM asset_stacks
WHERE stack_kind = 'burst' AND group_key = ?1
`

func (q *Queries) GetBurstStackByGroupKey(ctx context.Context, groupKey *string) (AssetStack, error) {
	row := q.db.QueryRowContext(ctx, getBurstStackByGroupKey, groupKey)
	var i AssetStack
	err := row.Scan(
		&i.StackID,
		&i.OwnerID,
		&i.RepositoryID,
		&i.StackKind,
		&i.CoverMediaItemID,
		&i.GroupKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaItemBrowseFactsByIDs = `-- name: GetMediaItemBrowseFactsByIDs :many
SELECT
  f.media_item_id,
  f.primary_asset_id,
  f.media_kind,
  CAST(f.component_count AS INTEGER) AS component_count,
  CAST(f.has_raw AS INTEGER) AS has_raw,
  CAST(f.has_jpeg AS INTEGER) AS has_jpeg,
  CAST(f.has_edited AS INTEGER) AS has_edited,
  CAST(f.has_live_motion AS INTEGER) AS has_live_motion,
  f.stack_id,
  f.stack_position,
  f.stack_kind
FROM media_item_browse_facts f
WHERE f.media_item_id IN (/*SLICE:media_item_ids*/?)
`

type GetMediaItemBrowseFactsByIDsRow struct {
	MediaItemID    uuid.UUID `db:"media_item_id" json:"media_item_id"`
	PrimaryAssetID uuid.UUID `db:"primary_asset_id" json:"primary_asset_id"`
	MediaKind      string    `db:"media_kind" json:"media_kind"`
	ComponentCount int64     `db:"component_count" json:"component_count"`
	HasRaw         int64     `db:"has_raw" json:"has_raw"`
	HasJpeg        int64     `db:"has_jpeg" json:"has_jpeg"`
	HasEdited      int64     `db:"has_edited" json:"has_edited"`
	HasLiveMotion  int64     `db:"has_live_motion" json:"has_live_motion"`
	StackID        uuid.UUID `db:"stack_id" json:"stack_id"`
	StackPosition  *int64    `db:"stack_position" json:"stack_position"`
	StackKind      *string   `db:"stack_kind" json:"stack_kind"`
}

// Composition/stack facts for a set of logical media items, used to hydrate
// browse items outside the unified query path (aggregate search, fused search).
func (q *Queries) GetMediaItemBrowseFactsByIDs(ctx context.Context, mediaItemIds []uuid.UUID) ([]GetMediaItemBrowseFactsByIDsRow, error) {
	query := getMediaItemBrowseFactsByIDs
	var queryParams []interface{}
	if len(mediaItemIds) > 0 {
		for _, v := range mediaItemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:media_item_ids*/?", strings.Repeat(",?", len(mediaItemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:media_item_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemBrowseFactsByIDsRow
	for rows.Next() {
		var i GetMediaItemBrowseFactsByIDsRow
		if err := rows.Scan(
			&i.MediaItemID,
			&i.PrimaryAssetID,
			&i.MediaKind,
			&i.ComponentCount,
			&i.HasRaw,
			&i.HasJpeg,
			&i.HasEdited,
			&i.HasLiveMotion,
			&i.StackID,
			&i.StackPosition,
			&i.StackKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaItemByAssetID = `-- name: GetMediaItemByAssetID :one

SELECT mi.media_item_id, mi.owner_id, mi.repository_id, mi.media_kind, mi.primary_asset_id, mi.group_key, mi.created_at, mi.updated_at
FROM media_items mi
JOIN media_item_assets mia ON mia.media_item_id = mi.media_item_id
WHERE mia.asset_id = ?1
`

// Logical media items -------------------------------------------------------
func (q *Queries) GetMediaItemByAssetID(ctx context.Context, assetID uuid.UUID) (MediaItem, error) {
	row := q.db.QueryRowContext(ctx, getMediaItemByAssetID, assetID)
	var i MediaItem
	err := row.Scan(
		&i.MediaItemID,
		&i.OwnerID,
		&i.RepositoryID,
		&i.MediaKind,
		&i.PrimaryAssetID,
		&i.GroupKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaItemComponents = `-- name: GetMediaItemComponents :many
SELECT mia.asset_id, mia.media_item_id, mia.relation, mia.position, mia.created_at
FROM media_item_assets mia
JOIN assets a ON a.asset_id = mia.asset_id
WHERE mia.media_item_id = ?1
  AND (?2 IS NULL OR a.owner_id = ?2)
ORDER BY mia.position ASC, mia.created_at ASC
`

type GetMediaItemComponentsParams struct {
	MediaItemID uuid.UUID   `db:"media_item_id" json:"media_item_id"`
	OwnerID     interface{} `db:"owner_id" json:"owner_id"`
}

func (q *Queries) GetMediaItemComponents(ctx context.Context, arg GetMediaItemComponentsParams) ([]MediaItemAsset, error) {
	rows, err := q.db.QueryContext(ctx, getMediaItemComponents, arg.MediaItemID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaItemAsset
	for rows.Next() {
		var i MediaItemAsset
		if err := rows.Scan(
			&i.AssetID,
			&i.MediaItemID,
			&i.Relation,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaItemsByAssetIDs = `-- name: GetMediaItemsByAssetIDs :many
SELECT mia.asset_id, mia.media_item_id, mi.primary_asset_id
FROM media_item_assets mia
JOIN media_items mi ON mi.media_item_id = mia.media_item_id
WHERE mia.asset_id IN (/*SLICE:asset_ids*/?)
`

type GetMediaItemsByAssetIDsRow struct {
	AssetID        uuid.UUID     `db:"asset_id" json:"asset_id"`
	MediaItemID    uuid.UUID     `db:"media_item_id" json:"media_item_id"`
	PrimaryAssetID uuid.NullUUID `db:"primary_asset_id" json:"primary_asset_id"`
}

func (q *Queries) GetMediaItemsByAssetIDs(ctx context.Context, assetIds []uuid.UUID) ([]GetMediaItemsByAssetIDsRow, error) {
	query := getMediaItemsByAssetIDs
	var queryParams []interface{}
	if len(assetIds) > 0 {
		for _, v := range assetIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", strings.Repeat(",?", len(assetIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemsByAssetIDsRow
	for rows.Next() {
		var i GetMediaItemsByAssetIDsRow
		if err := rows.Scan(&i.AssetID, &i.MediaItemID, &i.PrimaryAssetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextStackPosition = `-- name: GetNextStackPosition :one
SELECT CAST(COALESCE(MAX(position) + 1, 0) AS INTEGER)
FROM asset_stack_members
WHERE stack_id = ?1
`

func (q *Queries) GetNextStackPosition(ctx context.Context, stackID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextStackPosition, stackID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getStackByAssetID = `-- name: GetStackByAssetID :one
SELECT asm.stack_id, asm.media_item_id, asm.position
FROM media_item_assets mia
JOIN asset_stack_members asm ON asm.media_item_id = mia.media_item_id
WHERE mia.asset_id = ?1
`

type GetStackByAssetIDRow struct {
	StackID     uuid.UUID `db:"stack_id" json:"stack_id"`
	MediaItemID uuid.UUID `db:"media_item_id" json:"media_item_id"`
	Position    int64     `db:"position" json:"position"`
}

func (q *Queries) GetStackByAssetID(ctx context.Context, assetID uuid.UUID) (GetStackByAssetIDRow, error) {
	row := q.db.QueryRowContext(ctx, getStackByAssetID, assetID)
	var i GetStackByAssetIDRow
	err := row.Scan(&i.StackID, &i.MediaItemID, &i.Position)
	return i, err
}

const getStackMemberCount = `-- name: GetStackMemberCount :one
SELECT COUNT(*) AS count
FROM asset_stack_members asm
JOIN media_items mi ON mi.media_item_id = asm.media_item_id
JOIN assets a ON a.asset_id = mi.primary_asset_id
WHERE asm.stack_id = ?1
  AND a.is_deleted = false
  AND (?2 IS NULL OR mi.owner_id = ?2)
`

type GetStackMemberCountParams struct {
	StackID uuid.UUID   `db:"stack_id" json:"stack_id"`
	OwnerID interface{} `db:"owner_id" json:"owner_id"`
}

func (q *Queries) GetStackMemberCount(ctx context.Context, arg GetStackMemberCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStackMemberCount, arg.StackID, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStackMemberCountAny = `-- name: GetStackMemberCountAny :one
SELECT COUNT(*) AS count
FROM asset_stack_members asm
JOIN media_items mi ON mi.media_item_id = asm.media_item_id
WHERE asm.stack_id = ?1
  AND (?2 IS NULL OR mi.owner_id = ?2)
`

type GetStackMemberCountAnyParams struct {
	StackID uuid.UUID   `db:"stack_id" json:"stack_id"`
	OwnerID interface{} `db:"owner_id" json:"owner_id"`
}

func (q *Queries) GetStackMemberCountAny(ctx context.Context, arg GetStackMemberCountAnyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStackMemberCountAny, arg.StackID, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStackMembers = `-- name: GetStackMembers :many
SELECT asm.media_item_id, mi.primary_asset_id AS asset_id, asm.position, asm.created_at
FROM asset_stack_members asm
JOIN media_items mi ON mi.media_item_id = asm.media_item_id
JOIN assets a ON a.asset_id = mi.primary_asset_id
WHERE asm.stack_id = ?1
  AND a.is_deleted = false
  AND (?2 IS NULL OR mi.owner_id = ?2)
ORDER BY asm.position ASC, asm.created_at ASC
`

type GetStackMembersParams struct {
	StackID uuid.UUID   `db:"stack_id" json:"stack_id"`
	OwnerID interface{} `db:"owner_id" json:"owner_id"`
}

type GetStackMembersRow struct {
	MediaItemID uuid.UUID         `db:"media_item_id" json:"media_item_id"`
	AssetID     uuid.NullUUID     `db:"asset_id" json:"asset_id"`
	Position    int64             `db:"position" json:"position"`
	CreatedAt   dbtypes.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetStackMembers(ctx context.Context, arg GetStackMembersParams) ([]GetStackMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getStackMembers, arg.StackID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStackMembersRow
	for rows.Next() {
		var i GetStackMembersRow
		if err := rows.Scan(
			&i.MediaItemID,
			&i.AssetID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStackMembersAny = `-- name: GetStackMembersAny :many
SELECT asm.media_item_id, mi.primary_asset_id AS asset_id, asm.position, asm.created_at
FROM asset_stack_members asm
JOIN media_items mi ON mi.media_item_id = asm.media_item_id
WHERE asm.stack_id = ?1
  AND (?2 IS NULL OR mi.owner_id = ?2)
ORDER BY asm.position ASC, asm.created_at ASC
`

type GetStackMembersAnyParams struct {
	StackID uuid.UUID   `db:"stack_id" json:"stack_id"`
	OwnerID interface{} `db:"owner_id" json:"owner_id"`
}

type GetStackMembersAnyRow struct {
	MediaItemID uuid.UUID         `db:"media_item_id" json:"media_item_id"`
	AssetID     uuid.NullUUID     `db:"asset_id" json:"asset_id"`
	Position    int64             `db:"position" json:"position"`
	CreatedAt   dbtypes.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetStackMembersAny(ctx context.Context, arg GetStackMembersAnyParams) ([]GetStackMembersAnyRow, error) {
	rows, err := q.db.QueryContext(ctx, getStackMembersAny, arg.StackID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStackMembersAnyRow
	for rows.Next() {
		var i GetStackMembersAnyRow
		if err := rows.Scan(
			&i.MediaItemID,
			&i.AssetID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStackMembershipsByMediaItemIDs = `-- name: GetStackMembershipsByMediaItemIDs :many
SELECT stack_id, CAST(MIN(position) AS INTEGER) AS position
FROM asset_stack_members
WHERE media_item_id IN (/*SLICE:media_item_ids*/?)
GROUP BY stack_id
`

type GetStackMembershipsByMediaItemIDsRow struct {
	StackID  uuid.UUID `db:"stack_id" json:"stack_id"`
	Position int64     `db:"position" json:"position"`
}

func (q *Queries) GetStackMembershipsByMediaItemIDs(ctx context.Context, mediaItemIds []uuid.UUID) ([]GetStackMembershipsByMediaItemIDsRow, error) {
	query := getStackMembershipsByMediaItemIDs
	var queryParams []interface{}
	if len(mediaItemIds) > 0 {
		for _, v := range mediaItemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:media_item_ids*/?", strings.Repeat(",?", len(mediaItemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:media_item_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStackMembershipsByMediaItemIDsRow
	for rows.Next() {
		var i GetStackMembershipsByMediaItemIDsRow
		if err := rows.Scan(&i.StackID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStackNormalizationState = `-- name: GetStackNormalizationState :many
SELECT asm.media_item_id,
       asm.position,
       mi.owner_id,
       mi.repository_id
FROM asset_stack_members asm
JOIN media_items mi ON mi.media_item_id = asm.media_item_id
WHERE asm.stack_id = ?1
ORDER BY asm.position ASC, asm.created_at ASC, asm.media_item_id ASC
`

type GetStackNormalizationStateRow struct {
	MediaItemID  uuid.UUID     `db:"media_item_id" json:"media_item_id"`
	Position     int64         `db:"position" json:"position"`
	OwnerID      *int32        `db:"owner_id" json:"owner_id"`
	RepositoryID uuid.NullUUID `db:"repository_id" json:"repository_id"`
}

// All memberships of a stack with the member scope needed to enforce the
// presentation-stack invariants (no soft-delete filtering: trash restores must
// keep their memberships).
func (q *Queries) GetStackNormalizationState(ctx context.Context, stackID uuid.UUID) ([]GetStackNormalizationStateRow, error) {
	rows, err := q.db.QueryContext(ctx, getStackNormalizationState, stackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStackNormalizationStateRow
	for rows.Next() {
		var i GetStackNormalizationStateRow
		if err := rows.Scan(
			&i.MediaItemID,
			&i.Position,
			&i.OwnerID,
			&i.RepositoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStackScope = `-- name: GetStackScope :one
SELECT owner_id, repository_id, cover_media_item_id
FROM asset_stacks
WHERE stack_id = ?1
`

type GetStackScopeRow struct {
	OwnerID          *int32        `db:"owner_id" json:"owner_id"`
	RepositoryID     uuid.NullUUID `db:"repository_id" json:"repository_id"`
	CoverMediaItemID uuid.NullUUID `db:"cover_media_item_id" json:"cover_media_item_id"`
}

func (q *Queries) GetStackScope(ctx context.Context, stackID uuid.UUID) (GetStackScopeRow, error) {
	row := q.db.QueryRowContext(ctx, getStackScope, stackID)
	var i GetStackScopeRow
	err := row.Scan(&i.OwnerID, &i.RepositoryID, &i.CoverMediaItemID)
	return i, err
}

const getStacksByAssetIDs = `-- name: GetStacksByAssetIDs :many
SELECT mia.asset_id, asm.media_item_id, asm.stack_id, asm.position
FROM media_item_assets mia
JOIN asset_stack_members asm ON asm.media_item_id = mia.media_item_id
WHERE mia.asset_id IN (/*SLICE:asset_ids*/?)
`

type GetStacksByAssetIDsRow struct {
	AssetID     uuid.UUID `db:"asset_id" json:"asset_id"`
	MediaItemID uuid.UUID `db:"media_item_id" json:"media_item_id"`
	StackID     uuid.UUID `db:"stack_id" json:"stack_id"`
	Position    int64     `db:"position" json:"position"`
}

func (q *Queries) GetStacksByAssetIDs(ctx context.Context, assetIds []uuid.UUID) ([]GetStacksByAssetIDsRow, error) {
	query := getStacksByAssetIDs
	var queryParams []interface{}
	if len(assetIds) > 0 {
		for _, v := range assetIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", strings.Repeat(",?", len(assetIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStacksByAssetIDsRow
	for rows.Next() {
		var i GetStacksByAssetIDsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.MediaItemID,
			&i.StackID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAllMediaItemComponents = `-- name: MoveAllMediaItemComponents :exec
UPDATE media_item_assets
SET media_item_id = ?1
WHERE media_item_id = ?2
`

type MoveAllMediaItemComponentsParams struct {
	TargetMediaItemID uuid.UUID `db:"target_media_item_id" json:"target_media_item_id"`
	SourceMediaItemID uuid.UUID `db:"source_media_item_id" json:"source_media_item_id"`
}

func (q *Queries) MoveAllMediaItemComponents(ctx context.Context, arg MoveAllMediaItemComponentsParams) error {
	_, err := q.db.ExecContext(ctx, moveAllMediaItemComponents, arg.TargetMediaItemID, arg.SourceMediaItemID)
	return err
}

const moveMediaItemComponent = `-- name: MoveMediaItemComponent :exec
UPDATE media_item_assets
SET media_item_id = ?1,
    relation = ?2,
    position = ?3
WHERE asset_id = ?4
`

type MoveMediaItemComponentParams struct {
	TargetMediaItemID uuid.UUID `db:"target_media_item_id" json:"target_media_item_id"`
	Relation          string    `db:"relation" json:"relation"`
	Position          int64     `db:"position" json:"position"`
	AssetID           uuid.UUID `db:"asset_id" json:"asset_id"`
}

func (q *Queries) MoveMediaItemComponent(ctx context.Context, arg MoveMediaItemComponentParams) error {
	_, err := q.db.ExecContext(ctx, moveMediaItemComponent,
		arg.TargetMediaItemID,
		arg.Relation,
		arg.Position,
		arg.AssetID,
	)
	return err
}

const removeStackMemberByAssetID = `-- name: RemoveStackMemberByAssetID :exec
DELETE FROM asset_stack_members
WHERE media_item_id IN (
  SELECT media_item_id
  FROM media_item_assets
  WHERE asset_id = ?1
)
`

func (q *Queries) RemoveStackMemberByAssetID(ctx context.Context, assetID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeStackMemberByAssetID, assetID)
	return err
}

const removeStackMembership = `-- name: RemoveStackMembership :exec
DELETE FROM asset_stack_members
WHERE stack_id = ?1
  AND media_item_id = ?2
`

type RemoveStackMembershipParams struct {
	StackID     uuid.UUID `db:"stack_id" json:"stack_id"`
	MediaItemID uuid.UUID `db:"media_item_id" json:"media_item_id"`
}

func (q *Queries) RemoveStackMembership(ctx context.Context, arg RemoveStackMembershipParams) error {
	_, err := q.db.ExecContext(ctx, removeStackMembership, arg.StackID, arg.MediaItemID)
	return err
}

const removeStackMembershipsByMediaItemIDs = `-- name: RemoveStackMembershipsByMediaItemIDs :exec
DELETE FROM asset_stack_members
WHERE media_item_id IN (/*SLICE:media_item_ids*/?)
`

func (q *Queries) RemoveStackMembershipsByMediaItemIDs(ctx context.Context, mediaItemIds []uuid.UUID) error {
	query := removeStackMembershipsByMediaItemIDs
	var queryParams []interface{}
	if len(mediaItemIds) > 0 {
		for _, v := range mediaItemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:media_item_ids*/?", strings.Repeat(",?", len(mediaItemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:media_item_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const selectMediaItemPrimaryAsset = `-- name: SelectMediaItemPrimaryAsset :one
SELECT mia.asset_id
FROM media_item_assets mia
JOIN assets a ON a.asset_id = mia.asset_id
WHERE mia.media_item_id = ?1
  AND a.is_deleted = false
ORDER BY
  CASE mia.relation
    WHEN 'jpeg_original' THEN 0
    WHEN 'live_photo_still' THEN 1
    WHEN 'edited_version' THEN 2
    WHEN 'raw_original' THEN 3
    ELSE 4
  END,
  mia.position ASC,
  mia.created_at ASC
LIMIT 1
`

// Canonical browsing component of a logical media item: jpeg_original first,
// then live_photo_still, edited_version, raw_original, and finally the
// component with the smallest position. Soft-deleted components never serve.
func (q *Queries) SelectMediaItemPrimaryAsset(ctx context.Context, mediaItemID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, selectMediaItemPrimaryAsset, mediaItemID)
	var asset_id uuid.UUID
	err := row.Scan(&asset_id)
	return asset_id, err
}

const updateMediaItemAfterStructuralMerge = `-- name: UpdateMediaItemAfterStructuralMerge :exec
UPDATE media_items
SET primary_asset_id = ?1,
    media_kind = CASE
      WHEN EXISTS (
        SELECT 1
        FROM media_item_assets
        WHERE media_item_assets.media_item_id = ?2
          AND relation = 'live_photo_video'
      ) THEN 'live_photo'
      ELSE 'photo'
    END,
    group_key = ?3,
    updated_at = ?4
WHERE media_items.media_item_id = ?2
`

type UpdateMediaItemAfterStructuralMergeParams struct {
	PrimaryAssetID    uuid.NullUUID     `db:"primary_asset_id" json:"primary_asset_id"`
	TargetMediaItemID uuid.UUID         `db:"target_media_item_id" json:"target_media_item_id"`
	GroupKey          *string           `db:"group_key" json:"group_key"`
	UpdatedAt         dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateMediaItemAfterStructuralMerge(ctx context.Context, arg UpdateMediaItemAfterStructuralMergeParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaItemAfterStructuralMerge,
		arg.PrimaryAssetID,
		arg.TargetMediaItemID,
		arg.GroupKey,
		arg.UpdatedAt,
	)
	return err
}

const updateMediaItemAsLivePhoto = `-- name: UpdateMediaItemAsLivePhoto :exec
UPDATE media_items
SET media_kind = 'live_photo',
    primary_asset_id = ?1,
    group_key = ?2,
    updated_at = ?3
WHERE media_item_id = ?4
`

type UpdateMediaItemAsLivePhotoParams struct {
	PrimaryAssetID uuid.NullUUID     `db:"primary_asset_id" json:"primary_asset_id"`
	GroupKey       *string           `db:"group_key" json:"group_key"`
	UpdatedAt      dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
	MediaItemID    uuid.UUID         `db:"media_item_id" json:"media_item_id"`
}

func (q *Queries) UpdateMediaItemAsLivePhoto(ctx context.Context, arg UpdateMediaItemAsLivePhotoParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaItemAsLivePhoto,
		arg.PrimaryAssetID,
		arg.GroupKey,
		arg.UpdatedAt,
		arg.MediaItemID,
	)
	return err
}

const updateMediaItemPrimaryAsset = `-- name: UpdateMediaItemPrimaryAsset :exec
UPDATE media_items
SET primary_asset_id = ?1,
    updated_at = ?2
WHERE media_item_id = ?3
  AND (primary_asset_id IS NULL OR primary_asset_id <> ?1)
`

type UpdateMediaItemPrimaryAssetParams struct {
	PrimaryAssetID uuid.NullUUID     `db:"primary_asset_id" json:"primary_asset_id"`
	UpdatedAt      dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
	MediaItemID    uuid.UUID         `db:"media_item_id" json:"media_item_id"`
}

func (q *Queries) UpdateMediaItemPrimaryAsset(ctx context.Context, arg UpdateMediaItemPrimaryAssetParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaItemPrimaryAsset, arg.PrimaryAssetID, arg.UpdatedAt, arg.MediaItemID)
	return err
}

const updateStackCover = `-- name: UpdateStackCover :exec
UPDATE asset_stacks
SET cover_media_item_id = ?1,
    updated_at = ?2
WHERE stack_id = ?3
  AND (cover_media_item_id IS NULL OR cover_media_item_id <> ?1)
`

type UpdateStackCoverParams struct {
	CoverMediaItemID uuid.NullUUID     `db:"cover_media_item_id" json:"cover_media_item_id"`
	UpdatedAt        dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
	StackID          uuid.UUID         `db:"stack_id" json:"stack_id"`
}

func (q *Queries) UpdateStackCover(ctx context.Context, arg UpdateStackCoverParams) error {
	_, err := q.db.ExecContext(ctx, updateStackCover, arg.CoverMediaItemID, arg.UpdatedAt, arg.StackID)
	return err
}

const updateStackMemberPosition = `-- name: UpdateStackMemberPosition :exec
UPDATE asset_stack_members
SET position = ?1
WHERE stack_id = ?2
  AND media_item_id = ?3
  AND position <> ?1
`

type UpdateStackMemberPositionParams struct {
	Position    int64     `db:"position" json:"position"`
	StackID     uuid.UUID `db:"stack_id" json:"stack_id"`
	MediaItemID uuid.UUID `db:"media_item_id" json:"media_item_id"`
}

func (q *Queries) UpdateStackMemberPosition(ctx context.Context, arg UpdateStackMemberPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateStackMemberPosition, arg.Position, arg.StackID, arg.MediaItemID)
	return err
}
