// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stats_03.sql

package repo

import (
	"context"
)

const getTimeDistributionMonthly = `-- name: GetTimeDistributionMonthly :many
SELECT
    strftime('%Y-%m', COALESCE(a.taken_time, a.upload_time) / 1000000, 'unixepoch') AS month,
    COUNT(*) AS count
FROM assets a
WHERE
    a.is_deleted = false
    AND (?1 IS NULL OR EXISTS (
      SELECT 1 FROM active_asset_occurrences occurrence
      WHERE occurrence.asset_id = a.asset_id
        AND occurrence.repository_id = ?1
    ))
    AND (a.taken_time IS NOT NULL OR a.upload_time IS NOT NULL)
GROUP BY month
ORDER BY month DESC
LIMIT 24
`

type GetTimeDistributionMonthlyRow struct {
	Month interface{} `db:"month" json:"month"`
	Count int64       `db:"count" json:"count"`
}

func (q *Queries) GetTimeDistributionMonthly(ctx context.Context, repositoryID interface{}) ([]GetTimeDistributionMonthlyRow, error) {
	rows, err := q.db.QueryContext(ctx, getTimeDistributionMonthly, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTimeDistributionMonthlyRow
	for rows.Next() {
		var i GetTimeDistributionMonthlyRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
