// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stats.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvailableYears = `-- name: GetAvailableYears :many
SELECT DISTINCT
    EXTRACT(YEAR FROM COALESCE(taken_time, upload_time))::integer AS year
FROM assets
WHERE
    is_deleted = false
    AND (taken_time IS NOT NULL OR upload_time IS NOT NULL)
ORDER BY year DESC
`

// 获取所有有照片的年份列表
func (q *Queries) GetAvailableYears(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, getAvailableYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var year int32
		if err := rows.Scan(&year); err != nil {
			return nil, err
		}
		items = append(items, year)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCameraLensStats = `-- name: GetCameraLensStats :many
SELECT
    specific_metadata->>'camera_model' AS camera_model,
    specific_metadata->>'lens_model' AS lens_model,
    COUNT(*) AS count
FROM assets
WHERE
    is_deleted = false
    AND specific_metadata->>'camera_model' IS NOT NULL
    AND specific_metadata->>'camera_model' != ''
    AND specific_metadata->>'lens_model' IS NOT NULL
    AND specific_metadata->>'lens_model' != ''
GROUP BY camera_model, lens_model
ORDER BY count DESC
LIMIT $1
`

type GetCameraLensStatsRow struct {
	CameraModel interface{} `db:"camera_model" json:"camera_model"`
	LensModel   interface{} `db:"lens_model" json:"lens_model"`
	Count       int64       `db:"count" json:"count"`
}

// 获取相机+镜头组合统计
func (q *Queries) GetCameraLensStats(ctx context.Context, limit int32) ([]GetCameraLensStatsRow, error) {
	rows, err := q.db.Query(ctx, getCameraLensStats, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCameraLensStatsRow
	for rows.Next() {
		var i GetCameraLensStatsRow
		if err := rows.Scan(&i.CameraModel, &i.LensModel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyActivityHeatmap = `-- name: GetDailyActivityHeatmap :many
SELECT
    DATE(COALESCE(taken_time, upload_time)) AS date,
    COUNT(*) AS count
FROM assets
WHERE
    is_deleted = false
    AND (taken_time IS NOT NULL OR upload_time IS NOT NULL)
    AND COALESCE(taken_time, upload_time) >= $1
    AND COALESCE(taken_time, upload_time) <= $2
GROUP BY date
ORDER BY date
`

type GetDailyActivityHeatmapParams struct {
	TakenTime   pgtype.Timestamptz `db:"taken_time" json:"taken_time"`
	TakenTime_2 pgtype.Timestamptz `db:"taken_time_2" json:"taken_time_2"`
}

type GetDailyActivityHeatmapRow struct {
	Date  pgtype.Date `db:"date" json:"date"`
	Count int64       `db:"count" json:"count"`
}

// 获取每日拍摄活跃度热力图数据
func (q *Queries) GetDailyActivityHeatmap(ctx context.Context, arg GetDailyActivityHeatmapParams) ([]GetDailyActivityHeatmapRow, error) {
	rows, err := q.db.Query(ctx, getDailyActivityHeatmap, arg.TakenTime, arg.TakenTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyActivityHeatmapRow
	for rows.Next() {
		var i GetDailyActivityHeatmapRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFocalLengthDistribution = `-- name: GetFocalLengthDistribution :many
SELECT
    (specific_metadata->>'focal_length')::numeric AS focal_length,
    COUNT(*) AS count
FROM assets
WHERE
    is_deleted = false
    AND specific_metadata->>'focal_length' IS NOT NULL
    AND specific_metadata->>'focal_length' != ''
    AND (specific_metadata->>'focal_length')::numeric > 0
GROUP BY focal_length
ORDER BY count DESC
LIMIT 50
`

type GetFocalLengthDistributionRow struct {
	FocalLength pgtype.Numeric `db:"focal_length" json:"focal_length"`
	Count       int64          `db:"count" json:"count"`
}

// 获取焦距分布统计
func (q *Queries) GetFocalLengthDistribution(ctx context.Context) ([]GetFocalLengthDistributionRow, error) {
	rows, err := q.db.Query(ctx, getFocalLengthDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFocalLengthDistributionRow
	for rows.Next() {
		var i GetFocalLengthDistributionRow
		if err := rows.Scan(&i.FocalLength, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeDistributionHourly = `-- name: GetTimeDistributionHourly :many
SELECT
    EXTRACT(HOUR FROM COALESCE(taken_time, upload_time))::integer AS hour,
    COUNT(*) AS count
FROM assets
WHERE
    is_deleted = false
    AND (taken_time IS NOT NULL OR upload_time IS NOT NULL)
GROUP BY hour
ORDER BY hour
`

type GetTimeDistributionHourlyRow struct {
	Hour  int32 `db:"hour" json:"hour"`
	Count int64 `db:"count" json:"count"`
}

// 获取按小时的拍摄时间分布
func (q *Queries) GetTimeDistributionHourly(ctx context.Context) ([]GetTimeDistributionHourlyRow, error) {
	rows, err := q.db.Query(ctx, getTimeDistributionHourly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTimeDistributionHourlyRow
	for rows.Next() {
		var i GetTimeDistributionHourlyRow
		if err := rows.Scan(&i.Hour, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeDistributionMonthly = `-- name: GetTimeDistributionMonthly :many
SELECT
    DATE_TRUNC('month', COALESCE(taken_time, upload_time))::timestamp AS month,
    COUNT(*) AS count
FROM assets
WHERE
    is_deleted = false
    AND (taken_time IS NOT NULL OR upload_time IS NOT NULL)
GROUP BY month
ORDER BY month DESC
LIMIT 24
`

type GetTimeDistributionMonthlyRow struct {
	Month pgtype.Timestamp `db:"month" json:"month"`
	Count int64            `db:"count" json:"count"`
}

// 获取按月的拍摄时间分布
func (q *Queries) GetTimeDistributionMonthly(ctx context.Context) ([]GetTimeDistributionMonthlyRow, error) {
	rows, err := q.db.Query(ctx, getTimeDistributionMonthly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTimeDistributionMonthlyRow
	for rows.Next() {
		var i GetTimeDistributionMonthlyRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
