// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stats_02.sql

package repo

import (
	"context"
)

const getTimeDistributionHourly = `-- name: GetTimeDistributionHourly :many
SELECT
    CAST(strftime('%H', COALESCE(a.taken_time, a.upload_time) / 1000000, 'unixepoch') AS INTEGER) AS hour,
    COUNT(*) AS count
FROM assets a
WHERE
    a.is_deleted = false
    AND (?1 IS NULL OR EXISTS (
      SELECT 1 FROM active_asset_occurrences occurrence
      WHERE occurrence.asset_id = a.asset_id
        AND occurrence.repository_id = ?1
    ))
    AND (a.taken_time IS NOT NULL OR a.upload_time IS NOT NULL)
GROUP BY hour
ORDER BY hour
`

type GetTimeDistributionHourlyRow struct {
	Hour  int64 `db:"hour" json:"hour"`
	Count int64 `db:"count" json:"count"`
}

func (q *Queries) GetTimeDistributionHourly(ctx context.Context, repositoryID interface{}) ([]GetTimeDistributionHourlyRow, error) {
	rows, err := q.db.QueryContext(ctx, getTimeDistributionHourly, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTimeDistributionHourlyRow
	for rows.Next() {
		var i GetTimeDistributionHourlyRow
		if err := rows.Scan(&i.Hour, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
