// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: storage_locations.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"server/internal/db/dbtypes"
)

const deleteExternalStorageLocation = `-- name: DeleteExternalStorageLocation :execrows
DELETE FROM storage_locations
WHERE storage_locations.storage_location_id = ?1
  AND storage_locations.kind = 'external'
  AND NOT EXISTS (
      SELECT 1 FROM repositories WHERE repositories.storage_location_id = storage_locations.storage_location_id
  )
`

func (q *Queries) DeleteExternalStorageLocation(ctx context.Context, storageLocationID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExternalStorageLocation, storageLocationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDefaultStorageLocation = `-- name: GetDefaultStorageLocation :one
SELECT storage_location_id, name, path, kind, status, mount_fingerprint, created_at, updated_at FROM storage_locations
WHERE kind = 'default'
`

func (q *Queries) GetDefaultStorageLocation(ctx context.Context) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, getDefaultStorageLocation)
	var i StorageLocation
	err := row.Scan(
		&i.StorageLocationID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.MountFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageLocation = `-- name: GetStorageLocation :one
SELECT storage_location_id, name, path, kind, status, mount_fingerprint, created_at, updated_at FROM storage_locations
WHERE storage_location_id = ?1
`

func (q *Queries) GetStorageLocation(ctx context.Context, storageLocationID uuid.UUID) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, getStorageLocation, storageLocationID)
	var i StorageLocation
	err := row.Scan(
		&i.StorageLocationID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.MountFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageLocationByPath = `-- name: GetStorageLocationByPath :one
SELECT storage_location_id, name, path, kind, status, mount_fingerprint, created_at, updated_at FROM storage_locations
WHERE path = ?1
`

func (q *Queries) GetStorageLocationByPath(ctx context.Context, path string) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, getStorageLocationByPath, path)
	var i StorageLocation
	err := row.Scan(
		&i.StorageLocationID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.MountFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStorageLocations = `-- name: ListStorageLocations :many
SELECT storage_location_id, name, path, kind, status, mount_fingerprint, created_at, updated_at FROM storage_locations
ORDER BY kind ASC, created_at ASC
`

func (q *Queries) ListStorageLocations(ctx context.Context) ([]StorageLocation, error) {
	rows, err := q.db.QueryContext(ctx, listStorageLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageLocation
	for rows.Next() {
		var i StorageLocation
		if err := rows.Scan(
			&i.StorageLocationID,
			&i.Name,
			&i.Path,
			&i.Kind,
			&i.Status,
			&i.MountFingerprint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStorageLocationFromDisk = `-- name: UpdateStorageLocationFromDisk :one
UPDATE storage_locations
SET
    name = ?2,
    status = ?3,
    updated_at = ?4
WHERE storage_location_id = ?1
RETURNING storage_location_id, name, path, kind, status, mount_fingerprint, created_at, updated_at
`

type UpdateStorageLocationFromDiskParams struct {
	StorageLocationID uuid.UUID                     `db:"storage_location_id" json:"storage_location_id"`
	Name              string                        `db:"name" json:"name"`
	Status            dbtypes.StorageLocationStatus `db:"status" json:"status"`
	UpdatedAt         dbtypes.Timestamp             `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateStorageLocationFromDisk(ctx context.Context, arg UpdateStorageLocationFromDiskParams) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, updateStorageLocationFromDisk,
		arg.StorageLocationID,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
	)
	var i StorageLocation
	err := row.Scan(
		&i.StorageLocationID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.MountFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStorageLocationMountFingerprint = `-- name: UpdateStorageLocationMountFingerprint :one
UPDATE storage_locations
SET mount_fingerprint = ?2, updated_at = ?3
WHERE storage_location_id = ?1
RETURNING storage_location_id, name, path, kind, status, mount_fingerprint, created_at, updated_at
`

type UpdateStorageLocationMountFingerprintParams struct {
	StorageLocationID uuid.UUID         `db:"storage_location_id" json:"storage_location_id"`
	MountFingerprint  string            `db:"mount_fingerprint" json:"mount_fingerprint"`
	UpdatedAt         dbtypes.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateStorageLocationMountFingerprint(ctx context.Context, arg UpdateStorageLocationMountFingerprintParams) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, updateStorageLocationMountFingerprint, arg.StorageLocationID, arg.MountFingerprint, arg.UpdatedAt)
	var i StorageLocation
	err := row.Scan(
		&i.StorageLocationID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.MountFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStorageLocation = `-- name: UpsertStorageLocation :one
INSERT INTO storage_locations (
    storage_location_id,
    name,
    path,
    kind,
    status,
    mount_fingerprint,
    created_at,
    updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)
ON CONFLICT (storage_location_id) DO UPDATE SET
    name = EXCLUDED.name,
    path = EXCLUDED.path,
    kind = EXCLUDED.kind,
    status = EXCLUDED.status,
    mount_fingerprint = CASE
        WHEN storage_locations.mount_fingerprint = '' THEN EXCLUDED.mount_fingerprint
        ELSE storage_locations.mount_fingerprint
    END,
    updated_at = EXCLUDED.updated_at
RETURNING storage_location_id, name, path, kind, status, mount_fingerprint, created_at, updated_at
`

type UpsertStorageLocationParams struct {
	StorageLocationID uuid.UUID                     `db:"storage_location_id" json:"storage_location_id"`
	Name              string                        `db:"name" json:"name"`
	Path              string                        `db:"path" json:"path"`
	Kind              dbtypes.StorageLocationKind   `db:"kind" json:"kind"`
	Status            dbtypes.StorageLocationStatus `db:"status" json:"status"`
	MountFingerprint  string                        `db:"mount_fingerprint" json:"mount_fingerprint"`
	CreatedAt         dbtypes.Timestamp             `db:"created_at" json:"created_at"`
	UpdatedAt         dbtypes.Timestamp             `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertStorageLocation(ctx context.Context, arg UpsertStorageLocationParams) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, upsertStorageLocation,
		arg.StorageLocationID,
		arg.Name,
		arg.Path,
		arg.Kind,
		arg.Status,
		arg.MountFingerprint,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i StorageLocation
	err := row.Scan(
		&i.StorageLocationID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.Status,
		&i.MountFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
