// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: system_state.sql

package repo

import (
	"context"
)

const getSystemState = `-- name: GetSystemState :one
SELECT id, library_id, bootstrap_phase, updated_at FROM system_state
WHERE id = 1
`

func (q *Queries) GetSystemState(ctx context.Context) (SystemState, error) {
	row := q.db.QueryRowContext(ctx, getSystemState)
	var i SystemState
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.BootstrapPhase,
		&i.UpdatedAt,
	)
	return i, err
}

const setBootstrapPhase = `-- name: SetBootstrapPhase :one
UPDATE system_state
SET
    bootstrap_phase = ?1,
    updated_at = CAST(unixepoch('subsec') * 1000000 AS INTEGER)
WHERE id = 1
RETURNING id, library_id, bootstrap_phase, updated_at
`

func (q *Queries) SetBootstrapPhase(ctx context.Context, bootstrapPhase string) (SystemState, error) {
	row := q.db.QueryRowContext(ctx, setBootstrapPhase, bootstrapPhase)
	var i SystemState
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.BootstrapPhase,
		&i.UpdatedAt,
	)
	return i, err
}
