name = "lumilio-plugin-registry"
main = "src/index.ts"
compatibility_date = "2026-02-13"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "*"

[[d1_databases]]
binding = "DB"
database_name = "lumilio_plugin_registry"
database_id = "a5e886fb-a72c-4da5-a33a-f5168b92a1fb"

[[kv_namespaces]]
binding = "CACHE"
id = "31e40098afd2422db2b67cbf94a20072"
preview_id = "31e40098afd2422db2b67cbf94a20072"

[[r2_buckets]]
binding = "ARTIFACTS"
bucket_name = "lumilio-plugin-artifacts"
preview_bucket_name = "lumilio-plugin-artifacts-preview"
