package supervisor

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"strings"
)

// DesktopSettings are user choices that must persist across launches. It is the
// source of truth for those choices because server.local.toml is regenerated on
// every launch and therefore cannot hold persisted state.
type DesktopSettings struct {
	// StoragePath is the user-chosen media library location. Empty means "use
	// the default" (<appdata>/storage), resolved at startup.
	StoragePath string `json:"storage_path,omitempty"`
}

// LoadSettings reads desktop-settings.json. A missing file yields zero-value
// settings (first run) rather than an error.
func LoadSettings(path string) (DesktopSettings, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return DesktopSettings{}, nil
		}
		return DesktopSettings{}, fmt.Errorf("read desktop settings: %w", err)
	}
	var s DesktopSettings
	if err := json.Unmarshal(data, &s); err != nil {
		return DesktopSettings{}, fmt.Errorf("parse desktop settings: %w", err)
	}
	return s, nil
}

// SaveSettings persists desktop-settings.json atomically.
func SaveSettings(path string, s DesktopSettings) error {
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal desktop settings: %w", err)
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o600); err != nil {
		return fmt.Errorf("write desktop settings: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("replace desktop settings: %w", err)
	}
	return nil
}

// ensureSecret writes a fresh 32-byte cryptographically random hex secret to
// path if the file is missing or empty. Existing secrets are preserved so keys
// remain stable across launches.
func ensureSecret(path string) error {
	if info, err := os.Stat(path); err == nil && info.Size() > 0 {
		return nil
	}
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return fmt.Errorf("generate secret: %w", err)
	}
	if err := os.WriteFile(path, []byte(hex.EncodeToString(buf)), 0o600); err != nil {
		return fmt.Errorf("write secret %s: %w", path, err)
	}
	return nil
}

// ServerConfigParams is everything needed to render server.local.toml for the
// desktop runtime.
type ServerConfigParams struct {
	Port          string
	WebRoot       string // empty → API only (no SPA served)
	LogDir        string
	StoragePath   string
	SocketDir     string
	PGPort        string
	DBUser        string
	DBName        string
	PasswordFile  string
	SecretKeyPath string
	ExifToolPath  string // empty → server resolves via PATH
	FFmpegPath    string
	FFprobePath   string
}

// WriteServerConfig renders and writes server.local.toml. This file is rewritten
// on every launch; persisted user choices live in desktop-settings.json instead.
//
// WebAuthn RP id/origin are pinned to localhost:6680 — a hard requirement for
// passkeys in the desktop webview (see the exec plan's WebAuthn constraints).
func WriteServerConfig(path string, p ServerConfigParams) error {
	toml := fmt.Sprintf(`# Generated by Lumilio Photos desktop supervisor on every launch.
# Do not edit by hand; persisted user choices live in desktop-settings.json.
environment = "production"

[server]
port = %s
log_level = "info"
cors_allowed_origins = ["http://localhost:6657"]
web_root = %s

[logging]
level = "info"
dir = %s
console_format = "console"
file_format = "json"

[database]
host = %s
port = %s
user = %s
password_file = %s
name = %s
ssl = "disable"

[storage]
path = %s

[ml]
semantic_enabled = true
bioclip_enabled = true
ocr_enabled = true
face_enabled = true

[auth]
secret_key_path = %s
webauthn_rp_id = "localhost"
webauthn_rp_origins = ["http://localhost:%s"]

[lumen]
discovery_enabled = true
discovery_mdns_enabled = true
discovery_hub_url = ""

[tools]
exiftool_path = %s
ffmpeg_path = %s
ffprobe_path = %s
`,
		tomlString(p.Port),
		tomlString(p.WebRoot),
		tomlString(p.LogDir),
		tomlString(p.SocketDir),
		tomlString(p.PGPort),
		tomlString(p.DBUser),
		tomlString(p.PasswordFile),
		tomlString(p.DBName),
		tomlString(p.StoragePath),
		tomlString(p.SecretKeyPath),
		p.Port,
		tomlString(p.ExifToolPath),
		tomlString(p.FFmpegPath),
		tomlString(p.FFprobePath),
	)

	if err := os.WriteFile(path, []byte(toml), 0o600); err != nil {
		return fmt.Errorf("write server config: %w", err)
	}
	return nil
}

// tomlString renders a Go string as a TOML basic string literal, escaping the
// characters that are significant inside double quotes.
func tomlString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}
