package supervisor

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

// Postgres manages the lifecycle of the private, bundled PostgreSQL instance:
// initdb, configuration, start/stop, readiness, and database creation. On unix
// it only ever speaks over a Unix socket (no TCP port is opened), so it cannot
// collide with a system PostgreSQL or be reached from the network. Windows
// PostgreSQL has no Unix sockets, so there the postmaster binds the IPv4
// loopback only (127.0.0.1:<port>).
type Postgres struct {
	binDir       string // directory containing initdb/pg_ctl/postgres/pg_isready/createdb
	dataDir      string
	host         string // unix socket directory, or 127.0.0.1 on Windows
	logsDir      string
	port         string
	user         string
	dbName       string
	passwordFile string
	logf         func(string, ...any)
}

// PostgresOptions configures a Postgres controller.
type PostgresOptions struct {
	BinDir  string
	DataDir string
	// Host is the connection target: a Unix socket directory on unix hosts,
	// or 127.0.0.1 on Windows (use Paths.DBHost).
	Host         string
	LogsDir      string
	Port         string
	User         string
	DBName       string
	PasswordFile string
	Logf         func(string, ...any)
}

// NewPostgres builds a Postgres controller from options, filling in defaults.
func NewPostgres(opts PostgresOptions) *Postgres {
	logf := opts.Logf
	if logf == nil {
		logf = func(string, ...any) {}
	}
	port := opts.Port
	if port == "" {
		port = pgPort
	}
	return &Postgres{
		binDir:       opts.BinDir,
		dataDir:      opts.DataDir,
		host:         opts.Host,
		logsDir:      opts.LogsDir,
		port:         port,
		user:         opts.User,
		dbName:       opts.DBName,
		passwordFile: opts.PasswordFile,
		logf:         logf,
	}
}

func (p *Postgres) bin(name string) string {
	if runtime.GOOS == "windows" {
		name += ".exe"
	}
	return filepath.Join(p.binDir, name)
}

// IsInitialized reports whether dataDir already contains an initialized cluster.
func (p *Postgres) IsInitialized() bool {
	_, err := os.Stat(filepath.Join(p.dataDir, "PG_VERSION"))
	return err == nil
}

// DataVersion returns the major version recorded in the data directory's
// PG_VERSION file, or "" if the cluster is not initialized. Used to detect a
// bundled-vs-data major mismatch that requires a dump/restore upgrade.
func (p *Postgres) DataVersion() string {
	data, err := os.ReadFile(filepath.Join(p.dataDir, "PG_VERSION"))
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(data))
}

// InitDB initializes a fresh cluster owned by the configured user, trusting
// local connections (no password over the Unix socket).
func (p *Postgres) InitDB(ctx context.Context) error {
	p.logf("initdb: initializing cluster at %s", p.dataDir)
	return p.run(ctx, "initdb",
		"-D", p.dataDir,
		"-U", p.user,
		"--auth=trust",
		"--encoding=UTF8",
		"--locale=C",
	)
}

// WriteConfigs (over)writes postgresql.conf and pg_hba.conf. postgresql.conf is
// rewritten every launch so settings (especially the socket directory, which
// may fall back to /tmp) stay in sync with the resolved paths.
func (p *Postgres) WriteConfigs() error {
	if runtime.GOOS != "windows" {
		if err := os.MkdirAll(p.host, 0o700); err != nil {
			return fmt.Errorf("create socket dir %s: %w", p.host, err)
		}
	}
	if err := os.MkdirAll(p.logsDir, 0o700); err != nil {
		return fmt.Errorf("create logs dir %s: %w", p.logsDir, err)
	}

	conf := fmt.Sprintf(`# Generated by Lumilio Photos desktop supervisor. Do not edit by hand.
%s
port = %s
shared_buffers = 64MB
work_mem = 4MB
maintenance_work_mem = 16MB
# Comfortably above the API connection pool (sized to CPU count) plus River's
# per-queue producers and PostgreSQL's reserved superuser connections. The
# plan's original 10 caused transient "too many clients" errors at startup.
max_connections = 50
wal_level = minimal
max_wal_senders = 0
logging_collector = on
log_directory = '%s'
log_filename = 'postgresql-%%Y-%%m-%%d.log'
log_rotation_age = 1d
log_rotation_size = 10MB
`, pgListenConf(runtime.GOOS, p.host), p.port, pgConfEscape(p.logsDir))

	if err := os.WriteFile(filepath.Join(p.dataDir, "postgresql.conf"), []byte(conf), 0o600); err != nil {
		return fmt.Errorf("write postgresql.conf: %w", err)
	}

	if err := os.WriteFile(filepath.Join(p.dataDir, "pg_hba.conf"), []byte(pgHBAConf(runtime.GOOS)), 0o600); err != nil {
		return fmt.Errorf("write pg_hba.conf: %w", err)
	}
	return nil
}

// pgListenConf returns the listener configuration: unix hosts speak only over
// the Unix socket (no TCP), Windows binds the IPv4 loopback only because its
// PostgreSQL builds have no Unix socket support.
func pgListenConf(goos, host string) string {
	if goos == "windows" {
		return "listen_addresses = '127.0.0.1'"
	}
	return fmt.Sprintf("listen_addresses = ''\nunix_socket_directories = '%s'", pgConfEscape(host))
}

// pgHBAConf returns client auth rules matching the listener setup: socket-only
// trust on unix, loopback-only trust on Windows ("local" lines are rejected by
// Unix-socket-less builds).
func pgHBAConf(goos string) string {
	if goos == "windows" {
		return "# Generated by Lumilio Photos desktop supervisor.\n" +
			"host   all   all   127.0.0.1/32   trust\n"
	}
	return "# Generated by Lumilio Photos desktop supervisor.\nlocal   all   all   trust\n"
}

// HandleStaleState recovers from a previous unclean shutdown (force quit or
// crash) by either stopping a still-running leftover postmaster or clearing a
// stale postmaster.pid so a fresh start is not refused.
func (p *Postgres) HandleStaleState(ctx context.Context) error {
	pidFile := filepath.Join(p.dataDir, "postmaster.pid")
	if _, err := os.Stat(pidFile); err != nil {
		return nil // no pid file, nothing to recover
	}

	switch p.statusCode(ctx) {
	case 0:
		// Still running from a previous session; stop it cleanly.
		p.logf("recovery: leftover postgres is running, stopping")
		return p.Stop(ctx)
	default:
		// Not running but pid file present → stale; remove it.
		p.logf("recovery: removing stale postmaster.pid")
		if err := os.Remove(pidFile); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove stale pid file: %w", err)
		}
		return nil
	}
}

// statusCode returns the pg_ctl status exit code (0 = running, 3 = not running,
// 4 = bad data dir). Any non-ExitError is treated as "not running".
func (p *Postgres) statusCode(ctx context.Context) int {
	cmd := exec.CommandContext(ctx, p.bin("pg_ctl"), "status", "-D", p.dataDir)
	if err := cmd.Run(); err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			return exitErr.ExitCode()
		}
		return 3
	}
	return 0
}

// Start launches the postmaster and waits (pg_ctl -w) for it to accept
// connections.
func (p *Postgres) Start(ctx context.Context) error {
	p.logf("postgres: starting")
	logPath := filepath.Join(p.logsDir, "postgres.log")
	out, err := p.output(ctx, "pg_ctl",
		"start",
		"-D", p.dataDir,
		"-l", logPath,
		"-w",
		"-t", "60",
	)
	if err == nil {
		return nil
	}
	// pg_ctl's own failure message is only "could not start server / Examine
	// the log output"; the actual postmaster error lives in postgres.log. Fold
	// its tail into the error so the real cause is visible without hunting for
	// the log file (which the setup UI cannot open).
	msg := strings.TrimSpace(out)
	if tail := tailFile(logPath, 4096); tail != "" {
		msg = strings.TrimSpace(msg + "\n--- postgres.log ---\n" + tail)
	}
	return fmt.Errorf("pg_ctl start: %w\n%s", err, msg)
}

// tailFile returns up to maxBytes of the end of the file at path, or "" if it
// cannot be read. Used to surface the postmaster log tail on a start failure.
func tailFile(path string, maxBytes int64) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil {
		return ""
	}
	if size := info.Size(); size > maxBytes {
		if _, err := f.Seek(size-maxBytes, 0); err != nil {
			return ""
		}
	}
	data, err := io.ReadAll(f)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(data))
}

// Stop performs a fast shutdown (rollback in-flight, then exit) bounded by a
// timeout.
func (p *Postgres) Stop(ctx context.Context) error {
	p.logf("postgres: stopping")
	return p.run(ctx, "pg_ctl",
		"stop",
		"-D", p.dataDir,
		"-m", "fast",
		"-w",
		"-t", "30",
	)
}

// WaitReady polls pg_isready with exponential backoff until the server accepts
// connections or the timeout elapses.
func (p *Postgres) WaitReady(ctx context.Context, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	backoff := 100 * time.Millisecond
	var lastErr error
	for {
		if err := p.isReady(ctx); err == nil {
			p.logf("postgres: ready")
			return nil
		} else {
			lastErr = err
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("postgres not ready after %s: %w", timeout, lastErr)
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(backoff):
		}
		if backoff < 2*time.Second {
			backoff *= 2
		}
	}
}

func (p *Postgres) isReady(ctx context.Context) error {
	return exec.CommandContext(ctx, p.bin("pg_isready"),
		"-h", p.host,
		"-p", p.port,
	).Run()
}

// CreateDB creates the application database if it does not already exist. It is
// idempotent: an "already exists" failure from createdb is treated as success.
func (p *Postgres) CreateDB(ctx context.Context) error {
	out, err := p.output(ctx, "createdb",
		"-h", p.host,
		"-p", p.port,
		"-U", p.user,
		p.dbName,
	)
	if err == nil {
		p.logf("createdb: created database %q", p.dbName)
		return nil
	}
	if strings.Contains(out, "already exists") {
		return nil
	}
	return fmt.Errorf("createdb %q: %w (%s)", p.dbName, err, strings.TrimSpace(out))
}

// run executes a bundled binary, surfacing combined output on failure.
func (p *Postgres) run(ctx context.Context, name string, args ...string) error {
	out, err := p.output(ctx, name, args...)
	if err != nil {
		return fmt.Errorf("%s: %w\n%s", name, err, strings.TrimSpace(out))
	}
	return nil
}

func (p *Postgres) output(ctx context.Context, name string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, p.bin(name), args...)
	// Force the C locale for messages so the PostgreSQL tools emit English
	// ASCII rather than the OS-locale encoding (e.g. GBK on a Chinese Windows),
	// which would render as mojibake in the setup UI. The cluster's own
	// encoding/locale is fixed at initdb time (--encoding=UTF8 --locale=C) and
	// is unaffected by these message-only overrides.
	cmd.Env = append(os.Environ(), "LC_ALL=C", "LC_MESSAGES=C", "LANG=C")
	var buf bytes.Buffer
	cmd.Stdout = &buf
	cmd.Stderr = &buf
	err := cmd.Run()
	return buf.String(), err
}

// pgConfEscape escapes single quotes for a PostgreSQL configuration string value.
func pgConfEscape(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}
