-- Semantic search vectors move out of the polymorphic, dimensionless
-- `embeddings` table into a dedicated fixed-dimension, ANN-indexable store.
--
-- Rationale: pgvector HNSW/IVFFlat require a fixed dimension, which the
-- dimensionless `embeddings.vector` column cannot provide, so semantic search
-- ran as a brute-force exact scan. We have standardized on SigLIP2 (Matryoshka),
-- so every model output is truncated + L2-normalized to CanonicalEmbeddingDim
-- (768) on write. That lets one cosine HNSW index serve every model and keeps
-- the schema stable across model swaps (a swap is a full re-embed, not a column
-- migration).
--
-- The table is multi-row per asset: photos have one row (frame_ts_ms IS NULL);
-- videos have one row per sampled frame (frame_ts_ms set). pHash and other
-- attribute vectors stay in the generic `embeddings` table, unchanged.

CREATE TABLE public.search_embeddings (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id    uuid NOT NULL REFERENCES public.assets(asset_id) ON DELETE CASCADE,
    space_id    bigint NOT NULL REFERENCES public.embedding_spaces(id) ON DELETE RESTRICT,
    frame_ts_ms integer,
    vector      vector(768) NOT NULL,
    model_id    varchar(100) NOT NULL,
    created_at  timestamp with time zone DEFAULT now()
);

-- One primary (photo / whole-asset) row per asset; unique frames per asset.
CREATE UNIQUE INDEX search_embeddings_asset_primary_uniq
    ON public.search_embeddings (asset_id)
    WHERE frame_ts_ms IS NULL;

CREATE UNIQUE INDEX search_embeddings_asset_frame_uniq
    ON public.search_embeddings (asset_id, frame_ts_ms)
    WHERE frame_ts_ms IS NOT NULL;

CREATE INDEX search_embeddings_asset_idx
    ON public.search_embeddings (asset_id);

-- Single HNSW over the whole table: drop+refill on model swap guarantees every
-- live row comes from one model, so no per-space partial index is needed. Vectors
-- are L2-normalized on write (canonicalizeSemanticVector), so L2 distance ranks
-- identically to cosine while keeping the existing strictness cutoff math
-- (cutoff = sqrt(2*(1-cosFloor))) exactly valid. Queries use the <-> operator.
CREATE INDEX search_embeddings_vector_hnsw_l2_idx
    ON public.search_embeddings
    USING hnsw (vector vector_l2_ops)
    WITH (m = 16, ef_construction = 200);
