-- AI Descriptions Table
-- Store AI-generated image descriptions

-- Create AI descriptions table
CREATE TABLE ai_descriptions (
    asset_id UUID NOT NULL REFERENCES assets(asset_id) ON DELETE CASCADE,
    model_id VARCHAR(100) NOT NULL,           -- AI model identifier
    description TEXT NOT NULL,                -- Generated description text
    summary TEXT,                             -- Brief summary of the description
    confidence REAL,                          -- Model confidence score (if available)
    tokens_generated INTEGER,                 -- Number of tokens generated
    processing_time_ms INTEGER,               -- Processing time in milliseconds
    prompt_used TEXT,                         -- The prompt used for generation
    finish_reason VARCHAR(50),                -- Generation finish reason
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (asset_id)
);

-- Indexes
CREATE INDEX ai_descriptions_asset_id_idx ON ai_descriptions(asset_id);
CREATE INDEX ai_descriptions_model_id_idx ON ai_descriptions(model_id);
CREATE INDEX ai_descriptions_created_at_idx ON ai_descriptions(created_at);
CREATE INDEX ai_descriptions_confidence_idx ON ai_descriptions(confidence) WHERE confidence IS NOT NULL;

-- Full-text search index for descriptions
CREATE INDEX ai_descriptions_fulltext_idx ON ai_descriptions
USING GIN (to_tsvector('english', description));

-- Full-text search index for summaries
CREATE INDEX ai_descriptions_summary_fulltext_idx ON ai_descriptions
USING GIN (to_tsvector('english', summary)) WHERE summary IS NOT NULL;

-- Update timestamp trigger
CREATE OR REPLACE FUNCTION update_ai_description_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE ai_descriptions
    SET updated_at = CURRENT_TIMESTAMP
    WHERE asset_id = NEW.asset_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ai_description_update_trigger
    AFTER INSERT OR UPDATE ON ai_descriptions
    FOR EACH ROW
    EXECUTE FUNCTION update_ai_description_updated_at();

-- Constraints
ALTER TABLE ai_descriptions ADD CONSTRAINT chk_confidence_range
CHECK (confidence >= 0.0 AND confidence <= 1.0);

ALTER TABLE ai_descriptions ADD CONSTRAINT chk_tokens_positive
CHECK (tokens_generated >= 0);

ALTER TABLE ai_descriptions ADD CONSTRAINT chk_processing_time_positive
CHECK (processing_time_ms >= 0);

-- Comments
COMMENT ON TABLE ai_descriptions IS 'AI-generated image descriptions table, storing detailed descriptions and metadata';
COMMENT ON COLUMN ai_descriptions.model_id IS 'AI model identifier, such as "gpt-4-vision", "llava-v1.5", etc.';
COMMENT ON COLUMN ai_descriptions.description IS 'Generated detailed description of the image';
COMMENT ON COLUMN ai_descriptions.summary IS 'Brief summary of the description for quick display';
COMMENT ON COLUMN ai_descriptions.confidence IS 'Model confidence score, between 0.0-1.0';
COMMENT ON COLUMN ai_descriptions.tokens_generated IS 'Number of tokens generated by the model';
COMMENT ON COLUMN ai_descriptions.processing_time_ms IS 'Processing time in milliseconds';
COMMENT ON COLUMN ai_descriptions.prompt_used IS 'The prompt template used for generation';
COMMENT ON COLUMN ai_descriptions.finish_reason IS 'Generation finish reason, such as "stop", "length", "content_filter"';