-- Captions Table
-- Store generated image captions

-- Create captions table
CREATE TABLE captions (
    asset_id UUID NOT NULL REFERENCES assets(asset_id) ON DELETE CASCADE,
    model_id VARCHAR(100) NOT NULL,           -- AI model identifier
    description TEXT NOT NULL,                -- Generated description text
    summary TEXT,                             -- Brief summary of the description
    confidence REAL,                          -- Model confidence score (if available)
    tokens_generated INTEGER,                 -- Number of tokens generated
    processing_time_ms INTEGER,               -- Processing time in milliseconds
    prompt_used TEXT,                         -- The prompt used for generation
    finish_reason VARCHAR(50),                -- Generation finish reason
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (asset_id)
);

-- Indexes
CREATE INDEX captions_asset_id_idx ON captions(asset_id);
CREATE INDEX captions_model_id_idx ON captions(model_id);
CREATE INDEX captions_created_at_idx ON captions(created_at);
CREATE INDEX captions_confidence_idx ON captions(confidence) WHERE confidence IS NOT NULL;

-- Full-text search index for descriptions
CREATE INDEX captions_fulltext_idx ON captions
USING GIN (to_tsvector('english', description));

-- Full-text search index for summaries
CREATE INDEX captions_summary_fulltext_idx ON captions
USING GIN (to_tsvector('english', summary)) WHERE summary IS NOT NULL;

-- Update timestamp trigger
CREATE OR REPLACE FUNCTION update_caption_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE captions
    SET updated_at = CURRENT_TIMESTAMP
    WHERE asset_id = NEW.asset_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER caption_update_trigger
    AFTER INSERT OR UPDATE ON captions
    FOR EACH ROW
    EXECUTE FUNCTION update_caption_updated_at();

-- Constraints
ALTER TABLE captions ADD CONSTRAINT chk_confidence_range
CHECK (confidence >= 0.0 AND confidence <= 1.0);

ALTER TABLE captions ADD CONSTRAINT chk_tokens_positive
CHECK (tokens_generated >= 0);

ALTER TABLE captions ADD CONSTRAINT chk_processing_time_positive
CHECK (processing_time_ms >= 0);

-- Comments
COMMENT ON TABLE captions IS 'Generated image captions table, storing detailed captions and metadata';
COMMENT ON COLUMN captions.model_id IS 'AI model identifier, such as "gpt-4-vision", "llava-v1.5", etc.';
COMMENT ON COLUMN captions.description IS 'Generated detailed description of the image';
COMMENT ON COLUMN captions.summary IS 'Brief summary of the description for quick display';
COMMENT ON COLUMN captions.confidence IS 'Model confidence score, between 0.0-1.0';
COMMENT ON COLUMN captions.tokens_generated IS 'Number of tokens generated by the model';
COMMENT ON COLUMN captions.processing_time_ms IS 'Processing time in milliseconds';
COMMENT ON COLUMN captions.prompt_used IS 'The prompt template used for generation';
COMMENT ON COLUMN captions.finish_reason IS 'Generation finish reason, such as "stop", "length", "content_filter"';