[package]
name = "border-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["console"] }

[lib]
crate-type = ["cdylib", "rlib"]
