package lumen

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

const (
	PresetMinimal = "minimal"
	PresetBasic   = "basic"
	PresetBrave   = "brave"
)

// Preset mirrors lumen-launcher/setup.rs. The values are a small release
// contract, not a user-editable model configuration language.
type Preset struct {
	Name       string   `json:"name"`
	Components []string `json:"components"`
	MinRAMGB   uint64   `json:"minRamGB"`
	MinDiskGB  uint64   `json:"minDiskGB"`
	MinVRAMGB  uint64   `json:"minVramGB"`
}

var presets = []Preset{
	{Name: PresetMinimal, Components: []string{"siglip", "face"}, MinRAMGB: 4, MinVRAMGB: 2, MinDiskGB: 2},
	{Name: PresetBasic, Components: []string{"siglip", "face", "ocr", "bioclip"}, MinRAMGB: 6, MinVRAMGB: 3, MinDiskGB: 6},
	{Name: PresetBrave, Components: []string{"siglip", "face", "ocr", "bioclip"}, MinRAMGB: 8, MinVRAMGB: 4, MinDiskGB: 10},
}

func Presets() []Preset { return append([]Preset(nil), presets...) }

func PresetByName(name string) (Preset, bool) {
	for _, p := range presets {
		if p.Name == name {
			return p, true
		}
	}
	return Preset{}, false
}

// RecommendPreset returns the highest launcher preset whose RAM and disk
// guidance are met. Unknown measurements deliberately fall back to basic.
func RecommendPreset(ramGB, freeDiskGB float64) string {
	if ramGB <= 0 || freeDiskGB <= 0 {
		return PresetBasic
	}
	for i := len(presets) - 1; i >= 0; i-- {
		p := presets[i]
		if ramGB >= float64(p.MinRAMGB) && freeDiskGB >= float64(p.MinDiskGB) {
			return p.Name
		}
	}
	return PresetMinimal
}

type BackendChoice struct {
	Name        string `json:"name"`
	Profile     string `json:"profile"`
	Recommended bool   `json:"recommended,omitempty"`
}

func BackendChoicesFor(goos, goarch string) ([]BackendChoice, error) {
	switch goos + "/" + goarch {
	case "darwin/arm64":
		return []BackendChoice{{Name: "metal", Profile: "darwin-arm64-metal", Recommended: true}, {Name: "cpu", Profile: "darwin-arm64-cpu"}}, nil
	case "windows/amd64":
		return []BackendChoice{{Name: "gpu", Profile: "windows-x64-gpu", Recommended: true}, {Name: "cpu", Profile: "windows-x64-cpu"}}, nil
	default:
		return nil, fmt.Errorf("%w (%s/%s)", ErrUnsupportedHost, goos, goarch)
	}
}

func BackendChoicesForHost() ([]BackendChoice, error) {
	return BackendChoicesFor(runtime.GOOS, runtime.GOARCH)
}

type ConfigSelection struct {
	Preset   string
	Backend  string
	Profile  string
	CacheDir string
	Region   string
}

func DefaultConfigSelection(dir, lang string) (ConfigSelection, error) {
	choices, err := BackendChoicesForHost()
	if err != nil {
		return ConfigSelection{}, err
	}
	region := "other"
	if strings.HasPrefix(lang, "zh") {
		region = "cn"
	}
	return ConfigSelection{Preset: PresetBasic, Backend: choices[0].Name, Profile: choices[0].Profile, CacheDir: filepath.Join(dir, "models"), Region: region}, nil
}

func ValidateConfigSelection(s ConfigSelection) error {
	if _, ok := PresetByName(s.Preset); !ok {
		return fmt.Errorf("unknown Lumen preset %q", s.Preset)
	}
	choices, err := BackendChoicesForHost()
	if err != nil {
		return err
	}
	valid := false
	for _, c := range choices {
		if c.Name == s.Backend && c.Profile == s.Profile {
			valid = true
		}
	}
	if !valid {
		return fmt.Errorf("backend %q and profile %q are not compatible with this computer", s.Backend, s.Profile)
	}
	if strings.TrimSpace(s.CacheDir) == "" {
		return errors.New("model cache directory is required")
	}
	clean := filepath.Clean(s.CacheDir)
	if clean == filepath.VolumeName(clean)+string(os.PathSeparator) || clean == string(os.PathSeparator) {
		return errors.New("model cache directory cannot be a filesystem root")
	}
	if s.Region != "cn" && s.Region != "other" {
		return fmt.Errorf("unknown model download region %q", s.Region)
	}
	return nil
}

func WriteConfigFor(dir string, s ConfigSelection) error {
	if err := ValidateConfigSelection(s); err != nil {
		return err
	}
	if err := os.MkdirAll(s.CacheDir, 0o700); err != nil {
		return fmt.Errorf("create model cache: %w", err)
	}
	probe, err := os.CreateTemp(s.CacheDir, ".lumen-write-*")
	if err != nil {
		return fmt.Errorf("model cache is not writable: %w", err)
	}
	probe.Close()
	os.Remove(probe.Name())
	preset, _ := PresetByName(s.Preset)
	config := renderConfig(preset, s)
	return os.WriteFile(ConfigPath(dir), []byte(config), 0o600)
}

// WriteConfig preserves the old call site while migrating existing installs to
// launcher-compatible basic defaults.
func WriteConfig(dir, lang string) error {
	s, err := DefaultConfigSelection(dir, lang)
	if err != nil {
		return err
	}
	return WriteConfigFor(dir, s)
}

func renderConfig(p Preset, s ConfigSelection) string {
	services := "        - siglip\n        - face\n"
	if p.Name != PresetMinimal {
		services += "        - ocr\n        - bioclip\n"
	}
	siglipModel := "siglip2-base-patch16-224"
	if p.Name == PresetBrave {
		siglipModel = "siglip2-so400m-patch14-384"
	}
	config := fmt.Sprintf(`# Generated by Lumilio Photos desktop.
# Preset: %s (%s)
# Resource guidance: RAM %d GB, GPU/Unified memory %d GB, disk %d GB.
metadata:
    version: "0.1.0"
    region: %s
    cache_dir: %s

deployment:
    mode: hub
    services:
%s
server:
    host: "127.0.0.1"
    port: 50051
    batching:
        enabled: false
        max_batch_size: 8
        queue_latency_ms: 2

services:
    siglip:
        enabled: true
        package: siglip
        models:
            default:
                model: %s
                runtime: burn
                precision: fp16q8

    face:
        enabled: true
        package: insightface
        models:
            default:
                model: antelopev2
                runtime: burn
                precision: fp16q8
`, p.Name, strings.Join(p.Components, ", "), p.MinRAMGB, p.MinVRAMGB, p.MinDiskGB, s.Region, yamlQuote(s.CacheDir), services, siglipModel)
	if p.Name != PresetMinimal {
		config += `
    ocr:
        enabled: true
        package: ppocr
        models:
            default:
                model: pp-ocrv6-small
                runtime: burn
                precision: fp16q8

`
		dataset := "TreeOfLife200MCore"
		if p.Name == PresetBrave {
			dataset = "TreeOfLife200M"
		}
		config += fmt.Sprintf(`    bioclip:
        enabled: true
        package: clip
        models:
            default:
                model: bioclip-2
                runtime: burn
                precision: fp16q8
                dataset: %s
`, dataset)
	}
	return config
}

func ConfigPath(dir string) string { return filepath.Join(dir, "config.yaml") }
func yamlQuote(s string) string    { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }
