package lumen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteConfig regenerates the hub config, like the supervisor regenerates
// server.local.toml: launcher-owned, rewritten on every start so path changes
// self-heal. The service set mirrors what a Lumilio library uses out of the
// box (semantic search, faces, OCR); BioCLIP stays off (large catalog).
//
// The hub binds loopback only — this instance serves this machine; LAN serving
// is the CLI/Docker channels' job — and mDNS stays off: the desktop server
// config pins the endpoint as a static node instead, which is deterministic
// and doesn't advertise a loopback address to the network.
//
// lang is the desktop UI language: "zh" selects region cn so model downloads
// use the HF mirror (overridable by editing config.yaml before a start).
func WriteConfig(dir, lang string) error {
	region := "other"
	if strings.HasPrefix(lang, "zh") {
		region = "cn"
	}
	cacheDir := filepath.Join(dir, "models")

	config := fmt.Sprintf(`# Generated by Lumilio Photos desktop. Rewritten on every start.
metadata:
    version: "0.1.0"
    region: %s
    cache_dir: %s

deployment:
    mode: hub
    services:
        - siglip
        - face
        - ocr

server:
    host: "127.0.0.1"
    port: 50051
    batching:
        enabled: false
        max_batch_size: 8
        queue_latency_ms: 2

services:
    siglip:
        enabled: true
        package: siglip
        models:
            default:
                model: siglip2-base-patch16-224
                runtime: burn
                precision: fp16q8

    face:
        enabled: true
        package: insightface
        models:
            default:
                model: antelopev2
                runtime: burn
                precision: fp16q8

    ocr:
        enabled: true
        package: ppocr
        models:
            default:
                model: pp-ocrv6-small
                runtime: burn
                precision: fp16q8
`, region, yamlQuote(cacheDir))

	return os.WriteFile(ConfigPath(dir), []byte(config), 0o600)
}

// ConfigPath is where WriteConfig puts the generated hub config.
func ConfigPath(dir string) string { return filepath.Join(dir, "config.yaml") }

// yamlQuote single-quotes a string for YAML (Windows paths contain backslashes
// that double-quoted YAML would treat as escapes).
func yamlQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
