// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DesktopService from "./desktopservice.js";
import * as DiagnosticsService from "./diagnosticsservice.js";
import * as LumenService from "./lumenservice.js";
import * as RuntimeService from "./runtimeservice.js";
import * as StorageService from "./storageservice.js";
import * as UpdateService from "./updateservice.js";
export {
    DesktopService,
    DiagnosticsService,
    LumenService,
    RuntimeService,
    StorageService,
    UpdateService
};
