// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function ApplyConfig(requestID: string, expectedVersion: number, baseFingerprint: string, candidate: string): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(944333532, requestID, expectedVersion, baseFingerprint, candidate);
}

export function GetSnapshot(): $CancellablePromise<dto$0.RuntimeSnapshot> {
    return $Call.ByID(2760828682);
}

export function PatchConfigDraft(candidate: string, settings: dto$0.RuntimeConfigSettings): $CancellablePromise<dto$0.RuntimeConfigDraft> {
    return $Call.ByID(579392765, candidate, settings);
}

export function ReadConfigDraft(): $CancellablePromise<dto$0.RuntimeConfigDraft> {
    return $Call.ByID(4115928895);
}

export function Restart(requestID: string, expectedVersion: number): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(980638893, requestID, expectedVersion);
}

export function RestoreLastKnownGood(requestID: string, expectedVersion: number): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(889614262, requestID, expectedVersion);
}

export function RetryCleanup(requestID: string, expectedVersion: number): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(1918187668, requestID, expectedVersion);
}

export function SaveConfig(requestID: string, expectedVersion: number, baseFingerprint: string, candidate: string): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(1655885125, requestID, expectedVersion, baseFingerprint, candidate);
}

export function Start(requestID: string, expectedVersion: number): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(3271447106, requestID, expectedVersion);
}

export function Stop(requestID: string, expectedVersion: number): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(1777685442, requestID, expectedVersion);
}

export function ValidateConfig(candidate: string): $CancellablePromise<dto$0.ConfigValidation> {
    return $Call.ByID(2793338578, candidate);
}
