// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function ApproveHostAction(requestID: string, expectedVersion: number, actionID: string, nonce: string): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(1294281888, requestID, expectedVersion, actionID, nonce);
}

export function DeclineHostAction(actionID: string): $CancellablePromise<void> {
    return $Call.ByID(2463511999, actionID);
}

export function ListHostActions(): $CancellablePromise<dto$0.HostActionTicket[] | null> {
    return $Call.ByID(3798355756);
}

export function ListShortcuts(): $CancellablePromise<dto$0.StorageShortcut[] | null> {
    return $Call.ByID(881956902);
}

export function OpenLocation(id: string): $CancellablePromise<void> {
    return $Call.ByID(2120131312, id);
}

export function PickLocation(title: string): $CancellablePromise<string> {
    return $Call.ByID(1903461061, title);
}
