// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function Check(requestID: string, expectedVersion: number): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(2283361891, requestID, expectedVersion);
}

export function Download(requestID: string, expectedVersion: number): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(1375873677, requestID, expectedVersion);
}

export function GetSnapshot(): $CancellablePromise<dto$0.UpdateSnapshot> {
    return $Call.ByID(3612667507);
}

export function RestartAndApply(requestID: string, expectedVersion: number): $CancellablePromise<dto$0.OperationReceipt> {
    return $Call.ByID(3020140871, requestID, expectedVersion);
}
