package service

import (
	"context"
	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
	"server/internal/agent/core"
	"server/internal/agent/tools"
	"testing"
)

func TestMusicAgentEffectAtomicOrderOwnershipAndReplay(t *testing.T) {
	ctx := context.Background()
	catalog, svc, repositoryID := musicTestCatalog(t)
	a := seedMusicTrack(t, catalog, svc, repositoryID, `{"title":"A","artist":"One"}`)
	b := seedMusicTrack(t, catalog, svc, repositoryID, `{"title":"B","artist":"Two"}`)
	run := uuid.New()
	thread := "music-agent-test"
	_, err := catalog.SQL.ExecContext(ctx, `INSERT INTO agent_threads(user_id,thread_id,checkpoint_key,mode,policy_version,created_at,updated_at) VALUES(1,?,'music-checkpoint','free',1,1,1);
 INSERT INTO agent_runs(run_id,user_id,thread_id,started_at,created_at,updated_at) VALUES(?,1,?,1,1,1)`, thread, run, thread)
	require.NoError(t, err)
	tools.RegisterMusic()
	runtime := core.NewEffectRuntime(catalog.SQL, catalog.Writer, catalog.Queries, core.GetRegistry(), svc)
	prepare := func(ids []uuid.UUID, title string, target uuid.UUID, revision int64, skip bool) uuid.UUID {
		id, err := runtime.Prepare(ctx, 1, thread, run, "save_music_playlist", ids, map[string]any{"title": title, "skip_existing": skip}, map[string]any{"playlist_id": target, "revision": revision})
		require.NoError(t, err)
		return id
	}
	effect := prepare([]uuid.UUID{b, a}, "Ordered", uuid.Nil, 0, false)
	page, err := svc.ListPlaylists(ctx, 1, 100, 0)
	require.NoError(t, err)
	require.Zero(t, page.Total)
	_, err = runtime.Commit(ctx, 2, thread, run, effect)
	require.Error(t, err)
	_, err = runtime.Commit(ctx, 1, "other-thread", run, effect)
	require.Error(t, err)
	receipt, err := runtime.Commit(ctx, 1, thread, run, effect)
	require.NoError(t, err)
	require.Equal(t, 2, receipt.Count)
	playlist := uuid.MustParse(receipt.PlaylistID)
	entries, err := svc.ListPlaylistEntries(ctx, 1, playlist)
	require.NoError(t, err)
	require.Len(t, entries, 2)
	require.Equal(t, &b, entries[0].TrackID)
	require.Equal(t, &a, entries[1].TrackID)
	originalIDs := []string{entries[0].EntryID, entries[1].EntryID}
	runtime = core.NewEffectRuntime(catalog.SQL, catalog.Writer, catalog.Queries, core.GetRegistry(), svc)
	retry, err := runtime.Commit(ctx, 1, thread, run, effect)
	require.NoError(t, err)
	require.True(t, retry.AlreadyCommitted)
	require.Equal(t, receipt.PlaylistID, retry.PlaylistID)
	p, err := svc.GetPlaylist(ctx, 1, playlist)
	require.NoError(t, err)
	stale := prepare([]uuid.UUID{a}, "append", playlist, p.Revision, false)
	_, err = svc.UpdatePlaylist(ctx, 1, playlist, "Changed", "", p.Revision)
	require.NoError(t, err)
	_, err = runtime.Commit(ctx, 1, thread, run, stale)
	require.ErrorIs(t, err, ErrMusicConflict)
	p, err = svc.GetPlaylist(ctx, 1, playlist)
	require.NoError(t, err)
	duplicate := prepare([]uuid.UUID{a}, "append", playlist, p.Revision, false)
	_, err = runtime.Commit(ctx, 1, thread, run, duplicate)
	require.NoError(t, err)
	entries, err = svc.ListPlaylistEntries(ctx, 1, playlist)
	require.NoError(t, err)
	require.Len(t, entries, 3)
	require.Equal(t, originalIDs, []string{entries[0].EntryID, entries[1].EntryID})
	require.Equal(t, &a, entries[2].TrackID)
	p, err = svc.GetPlaylist(ctx, 1, playlist)
	require.NoError(t, err)
	dedup := prepare([]uuid.UUID{a, b}, "dedup", playlist, p.Revision, true)
	saved, err := runtime.Commit(ctx, 1, thread, run, dedup)
	require.NoError(t, err)
	require.Zero(t, saved.Count)
	declined := prepare([]uuid.UUID{a}, "declined", uuid.Nil, 0, false)
	require.NoError(t, runtime.Reject(ctx, 1, thread, declined))
	_, err = runtime.Commit(ctx, 1, thread, run, declined)
	require.Error(t, err)
	deleted := prepare([]uuid.UUID{b}, "deleted", uuid.Nil, 0, false)
	_, err = catalog.SQL.ExecContext(ctx, `UPDATE assets SET is_deleted=1 WHERE asset_id=?`, b)
	require.NoError(t, err)
	_, err = runtime.Commit(ctx, 1, thread, run, deleted)
	require.Error(t, err)
	page, err = svc.ListPlaylists(ctx, 1, 100, 0)
	require.NoError(t, err)
	require.EqualValues(t, 1, page.Total)
	// A receipt failure must roll back the newly created playlist and entries.
	atomicEffect := prepare([]uuid.UUID{a}, "atomic", uuid.Nil, 0, false)
	_, err = catalog.SQL.ExecContext(ctx, `CREATE TRIGGER fail_music_receipt BEFORE UPDATE ON agent_pending_effects WHEN NEW.status='committed' BEGIN SELECT RAISE(ABORT,'fixture receipt failure'); END`)
	require.NoError(t, err)
	_, err = runtime.Commit(ctx, 1, thread, run, atomicEffect)
	require.Error(t, err)
	page, err = svc.ListPlaylists(ctx, 1, 100, 0)
	require.NoError(t, err)
	require.EqualValues(t, 1, page.Total)
	_, err = catalog.SQL.ExecContext(ctx, `DROP TRIGGER fail_music_receipt`)
	require.NoError(t, err)
	_, err = runtime.Commit(ctx, 1, thread, run, atomicEffect)
	require.NoError(t, err)

}

func TestAgentMusicSearchOwnerScopeAndMetadata(t *testing.T) {
	ctx := context.Background()
	catalog, svc, repositoryID := musicTestCatalog(t)
	a := seedMusicTrack(t, catalog, svc, repositoryID, `{"title":"Alpha","artist":"One","genre":"Jazz"}`)
	b := seedMusicTrack(t, catalog, svc, repositoryID, `{"title":"Beta","artist":"Two","genre":"Rock"}`)
	_, err := catalog.SQL.ExecContext(ctx, `UPDATE assets SET liked=1,rating=4,duration=120 WHERE asset_id=?`, a)
	require.NoError(t, err)
	library := core.NewAuthorizedLibraryFactory(catalog.Queries, nil).ForUser(1)
	rows, _, err := library.SearchMusic(ctx, core.MusicSearch{LikedOnly: true, MinRating: 4, MissingLyrics: true, MissingCover: true}, nil)
	require.NoError(t, err)
	require.Len(t, rows, 1)
	require.Equal(t, a, rows[0].TrackID)
	ordered, err := library.MusicTracks(ctx, []uuid.UUID{b, a})
	require.NoError(t, err)
	require.Equal(t, b, ordered[0].TrackID)
	rows, _, err = library.SearchMusic(ctx, core.MusicSearch{Query: "Alpha"}, []uuid.UUID{b})
	require.NoError(t, err)
	require.Empty(t, rows)
	_, err = core.NewAuthorizedLibraryFactory(catalog.Queries, nil).ForUser(2).MusicTracks(ctx, []uuid.UUID{a})
	require.Error(t, err)
	rows, _, err = library.SearchMusic(ctx, core.MusicSearch{DurationBudgetSeconds: 120}, nil)
	require.NoError(t, err)
	require.Len(t, rows, 1)
}
