name: Deploy Specific Folders to R2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Upload specific folders to R2
              run: |
                  echo "Uploading files from pml, server, and web directories..."

                  for file in $(find pml server web -type f); do
                    echo "Putting ${file} to r2://${{ secrets.R2_BUCKET_NAME }}/${file}"
                    npx wrangler r2 object put ${{ secrets.R2_BUCKET_NAME }}/${file} --file=${file}
                  done

                  echo "Upload complete."
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
