# .github/workflows/deploy.yml
name: Deploy Specific Folders to R2

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup rclone and sync to R2
              run: |
                  curl https://rclone.org/install.sh | sudo bash

                  rclone sync . :s3,provider=Cloudflare,access_key_id=${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }},secret_access_key=${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }},endpoint=1b7c97a6a0b3abf6e8c376b5db57a00a.r2.cloudflarestorage.com/:lumilio-photos-code/ \
                              --filter "+ /pml/**" \
                              --filter "+ /server/**" \
                              --filter "+ /web/**" \
                              --filter "- *" \
                              --fast-list \
                              --transfers 16 \
                              -v --progress
