# .github/workflows/deploy.yml
name: Deploy Specific Folders to R2

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup rclone and sync to R2
              run: |
                  sudo apt-get update && sudo apt-get install -y rclone

                  rclone sync . r2:lumilio-photos-code \
                              --filter "+ /pml/**" \
                              --filter "+ /server/**" \
                              --filter "+ /web/**" \
                              --filter "- *" \
                              --fast-list \
                              --transfers 16 \
                              -v --progress

              # Updated
              env:
                  RCLONE_CONFIG_R2_TYPE: s3
                  RCLONE_CONFIG_R2_PROVIDER: Cloudflare
                  RCLONE_CONFIG_R2_ENDPOINT: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
                  RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
                  RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
                  RCLONE_CONFIG_R2_ACL: private
