name: Generate OpenAPI & Redoc

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Swagger tools
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate OpenAPI docs with swag
        run: |
          cd server
          swag init --output ../docs/openapi

      - name: Install redoc-cli
        run: npm install -g redoc-cli

      - name: Generate Redoc static HTML
        run: |
          npx redoc-cli bundle ./docs/openapi/swagger.json -o redoc-static.html

      - name: Move Redoc HTML to docs/public
        run: |
          mv -f redoc-static.html ./docs/public/redoc-static.html